Import('env')

env['LIBS'] = ['analysis', 'framework', 'analysis_dataobjects', 'pxd_dataobjects', 'svd_dataobjects', 'cdc_dataobjects', 'vxd_dataobjects', 'tracking_dataobjects', 'generators_dataobjects', 'ecl_dataobjects', 'genfit', 'RaveBase', 'CLHEP']
Return('env')

