Import('env')

env['LIBS'] = [
  'tracking',
  'tracking_dataobjects',
  'tracking_trackFindingCDC',
	'pxd_dataobjects',
  'svd_dataobjects',
	'cdc_dataobjects',
	'genfit2',
	'framework',
	'mdst_dataobjects',
	]
Return('env')

