Import('env')                                                                                                                           

env['LIBS'] = ['framework', 'ecl', 'ecl_dataobjects', '$ROOT_LIBS', 'mdst_dataobjects']

Return('env')
