Import('env')                                                                                                                           

env['LIBS'] = ['framework', 'ecl', 'ecl_dbobjects', 'ecl_dataobjects', '$ROOT_LIBS', 'mdst_dataobjects', 'analysis', 'analysis_utility', 'analysis_ClusterUtility']

Return('env')
