Import('env')
env['SUBLIB'] = True

#env['LIBS'] = ['$ROOT_LIBS', 'Geom',
#               'G4root', '$GEANT4_LIBS', 'CLHEP',
#               'boost_python', 'boost_filesystem',
#               '$PYTHON_LIBS', '$XML_LIBS']

env['LIBS'] = ['$ROOT_LIBS', 'rawdata_dataobjects', 'daq_dataobjects', 'daq', 'framework' ]

Return('env')
