Import('env')

env['LIBS'] = [ 'framework', 'geometry','generators_dataobjects', 'vxd','pxd_dataobjects','svd_dataobjects','cdc_dataobjects', 'cdc','tracking_dataobjects', 'genfit', 'RKTrackRep']
Return('env')

