  enum INAME {
    b_t3_0, b_t3_1, b_t3_2, b_t3_3,
    b_t2_0, b_t2_1, b_t2_2, b_t2_3,
    b_cdc_open90,
    b_cdc_active,
    b_cdc_b2b3, b_cdc_b2b5, b_cdc_b2b7, b_cdc_b2b9,
    b_ehigh,
    b_elow,
    b_elum,
    b_ecl_bha,
    b_bha_type_0, b_bha_type_1, b_bha_type_2, b_bha_type_3, b_bha_type_4,
    b_bha_type_5, b_bha_type_6, b_bha_type_7, b_bha_type_8, b_bha_type_9, b_bha_type_10,
    b_bha_type_11, b_bha_type_12, b_bha_type_13,
    b_clst_0, b_clst_1, b_clst_2, b_clst_3,
    b_ecl_bg_0, b_ecl_bg_1, b_ecl_bg_2,
    b_ecl_active,
    b_ecl_timing_fwd,
    b_ecl_timing_brl,
    b_ecl_timing_bwd,
    b_ecl_phys,
    b_top_0, b_top_1, b_top_2,
    b_top_bb,
    b_top_active,
    b_klm_hit,
    b_klm_0, b_klm_1, b_klm_2, b_klm_3,
    b_klmb2b_0, b_klmb2b_1, b_klmb2b_2,
    b_revo,
    b_her_kick,
    b_ler_kick,
    b_bha_delay,
    b_pseud_rand, b_plsin, b_poissonin, b_periodin,
    b_veto,
    b_nclst1_0, b_nclst1_1, b_nclst1_2,
    b_nclst2_0, b_nclst2_1, b_nclst2_2,
    b_cdcecl_0, b_cdcecl_1, b_cdcecl_2, b_cdcecl_3,
    b_cdcklm_0, b_cdcklm_1, b_cdcklm_2, b_cdcklm_3,
    b_nimin0,
    b_nimin1,
    b_nimin2,
    b_nimin3,
    b_u2_0, b_u2_1, b_u2_2, inp87, inp88, inp89,
    inp90, inp91, inp92, inp93, inp94, inp95
};

  enum ONAME {
      b_zzz, b_zzzo,
      b_fff, b_fffo,
      b_zz, b_zzo,
      b_ffb, b_ffo,
      b_hie, b_lowe, b_lume,
      b_c2, b_c3, b_c4, b_c5,
      b_bhabha, b_bhabha_trk, b_bhabha_brl, b_bhabha_ecp,
      b_g_high, b_g_c1, b_gg,
      b_mu_pair, b_mu_b2b,
      b_revolution,
      b_random,
      b_bg,
      b_ecltiming,
      b_nim0,
      b_nima03,
      b_nimo03,
      b_period,
      b_eclnima03, b_eclnimo03,
      b_pls, b_poisson,
      b_klmhit,
      b_f, b_fe, b_ffe,
      b_fc, b_ffc,
      b_cdctiming,
      b_cdcbb, b_nim1c,
      b_c1n0, b_c1n1, b_c1n2, b_c1n3, b_c1n4, 
      b_c2n1, b_c2n2, b_c2n3, b_c2n4, 
      b_cdcecl1, b_cdcecl2, b_cdcecl3, b_cdcecl4, 
      b_cdcklm1, b_cdcklm2, b_cdcklm3, b_cdcklm4, 
      b_ff,
      b_uuu, b_uuuo,
      b_uub, b_uuo,
      b_c1hie, b_c1lume, b_n1hie, b_n1lume,
      b_oup71, b_oup72, b_oup73, b_oup74,
      b_oup75, b_oup76, b_oup77, b_oup78, b_oup79,
      b_oup80, b_oup81, b_oup82, b_oup83, b_oup84,
      b_oup85, b_oup86, b_oup87, b_oup88, b_oup89,
      b_oup90, b_oup91, b_oup92, b_oup93, b_oup94,
      b_oup95
};

  const char *CINAME[] = {
    "t3_0", "t3_1", "t3_2", "t3_3",
    "t2_0", "t2_1", "t2_2", "t2_3",
    "cdc_open90",
    "cdc_active",
    "cdc_b2b3", "cdc_b2b5", "cdc_b2b7", "cdc_b2b9",
    "ehigh",
    "elow",
    "elum",
    "ecl_bha",
    "bha_type_0", "bha_type_1", "bha_type_2", "bha_type_3", "bha_type_4",
    "bha_type_5", "bha_type_6", "bha_type_7", "bha_type_8", "bha_type_9", "bha_type_10",
    "bha_type_11", "bha_type_12", "bha_type_13",
    "clst_0", "clst_1", "clst_2", "clst_3",
    "ecl_bg_0", "ecl_bg_1", "ecl_bg_2",
    "ecl_active",
    "ecl_timing_fwd",
    "ecl_timing_brl",
    "ecl_timing_bwd",
    "ecl_phys",
    "top_0", "top_1", "top_2",
    "top_bb",
    "top_active",
    "klm_hit",
    "klm_0", "klm_1", "klm_2", "klm_3",
    "klmb2b_0", "klmb2b_1", "klmb2b_2",
    "revo",
    "her_kick",
    "ler_kick",
    "bha_delay",
    "pseud_rand", "plsin", "poissonin", "periodin",
    "veto",
    "nclst1_0", "nclst1_1", "nclst1_2",
    "nclst2_0", "nclst2_1", "nclst2_2",
    "cdcecl_0", "cdcecl_1", "cdcecl_2", "cdcecl_3",
    "cdcklm_0", "cdcklm_1", "cdcklm_2", "cdcklm_3",
    "nimin0",
    "nimin1",
    "nimin2",
    "nimin3",
    "u2_0", "u2_1", "u2_2",
    "inp87", "inp88", "inp89", "inp90", "inp91", "inp92", "inp93", "inp94", 
    "inp95", 
};

  const char  *CONAME[] = {
      "zzz", "zzzo",
      "fff", "fffo",
      "zz", "zzo",
      "ffb", "ffo",
      "hie", "lowe", "lume",
      "c2", "c3", "c4", "c5",
      "bhabha", "bhabha_trk", "bhabha_brl", "bhabha_ecp",
      "g_high", "g_c1", "gg",
      "mu_pair", "mu_b2b",
      "revolution",
      "random",
      "bg",
      "ecltiming",
      "nim0",
      "nima03",
      "nimo03",
      "period",
      "eclnima03", "eclnimo03",
      "pls", "poisson",
      "klmhit",
      "f", "fe", "ffe",
      "fc", "ffc",
      "cdctiming",
      "cdcbb", "nim1c",
      "c1n0", "c1n1", "c1n2", "c1n3", "c1n4", 
      "c2n1", "c2n2", "c2n3", "c2n4", 
      "cdcecl1", "cdcecl2", "cdcecl3", "cdcecl4", 
      "cdcklm1", "cdcklm2", "cdcklm3", "cdcklm4", 
      "ff",
      "uuu", "uuuo",
      "uub", "uuo",
      "c1hie", "c1lume", "n1hie", "n1lume",
      "oup71", "oup72", "oup73", "oup74",
      "oup75", "oup76", "oup77", "oup78", "oup79",
      "oup80", "oup81", "oup82", "oup83", "oup84",
      "oup85", "oup86", "oup87", "oup88", "oup89",
      "oup90", "oup91", "oup92", "oup93", "oup94",
      "oup95"
};

    /** enum of leafs **/
    enum EBits {
      e_rvc,
      e_timtype,
      e_etyp,
      e_tdtimtyp,
      e_tdsrcp,
      e_tdtopp,
      e_tdeclp,
      e_tdcdcp,
      e_rvcout,
      e_toprvc,
      e_eclrvc,
      e_cdcrvc,
      e_toptiming,
      e_ecltiming,
      e_cdctiming,
      e_nim0rvc,
      e_dtoprvc,
      e_declrvc,
      e_dcdcrvc,
      e_psn2,
      e_psn1,
      e_psn0,
      e_topslot1,
      e_topslot0,
      e_ntopslot,
      e_ftd2,
      e_ftd1,
      e_ftd0,
      e_itd2,
      e_itd1,
      e_itd0,
      e_evt, e_clk, e_firmid, e_firmver, e_finalrvc, e_drvc, e_gdll1rvc, e_coml1rvc, e_b2ldly, e_maxrvc
    };

