Import('env')
env['LIBS'] = ['framework',
               'framework_io',
               'boost_python',
               '$ROOT_LIBS',
               'calibration_dataobjects',
               ]
Return('env')
