Import('env')

env['LIBS'] = [ 'framework', 'mdst_dataobjects', 'geometry', 'vxd_dataobjects','pxd','pxd_dataobjects','svd','svd_dataobjects', 'cdc_dataobjects', 'cdc', 'testbeam_vxd_dataobjects', 'testbeam', 'genfit2']
Return('env')

