Import('env')

env['LIBS'] = [ 'framework', 'mdst_dataobjects', 'pxd', 'svd', 'cdc_dataobjects', 'cdc', 'genfit2', 'alignment', 'bklm_dataobjects',
'pxd_dataobjects', 'svd_dataobjects', 'eklm_dataobjects']

if 'ALLOW_TELESCOPES_IN_GBLFITMODULE' in env['CPPDEFINES']:
    env['LIBS'] += ['testbeam_vxd_dataobjects', 'testbeam']

Return('env')

