Import('env')

env['LIBS'] = [ 'framework', 'mdst_dataobjects', 'geometry', 'vxd_dataobjects','pxd','pxd_dataobjects','svd','svd_dataobjects', 'cdc_dataobjects', 'cdc', 'genfit2']

if 'ALLOW_TELESCOPES_IN_GBLFITMODULE' in env['CPPDEFINES'].keys():
    env['LIBS'] += ['testbeam_vxd_dataobjects', 'testbeam']

Return('env')

