Import('env')

env['LIBS'] = ['eklm', 'framework', 'eklm_dataobjects', 'tracking_dataobjects',
               'simulation_dataobjects', 'mdst_dataobjects',
               '$ROOT_LIBS']

Return('env')

