Import('env')
env['LIBS'] = ['$ROOT_LIBS', 'framework', 'reconstruction_dataobjects', 'reconstruction_dbobjects', 'genfit2', 'cdc', 'tracking_dataobjects', 'cdc_dataobjects', 'mdst_dataobjects', 'vxd']
Return('env')

