Import('env')

env['LIBS'] = ['framework', 'calibration', 'top', 'top_reconstruction',
               'top_dataobjects', 'mdst_dataobjects', 'tracking_dataobjects',
               '$ROOT_LIBS', 'gfortran']

Return('env')
