#!/usr/bin/env python3

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

"""
You can run ``b2help-variables`` to list all available variables.
"""
import argparse
from terminal_utils import Pager
from variables import printVars, printVariableType


def get_argument_parser():
    parser = argparse.ArgumentParser(description="""
This returns the description of variables whixh are available in the `analysis` package of basf2.

- Display all available variables
    ``b2help-variables``

- Description of the provided variables
    ``b2help-variables --variables M Mbc isSignal``

- Only the data type of the provided variables
    ``b2help-variables --variables M Mbc isSignal --only_type``
""")
    parser.add_argument('--no-pager', dest='pager', default=True, action='store_false',
                        help='Use a pager to show output or print to terminal.')
    parser.add_argument('--variables', nargs='+', default=None, 
                        help='Input variables to be displayed.')
    parser.add_argument('--only_type', default=False, action='store_true', 
                        help='Show only the data type of variable. This option requires the variable names with ``--variables``')
    return parser



if __name__ == "__main__":
    args = get_argument_parser().parse_args()

    warning = (
        "The following variables have been renamed since release-04:\n"
        "old: mcFlavorOfOtherB0 --> new: mcFlavorOfOtherB\n"
        "old: mdstSource --> new: uniqueParticleIdentifier\n"
        "old: MCDeltaT --> new: mcDeltaT\n"
        "old: mc{X, Y, Z} --> new: mcDecayVertex{X, Y, Z}\n"
        "old: mcRho --> new: mcDecayVertexRho\n"
        "old: mcProdVertex{X, Y, Z} --> new: mcProductionVertex{X, Y, Z}\n"
        "old: mcProdVertexD{X, Y, Z} --> new: mcProductionVertexFromIP{X, Y ,Z}\n"
        "old: mcDistance --> new: mcDecayVertexFromIPDistance\n"
        "old: WE_XXX, ROE_XXX, Rec_XXX --> new: weXXX, roeXXX, recXXX\n\n"
        "The variables 'decayAngle', 'daughterAngle', and 'pointingAngle' return angles in rad and no longer the corresponding "
        "cosine!\n"

        "The following variables have been renamed since release-05:\n"
        "old: TagVmcLBoost --> new: mcTagVLBoost\n"
        "old: TagVmcOBoost --> new: mcTagVOBoost\n"
        "old: mcDeltaL --> new: mcDeltaBoost\n"
	"old: L1TimQuality --> new: L1TimeQuality\n"

        "The following variables have been renamed since release-06:\n"
        "old: beamBackgroundProbabilityMVA --> new: beamBackgroundSuppression\n"

        "The following variables have been renamed since release-07:\n"
        "old: hadronicSplitOffSuppression --> new: fakePhotonSuppression\n"

    )

    if args.only_type:
        printVariableType(args.variables)
    else:
        if args.pager:
            with Pager(r'Available variables in Variable\:\:Manager'):
                printVars(warning, args.variables)
        else:
            printVars(warning, args.variables)
