#!/usr/bin/env python3

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

"""
You can run ``b2help-variable-type`` to show the return type of the provided variables.
"""
import argparse
from variables import printVariableType


def get_argument_parser():
    parser = argparse.ArgumentParser(description="""
This returns the data type of the return type of the return value of the provided variables.

Usage:
    ``b2help-variable-type M E isSignal``
""")

    parser.add_argument('variables', nargs='+', default=None, 
                        help='input variables')
    return parser


if __name__ == "__main__":
    args = get_argument_parser().parse_args()

    printVariableType(args.variables)
