#!/usr/bin/env python3

/**************************************************************************
 * basf2 (Belle II Analysis Software Framework)                           *
 * Author: The Belle II Collaboration                                     *
 *                                                                        *
 * See git log for contributors and copyright holders.                    *
 * This file is licensed under LGPL-3.0, see LICENSE.md.                  *
 **************************************************************************/

"""
You can run ``b2help-variables`` to list all available variables.
"""
import argparse
from terminal_utils import Pager
from variables import printVars


def get_argument_parser():
    parser = argparse.ArgumentParser(description="""
This returns all variables which are available in the `analysis` package of basf2.

Usage:
    ``b2help-variables``
""")
    parser.add_argument('--no-pager', dest='pager', default=True, action='store_false',
                        help='Use a pager to show output or print to terminal.')
    return parser



if __name__ == "__main__":
    args = get_argument_parser().parse_args()

    warning = (
        "The following variables have been renamed since release-04:\n"
        "old: mcFlavorOfOtherB0 --> new: mcFlavorOfOtherB\n"
        "old: mdstSource --> new: uniqueParticleIdentifier\n"
        "old: MCDeltaT --> new: mcDeltaT\n"
        "old: mc{X, Y, Z} --> new: mcDecayVertex{X, Y, Z}\n"
        "old: mcRho --> new: mcDecayVertexRho\n"
        "old: mcProdVertex{X, Y, Z} --> new: mcProductionVertex{X, Y, Z}\n"
        "old: mcProdVertexD{X, Y, Z} --> new: mcProductionVertexFromIP{X, Y ,Z}\n"
        "old: mcDistance --> new: mcDecayVertexFromIPDistance\n"
        "old: WE_XXX, ROE_XXX, Rec_XXX --> new: weXXX, roeXXX, recXXX\n\n"
        "The variables 'decayAngle', 'daughterAngle', and 'pointingAngle' return angles in rad and no longer the corresponding "
        "cosine!\n"

        "The following variables have been renamed since release-05:\n"
        "old: TagVmcLBoost --> new: mcTagVLBoost\n"
        "old: TagVmcOBoost --> new: mcTagVOBoost\n"
        "old: mcDeltaL --> new: mcDeltaBoost\n"
	"old: L1TimQuality --> new: L1TimeQuality\n"
    )
    if args.pager:
        with Pager(r'Available variables in Variable\:\:Manager'):
            printVars(warning)
    else:
        printVars(warning)
