#!/usr/bin/env python3

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

"""
Print the MCParticles of the given mdst file.
"""

import argparse

import basf2 as b2
import modularAnalysis as ma

def get_argument_parser():
    parser = argparse.ArgumentParser(description="""
This command prints the MCParticles of the given mdst file.
By default, only the first event is displaied. One can specify the number of events to be displaied by ``-n`` option.
""")
    parser.add_argument('filename', help='Input file.')
    parser.add_argument('-n', '--num_events', type=int, default=1,
                        help='Number of events to display.')
    return parser


def main(filename, num_events):
    main = b2.Path()
    ma.inputMdst(filename, path=main)

    ma.printMCParticles(path=main)
    b2.process(main, num_events)

if __name__ == "__main__":

    args = get_argument_parser().parse_args()
    main(args.filename, args.num_events)
