#!/usr/bin/env python3

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

# Removes broken or empty root files in the current directory

import ROOT
import os

if __name__ == '__main__':
    for filename in [f for f in os.listdir('.') if os.path.isfile(f) and f.endswith('.root')]:
        rootfile = ROOT.TFile(filename)
        n = len(rootfile.GetListOfKeys())
        z = rootfile.IsZombie()
        rootfile.Close()
        if n == 0 or z:
            print(f'Remove broken or empty ROOT file {filename} (y/n)?')
            if input() == 'y':
                os.remove(filename)
