#!/bin/bash
# createAnalysisPlots.sh
# Create Control Plots as png for a training stored in root file created by TMVATeacher

if [ $# -ne 2 ]
then
  echo "Usage: createAnalysisPlots TMVA_PREFIX PRECUT_PREFIX"
  echo "TMVA_PREFIX: $PREFIX_1_vs_0.root"
  exit 1
fi

#get full path
TF=$1
PF=$2

TMVA_FILE=`readlink -f "$TF"_1_vs_0.root`
PRECUT_FILE=`readlink -f "$PF".root`

cd $BELLE2_EXTERNALS_DIR/src/root/tmva/test/
if [ $? -ne 0 ]
then
  echo "Directory src/root/tmva/test not found in externals. Please re-install from source."
  exit 1
fi
cd -

root -l -q -b "$BELLE2_EXTERNALS_DIR/src/root/tmva/test/mvas.C(\"$TMVA_FILE\",3)"
cp plots/$(ls -t plots/ | head -1) overtraining.png

root -l -q -b "$BELLE2_EXTERNALS_DIR/src/root/tmva/test/efficiencies.C(\"$TMVA_FILE\")"
cp plots/$(ls -t plots/ | head -1) roc.png

echo "auto keys = _file0->GetListOfKeys();
      TCanvas canvas1(\"signal_canvas\", \"signal\", 600, 400);
      canvas1.cd()
      auto hist1 = _file0->Get(keys.At(0).GetName());
      hist1->Draw();
      canvas1.SaveAs(\"signal.png\");
      TCanvas canvas2(\"all_canvas\", \"all\", 600, 400);
      canvas2.cd()
      auto hist2 = _file0->Get(keys.At(1).GetName());
      hist2->Draw();
      canvas2.SaveAs(\"all.png\");
      TCanvas canvas3(\"bckgrd_canvas\", \"background\", 600, 400);
      canvas3.cd()
      auto hist3 = _file0->Get(keys.At(2).GetName());
      hist3->Draw();
      canvas3.SaveAs(\"background.png\");
      TCanvas canvas4(\"ratio_canvas\", \"ratio\", 600, 400);
      canvas4.cd()
      auto hist4 = _file0->Get(keys.At(3).GetName());
      hist4->Draw();
      canvas4.SaveAs(\"ratio.png\");
      .q" | root -l -b "$PRECUT_FILE"
      
      
echo "$TMVA_FILE"
echo "$PRECUT_FILE"