#!/bin/bash
# Runs the externTeacher tool as a job on the cluster

f=`mktemp`
echo "Use $f as temporary file"
echo "externTeacher $*" > "$f"
cat "$f"
bsub -K -q lx -e "$f".elog -o "$f".log "$f"
rm $f

