#!/bin/bash
# Runs the externTeacher tool as a job on the cluster

rf=`mktemp`
f=$(basename $rf)
echo "Use $f as temporary file"
printf " %q" externTeacher "$@" > "$f" 
#echo "externTeacher $*" > "$f"
cat "$f"
chmod +x ./"$f"
echo bsub -K -q sx -e "$f".elog -o "$f".log "$f"
bsub -K -q sx -e "$f".elog -o "$f".log ./"$f"
#rm $f
