Import('env')

env['TOOLS_LIBS']['externTeacher'] = ['stdc++', 'framework', 'analysis', 'boost_program_options', '$ROOT_LIBS']

env['TOOLS_LIBS']['variableCutParser'] = ['stdc++', 'framework', 'analysis', 'analysis_dataobjects', '$ROOT_LIBS']

Return('env')
