#!/usr/bin/env bash
#
# Shows Control Plots for a training stored in root file created by TMVATeacher

printUsage() {
  echo "Usage: showTMVAResults TMVA_TRAINING_OUTPUT"
  echo "where TMVA_TRAINING_OUTPUT is the ROOT file produced during the training (usually with suffix _1.root)."
}
if [ $# -ne 1 ]
then
  printUsage
  exit 1
fi

if [ ! -f $1 ]
then
  printUsage
  echo ""
  echo "File '$1' not found!"
  exit 1
fi

#get full path
FILE=`readlink -f "$1"`

cd $BELLE2_EXTERNALS_DIR/share/root/tmva/
if [ $? -ne 0 ]
then
  echo "Directory share/root/tmva not found in externals. Please update to at least version v00-05-04"
  exit 1
fi

#set TMVASYS to avoid some (noncritical) errors
TMVASYS="$ROOTSYS" root -e "TMVA::TMVAGui(\"$FILE\")"
