#!/usr/bin/env bash
# showTMVAResults.sh TMVA.root
# Shows Control Plots for a training stored in root file created by TMVATeacher

printUsage() {
  echo "Usage: showTMVAResults TMVA_TRAINING_OUTPUT"
  echo "where TMVA_TRAINING_OUTPUT is the ROOT file produced during the training (usually with suffix _1.root)."
}
if [ $# -ne 1 ]
then
  printUsage
  exit 1
fi

if [ ! -f $1 ]
then
  printUsage
  echo ""
  echo "File '$1' not found!"
  exit 1
fi

#get full path
FILE=`readlink -f "$1"`

cd $BELLE2_EXTERNALS_DIR/src/root/tmva/test/
if [ $? -ne 0 ]
then
  echo "Directory src/root/tmva/test not found in externals. Please re-install from source."
  exit 1
fi

#set TMVASYS to avoid some (noncritical) errors
TMVASYS="$ROOTSYS" root -l "$BELLE2_EXTERNALS_DIR/src/root/tmva/test/TMVAGui.C(\"$FILE\")"
