Import('env')

env['LIBS'] = ['framework',
               'cdc',
               'cdc_dataobjects',
               'trg_cdc_dataobjects',
               '',
               'dl',
               'rt']
               
vivado_lib = '/home/belle2/tasheng/Vivado_2017.2/lib/lnx64.o/'
xsim_lib = '/home/belle2/tasheng/Vivado_2017.2/data/xsim/include'
env.Append(CPPPATH=[vivado_lib])
env.Append(CPPPATH=[xsim_lib])
loader = SharedObject(target='xsi_loader.o', source='src/xsi_loader.cpp', CPPPATH=['include', xsim_lib])
env.Append(LIBS=loader)

# env['ENV']['LD_LIBRARY_PATH'] += ':/home/belle2/tasheng/Vivado_2017.2/lib/lnx64.o/'
Return('env')
