Import('env')

#These are the libraries the awesome package has to be linked against
env['LIBS'] = ['framework', '$ROOT_LIBS', 'mdst_dataobjects','vtx_dataobjects', 'vxd', 'vxd_dataobjects', 'vtx']

Return('env')
