Import('env')

env['LIBS'] = [
    'framework',
    'mdst_dataobjects',
    'genfit2',
    'vxd',
    'geometry',
    'pxd_dataobjects',
    'svd_dataobjects',
    'vxd_dataobjects',
    'tracking_dataobjects',
    ]

Return('env')

