Import('env')

env['LIBS'] = ['framework', 'analysis_dataobjects', 'analysis_KFit', 
	      'analysis_raveInterface', 'analysis_DecayDescriptor', 'mdst_dataobjects',
	      'analysis', 'genfit2', 'RaveBase', '$ROOT_LIBS', 'CLHEP']

Return('env')
