Import('env')
env['LIBS'] = [
    '$ROOT_LIBS',
    'framework',
    'pxd_dataobjects',
    'svd_dataobjects',
    'vxd_dataobjects',
    'tracking',
    'tracking_dataobjects',
    'mdst_dataobjects',
    'vxd'
    ]
Return('env')
