Import('env')
#env['CONTINUE'] = False

env['LIBS'] = [
    'CLHEP',
    '$ROOT_LIBS',
    '$GEANT4_LIBS',
    'framework',
    'simulation', 
    'ecl',
    'tracking_dataobjects',
    'mdst_dataobjects',
    'genfit2',
    'mdst_dataobjects',
    ]

Return('env')
