Import('env')

env['LIBS'] = ['analysis', 'framework', 'generators', 'pxd_dataobjects', 'svd_dataobjects', 'cdc_dataobjects', 'vxd_dataobjects', 'tracking_dataobjects', 'generators_dataobjects', 'arich_dataobjects', 'top_dataobjects', 'reconstruction_dataobjects', 'genfit', 'CLHEP']
Return('env')

