Import('env')

env['LIBS'] = ['analysis', 'framework', 'generators', 'geometry', 'pxd_dataobjects', 'svd_dataobjects', 'cdc_dataobjects', 'vxd_dataobjects', 'tracking_dataobjects', 'genfit']
Return('env')

