Import('env')

env['LIBS'] = ['tracking', 'vxd', 'pxd', 'svd', 'svd_dataobjects', 'tracking_dataobjects', 'mdst_dataobjects', 'tracking', 'framework', 'generators', 'geometry', 'simulation', 'genfit2', 'reconstruction']
Return('env')

