Import('env')

env['LIBS'] = ['pxd', 'svd', 'framework', 'geometry', 'simulation',
               '$ROOT_LIBS', 'Geom', 'EG', 'G4root', 'tracking', 'cairo',
               '$GEANT4_LIBS', 'CLHEP']

Return('env')
