Import('env')

env['LIBS'] = ['$ROOT_LIBS', 'framework', 'geometry', 'simulation', 'simulation_dataobjects',
    'generators_dataobjects', 'geometry', 'vxd', 'vxd_dataobjects',
    'pxd_dataobjects', 'svd_dataobjects', 'genfit']

Return('env')