Import('env')

env['LIBS'] = ['$ROOT_LIBS', 'framework', 'geometry', 'simulation',
    'mdst_dataobjects', 'geometry', 'vxd', 'vxd_dataobjects',
    'pxd_dataobjects', 'svd_dataobjects', 'testbeam_vxd_dataobjects', 
    'testbeam_top_dataobjects', 'tracking', 'pxd', 'svd', 'genfit2']

Return('env')
