Import('env')

env['LIBS'] = ['framework',
               #'geometry',
               'mdst_dataobjects',
               'pxd_dataobjects',
               'svd_dataobjects',
               'tracking']

Return('env')
