Import('env')

env['LIBS'] = [
    'framework',
    'mdst_dataobjects',
    'simulation_dataobjects',
    'vxd_dataobjects',
    'pxd_dataobjects', 
    'svd_dataobjects',
    'cdc', 'cdc_dataobjects',
    'genfit2',
    ]

Return('env')

