#!/bin/bash

which doxygen &> /dev/null
if [ $? -ne 0 ]; then
    echo "doxygen executable not found. Doxygen must be installed for this script to work"
    exit 1;
fi

# check for help argument
echo $@ | grep -E -- "(^|\\s)(--help|-h)($|\\s)" &>/dev/null
if [ $? -eq 0 ]; then
    cat <<EOT
This script will try to show all doxygen warnings about undocumented items
similar to the development build. To run it on single files or directories just
supply them as arguments:
    $0 [<directory>...] [<filename>...]

To run on the full release directory run it without any arguments:
    $0
EOT
    exit 1;
fi

# collect arguments or use belle2 release directory
FILES=${@:-$BELLE2_LOCAL_DIR}

# call doxygen on the files from the command line arguments
sed "s;INPUT                  =;INPUT                  = ${FILES};" ${BELLE2_LOCAL_DIR}/site_scons/doxygen/Doxyfile | doxygen - 2>&1 >/dev/null | grep "" && exit 1 || exit 0
