#!/bin/bash

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

output_dir=$(mktemp -d)
use_temp_dir=true

while [[ $# -gt 0 ]]; do
    case "$1" in
        -o|--output)
            output_dir="$2"
            use_temp_dir=false
            shift 2
            ;;
        -h|--help)
            cat <<EOT
This script will create the Sphinx documentation and check whether there are any warnings.
Options:
  -o, --output DIR       Specify the output directory.
  -h, --help             Display this help message.
All extra arguments are forwarded to b2code-sphinx-build.
EOT
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

# remove temporary directory on exit if it was created
if [ "$use_temp_dir" = true ]; then
    trap "rm -rf $output_dir" EXIT
fi

# build sphinx documentation with html option
output=$(b2code-sphinx-build --output-dir ${output_dir} -t html -q "$@" 2>&1)
status=$?

# Check the exit status
if [ $status -ne 0 ]; then
    echo "b2code-sphinx-build failed with exit code $status"
    exit $status
elif echo "$output" | grep "WARNING"; then
    exit 1
else
    exit 0
fi
