#!/bin/bash

which doxygen &> /dev/null
if [ $? -ne 0 ]; then
    echo "doxygen executable not found. Doxygen must be installed for this script to work"
    exit 1;
fi

# check for help argument
echo $@ | grep -E -- "(^|\\s)(--help|-h)($|\\s)" &>/dev/null
if [ $? -eq 0 ]; then
    cat <<EOT
This script will try to show all doxygen warnings about undocumented items
similar to the development build. To run it on single files or directories just
supply them as arguments:
    $0 [<directory>...] [<filename>...]

To run on the full release directory run it without any arguments:
    $0
EOT
    exit 1;
fi

# collect arguments or use belle2 release directory
FILES=${@:-$BELLE2_LOCAL_DIR}
# create temp dir for output
tmpdir=`mktemp -d`
# remove temporary directory on exit
trap "rm -rf $tmpdir" EXIT
# create script to convert #: comments to doxygen ## on the fly
cat <<EOT > $tmpdir/doxygen_filter.sh
#!/bin/sh
sed -e 's/#: /## /' \$1
EOT
chmod +x $tmpdir/doxygen_filter.sh
# call doxygen on the files from the command line arguments
cat <<EOT | doxygen - 2>&1 >/dev/null | grep "is not documented" && exit 1 || exit 0
OUTPUT_DIRECTORY=$tmpdir
INPUT_FILTER=$tmpdir/doxygen_filter.sh
HAVE_DOT=NO
INPUT=$FILES
RECURSIVE=YES
EOT
