#!/bin/bash

# This command set up location of tutorial files depending on the server where code is running.
# So far only kekcc is supported.

case $HOSTNAME in
  (*cc.kek.jp) export BELLE2_EXAMPLES_DATA='/sw/belle2/examples-data'; 
               echo '$BELLE2_EXAMPLES_DATA is set to '$BELLE2_EXAMPLES_DATA;;
  (*)   printf "You are trying to setup location of tutorial files on the server that did not have DESY cloud configured by the time of release.
Please contact your system administrator to mount DESY cloud somewhere at your server and set up environemnt variable
$BELLE2_EXAMPLES_DATA pointing to examples-data directory from DESY cloud.
";;
esac
