#!/bin/bash
OLD=merge_basf2_files
NEW=b2file-merge
echo -e "\033[0;31mAttention:\033[0m ${OLD} has been renamed to ${NEW}.

Some time ago the software group has decided that we should enforce a more
systematic naming convention for command line tools. The old names have been
kept for compatibility but will now be removed. The tool you tried to call is
one of those which has been renamed.

From now on please use \033[0;32m${NEW}\033[0m

\033[0;31mAttention:\033[0m ${OLD} has been renamed to ${NEW}."
exit 1
