#!/bin/sh

# install optional python packages which are required to 
# use ipython notebooks productively

pip3 install jupyter scipy matplotlib pandas widgetsnbextension javascript
jupyter nbextension enable --py --sys-prefix widgetsnbextension
