Import('env')

env['TOOLS_LIBS']['basf2'] = ['framework_pybasf2', 'framework',
                              'boost_filesystem', 'boost_program_options', 'boost_python', 'boost_system',
                              '$PYTHON_LIBS']

env['TOOLS_LIBS']['showmetadata'] = ['$XML_LIBS', 'framework', 'boost_program_options', '$ROOT_LIBS']

env['TOOLS_LIBS']['addmetadata'] = ['$XML_LIBS', 'framework', 'boost_program_options', '$ROOT_LIBS']

env['TOOLS_LIBS']['addtocatalog'] = ['$XML_LIBS', 'framework', 'boost_program_options', '$ROOT_LIBS']
env['TOOLS_LIBS']['merge_basf2_files'] = ['framework', 'boost_program_options', '$ROOT_LIBS']

Return('env')
