Import('env')
#env['TOOLS_LIBS']['TRGCDCConfig'] = ['trg', 'framework', 'cdc']
env['TOOLS_LIBS']['TRGCDCConfig'] = ['trg', 'dataobjects']
env['TOOLS_LIBS']['TRGCDCInterfaceBuilder'] = ['trg', 'dataobjects']
env['TOOLS_LIBS']['TRGCDCFrontEndImplementation'] = ['trg', 'dataobjects']
env['TOOLS_LIBS']['TRGCDCTRGPackerTB'] = ['trg', 'dataobjects']
env['TOOLS_LIBS']['TRGCDCTSStreamReader'] = ['Core', 'trg', 'framework', 'dataobjects']
env['TOOLS_LIBS']['TRGCDCDisplay'] = ['trg', 'framework', 'dataobjects']

#env['TOOLS_LIBS']['TRGCDCTSStreamReader'].insert(0, ['gtkmm-2.4', 'gdkmm-2.4', 'glibmm-2.4', 'Core'])
#env['TOOLS_LIBS']['TRGCDCDisplay'].insert(0, ['gtkmm-2.4', 'gdkmm-2.4', 'glibmm-2.4', 'Core'])

Return('env')
