#define TRG_SHORT_NAMES

#include <iostream>
#include <fstream>
#include <cmath>
#include <cstdio>
#include <vector>
#include <math.h>
#include <iomanip>
#include "trg/trg/Utilities.h"

using namespace std;
using namespace Belle2;

#define NAME          "HoughMapping"
#define VERSION       "version 0.00"

struct XY {double x ; double y ;};
struct Plane { unsigned x;  unsigned y ;};
void superLayer(const unsigned id);

//...C++ for TSIM...
const string fnc = "HoughMapping.cc";
ofstream outc(fnc);

int
main(int, char **) {

    cout << NAME << " ... " << VERSION << endl;
    const string tab = "    ";

    //...Date...
    string ts = TRGUtil::dateString();

    outc << "// This file is generated by " << NAME << "(" << VERSION << ")"
         << endl;
    outc << "// " << ts << endl << endl;
    outc << "#define TRGCDC_SHORT_NAMES" << endl;
    outc << "#include \"trg/trg/State.h\"" << endl;
    outc << "#include \"trg/cdc/Tracker2D.h\"" << endl;
    outc << "using namespace std;" << endl;
    outc << "using namespace Belle2;" << endl;
    outc << "void" << endl;
    outc << "TCTracker2D::HoughMapping(void) {" << endl;

    outc << "    //...TS hit map..." << endl;
    outc << "    TRGState SL0_TS = _ts.subset(0, 160);" << endl;
    outc << "    TRGState SL2_TS = _ts.subset(160, 192);" << endl;
    outc << "    TRGState SL4_TS = _ts.subset(160 + 192, 256);" << endl;
    outc << "    TRGState SL6_TS = _ts.subset(160 + 192 + 256, 320);" << endl;
    outc << "    TRGState SL8_TS = _ts.subset(160 + 192 + 256 + 320, 384);"
         << endl;

    outc << "    //...Hough cells..." << endl;
    for (unsigned i = 0; i < 5; i++)
        for (unsigned j = 1; j < 17; j++)
            outc << "    TRGState SL" << to_string(i * 2) << "_row"
                 << to_string(j) << "(160);" << endl;

    for (unsigned sl = 0; sl < 5; sl++)
        superLayer(sl);

    outc << endl << "}" << endl;

    outc.close();

    //...Termination...
    cout << "Files generated" << endl;
    cout << "    c++ for tsim firmware : " << fnc << endl;
//  cout << "    text file for axial super layer : " << 
}

void
superLayer(const unsigned id) {
    double tmp = 0;
    int tmpi = 0;
    int tmpj = 0;

    if (id == 0) {
        tmp = 18.8;
        tmpi = 160;
        tmpj = 0;
    }
    else if (id == 1) {
        tmp = 40.16;
        tmpi = 192;
        tmpj = 2;
    }
    else if (id == 2) {
        tmp = 62.0;
        tmpi = 256;
        tmpj = 4;
    }
    else if (id == 3) {
        tmp = 83.84;
        tmpi = 320;
        tmpj = 6;
    }
    else if (id == 4) {
        tmp = 105.68;
        tmpi = 384;
        tmpj = 8;
    }
    else {
        cout << NAME << " !!! bad super layer ID" << endl;
        exit(-1);
    }

    //Hough Plane Parameter
    //Theta Range (X Axial)
    const double PI2=2*M_PI;
    //log10(r) Range (Y Axial)
    //cm
    const float minY=1.823908740944321;
    const float maxY=3.204119982655926;
    const int SL = tmpj;
    //other const
    const unsigned nX=160;
    const unsigned nY=16;
    //const unsigned oder=1000;

    //Radious of SL_center cell
    const double r_SL0 = tmp;
    // const double r_SL0=18.8;
    // const double r_SL0=40.16;
    // const double r_SL0=62.0;
    // const double r_SL0=83.84;
    // const double r_SL0=105.68;

    //Number of TS each SL
    const int N_TS_SL0 = tmpi;
    // const int N_TS_SL0=160;
    // const int N_TS_SL0=192;
    // const int N_TS_SL0=256;
    // const int N_TS_SL0=320;
    // const int N_TS_SL0=384;


    //Hough Plane database SL-0
    vector <XY> xymatrix;
    XY xy={0,0};

/////////////////////////////////////////////////base of ts

    for(int i=0 ; i<N_TS_SL0 ; i++) {
        xy.x=r_SL0*cos((PI2/N_TS_SL0)*i);
        xy.y=r_SL0*sin((PI2/N_TS_SL0)*i);
        xymatrix.push_back(xy);
    }
///////////////////////////////////////////////////HP to TS

    const float r0=minY;
    const float theta0=0;
    const float dr=(maxY-minY)/nY;
    const float dtheta=PI2/nX;



    int p=0;
    int u;
    int *ptr;
    int l=0;

    double r1 ;
    double r2 ;
    double rminus ;
    double rplus ;
    double theta1 ;
    double theta2 ;
    double minus1 ;
    double minus2 ;
    double plus1 ;
    double plus2 ;

    const string fn = "SL" + to_string(id * 2) + "_minus_UT3_0.txt";
//  ofstream outputp("SL0_minus_UT3_0.txt",fstream::app);
    ofstream outputp(fn, fstream::app);

    //vertical
    for(int k=0 ; k<16 ; k++) {

        //horizontal
        for(int t=20 ; t<60 ; t++) {
            int  j=t%160;
            p++;
            u=-1;
            ptr=&l;
            //    outputp <<*ptr<<  endl;
            //    outputp <<"XLXI_"<<p<<":"<<" OR"<<*ptr<<  endl;
            //    outputp <<"port map (";
            outputp <<"SL"<<SL<<"_row"<<k+1<<"("<<j<<")<=";
            outc << "    SL" << SL << "_row" << k + 1 << ".set(" << j << ", ";

            bool first = true;

            //     cout <<"HP" << "(" << j << "," << k+1 <<")"<<endl;

//SL8 0.4166
            theta1=theta0+j*dtheta-dtheta*0.0 ;         //minus
            theta2=theta0+(j+1)*dtheta+dtheta*0.0;      //plus

            //     outputp<< j <<" "<< k+1;
            //TS
            for(int i=0 ; i<N_TS_SL0 ; i++) {   //HP_0(0,0) to TS_SL_0  Save Date


                r1=(((xymatrix[i].x)*(xymatrix[i].x))+((xymatrix[i].y)*(xymatrix[i].y)))/((2*xymatrix[i].x*cos(theta1))+(2*xymatrix[i].y*sin(theta1)));
                r2=(((xymatrix[i].x)*(xymatrix[i].x))+((xymatrix[i].y)*(xymatrix[i].y)))/((2*xymatrix[i].x*cos(theta2))+(2*xymatrix[i].y*sin(theta2)));

                rplus=(((xymatrix[i].x)*(xymatrix[i].x))+((xymatrix[i].y)*(xymatrix[i].y)))/(2*xymatrix[i].x*cos(theta1+dtheta/10000)+(2*xymatrix[i].y*sin(theta1+dtheta/10000)));
                rminus=(((xymatrix[i].x)*(xymatrix[i].x))+((xymatrix[i].y)*(xymatrix[i].y)))/(2*xymatrix[i].x*cos(theta2+dtheta/10000)+(2*xymatrix[i].y*sin(theta2+dtheta/10000)));

                if(r1<0) {
                    r1=1;
                }
                if(r2<0) {
                    r2=1;
                }
                if(rminus<0) {
                    rminus=1;
                }
                if(rplus<0) {
                    rplus=1;
                }
                
                minus1=r0+(k+1)*dr+dr*0.0-log10(r1);
                minus2=r0+k*dr-dr*0.0-log10(r2);

                plus1=r0+(k+1)*dr-log10(r2);
                plus2=r0+k*dr-log10(r1);




/*
  outputp << "TS8-" << i+1 << endl;
  outputp << "(x,y)="<<"("<<xymatrix[i].x <<","<< xymatrix[i].y <<")"<<endl;
  outputp << "r0+(k+1)*dr=" << r0+(k+1)*dr << endl;
  outputp << "log r1=" << log10(r1) << endl;
  outputp << "r1=" << r1 << endl;
  outputp << "r0+k*dr=" << r0+k*dr << endl;
  outputp << "log r2=" << log10(r2) << endl;
  outputp << "r2=" << r2 << endl;
  outputp << "minus1=" << minus1 <<endl;
  outputp << "minus2=" << minus2 <<endl;
  outputp << "rminus=" << rminus <<endl;
  outputp << "minus1*minus2=" << minus1*minus2 <<endl;
  outputp << "======================================" << endl;
*/


//minus
////////////////////////////////////////////////////////////////

                if( r1!=1 && r2!=1 ) {
                    if ( r2<=rminus  ) {
                        if(minus1*minus2 <=0.0 ) {
                            u=u+1;

                            if (! first)
                                outc << " or ";

                            if (u!=0) {
// outputp <<setw(11)<<"I"<<u<<"=>SL0_TS("<< i+1  <<"),"<< endl;
// outputp <<SL<<" "<< i <<" "  ;
                                outputp<<"SL"<<SL<<"_TS("<<i<<") or ";
                                outc << "SL" << SL << "_TS[" << i << "]";
                                first = false;
                            }
                            else {
// outputp <<"I"<<l<<"=>TS("<< i+1  <<"),"<< endl;
// outputp <<SL<<" "<< i <<" "  ;
                                outputp<<"SL"<<SL<<"_TS("<<i<<") or ";
                                outc << "SL" << SL << "_TS[" << i << "]";
                                first = false;
                            }
                        }
                        
                    }
                    
                }

//iw            else if(r2=1 && r1!=1) {
                else if (r2 ==1 && r1 != 1) {

                    if( r2<=rminus  ) {
//iw                    if( r2=1 && minus1>0 ) {    u=u+1;
                        if (r2 == 1 && minus1 > 0) {
                            u = u + 1;
                            if (u!=0) {
 //                 outputp <<setw(11)<<"I"<<u<<"=>TS("<< i+1  <<"),"<< endl;
 //                  outputp <<SL<<" "<< i <<" "  ;
                                outputp<<"SL"<<SL<<"_TS("<<i<<") or ";
                                if (! first)
                                    outc << " or ";
                                outc << "SL" << SL << "_TS[" << i << "]";
                                first = false;
                            }
                            else {
 //                  outputp <<"I"<<u<<"=>TS("<< i+1  <<"),"<< endl;
 //                 outputp <<SL<<" "<< i <<" "  ;
                                outputp<<"SL"<<SL<<"_TS("<<i<<") or ";
                                if (! first)
                                    outc << " or ";
                                outc << "SL" << SL << "_TS["<<i<<"]";
                                first = false;
                            }
                        }
                        
                    }
                }

                
//////////////////////////////////////////////////////////////////



//plus
//////////////////////////////////////////////////////////////////
/*
//plus
if( r1!=1 && r2!=1 )
{

if ( r1>=rplus  )
{
if(plus1*plus2 <=0.0 )
{
u=u+1;
if(u!=0)
outputp <<setw(11)<<"I"<<u<<"=>TS("<< i+1  <<"),"<< endl;
else
outputp <<"I"<<l<<"=>TS("<< i+1  <<"),"<< endl;

}

}

}

else if(r1=1 && r2!=1)
{
if( r1>=rplus  )
{
if( r1=1 && plus1>0 )
{    u=u+1;
if(u!=0)
outputp <<setw(11)<<"I"<<u<<"=>TS("<< i+1  <<"),"<< endl;
else
outputp <<"I"<<u<<"=>TS("<< i+1  <<"),"<< endl;

}

}
}

*/
//////////////////////////////////////////////////////////////////

     l=u+1;
//outputp.close();

            }

            // outputp <<"XLXI_"<<p<<":"<<" OR"<<*ptr<<  endl;
            // outputp <<"                                       "<<endl;
            
            outputp<<";"<<endl;

            if (first)
                outc << "false";
            outc << ");" <<endl;

            // outputp<<"SL0_row"<< k+1 << "(" << j+1 <<")<= a("<<p<<");"<<endl;
            
        }
    }

    outputp.close();
    
    return;
}
