Import('env')

env['LIBS'] = ['eklm_dataobjects', 'eklm_dbobjects', 'framework', 'geometry',
               'simulation', 'mdst_dataobjects','simulation_dataobjects',
               'calibration', 'calibration_dataobjects',
               'alignment_dataobjects', 'genfit2',
               '$ROOT_LIBS', 'libMinuit', 'Geom']

Return('env')
