Import('env')

#These are the libraries the awesome package has to be linked against
env['LIBS'] = ['$ROOT_LIBS', 'generators_dataobjects','beast_bgo_dataobjects','beast_microtpc_dataobjects','beast_cave_dataobjects','beast_ph1bpipe_dataobjects','beast_ph1sustr_dataobjects','beast_he3tube_dataobjects']

Return('env')
