#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import basf2
import logging

from trackfindingcdc.run.display import CDCDisplayRun

def main():
    cdc_display_run = CDCDisplayRun()
    cdc_display_run.show_all_drawoptions = True
    file_name_prefix = "event_"
    cdc_display_run.configure_and_execute_from_commandline()

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    main()
