#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import tracking
from trackfindingcdc.cli.displaying import run_cdc_display

def main():
    arguments = dict(show_all_draw_options=True, file_name_prefix="event_")
    run_cdc_display(arguments)

if __name__ == "__main__":
    main()
