#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import os.path
import basf2

from trackfindingcdc.run.recording import RecordingRun

import logging


class CDCClusterRecordingRun(RecordingRun):
    """Run for recording clusters encountered at the filter"""
    n_events = 1000
    bkg_files = os.path.join(os.environ["VO_BELLE2_SW_DIR"], "bkg")
    flight_time_estimation = "outwards"
    root_output_file_name = "ClusterFilter.root"
    varsets = ["basic", "bkg_truth", ]

    recording_filter_parameter_name = "ClusterFilterParameters"

    recording_finder_module = basf2.register_module("SegmentFinderCDCFacetAutomaton")

    recording_finder_module.param({
        "ClusterFilter": "unionrecording",
        recording_filter_parameter_name : {
                "rootFileName": root_output_file_name,
                "varSets": varsets,
        },
        "FacetFilter": "none",
        "FacetRelationFilter": "none",
    })


def main():
    run = CDCClusterRecordingRun()
    run.configure_and_execute_from_commandline()


if __name__ == "__main__":
    logging.basicConfig(stream=sys.stdout, level=logging.INFO, format='%(levelname)s:%(message)s')
    main()
