#!/usr/bin/env python

"""Opens a TBrowser with the given object from commandline"""

import os
import sys
import os.path

import tracking.utilities as utilities

from tracking.validation.utilities import root_browse

import ROOT.TFile

import logging


def main():
    argument_parser = utilities.DefaultHelpArgumentParser()

    argument_parser.add_argument(
        "root_file_path",
        help="ROOT file to be browsed.",
    )

    arguments = argument_parser.parse_args()

    root_file_path = arguments.root_file_path
    tfile = ROOT.TFile(root_file_path, "READ")

    root_browse(tfile)
    raw_input("Close with return key.")


if __name__ == "__main__":
    logging.basicConfig(stream=sys.stdout, level=logging.INFO, format='%(levelname)s:%(message)s')
    main()
