#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import os.path
import basf2

from trackfindingcdc.validation.recording import RecordingRun

import logging


class CDCFacetRelationRecordingRun(RecordingRun):
    """Run for recording facet relations encountered at the filter"""
    n_events = 50
    # bkg_files = os.path.join(os.environ["VO_BELLE2_SW_DIR"], "bkg")

    root_output_file_name = "CDCFacetRelationTruthRecords.root"
    varsets = ["basic", "filter(truth)", ]

    recording_filter_parameter_name = "FacetRelationFilterParameters"

    recording_finder_module = basf2.register_module("SegmentFinderCDCFacetAutomatonDev")

    recording_finder_module.param({
        "FacetRelationFilter": "unionrecording",
        recording_filter_parameter_name : {
            "rootFileName": root_output_file_name,
            "varsets": varsets,
        },
    })


def main():
    """Execute the facet relation recording"""
    run = CDCFacetRelationRecordingRun()
    run.configure_and_execute_from_commandline()


if __name__ == "__main__":
    logging.basicConfig(stream=sys.stdout, level=logging.INFO, format='%(levelname)s:%(message)s')
    main()
