#!/bin/bash

if [ -z "$1" ]; then
	echo "usage: $0 training_root_file";
	echo "   This script creates all weight files for the SegmentTrackCombinerModule from the given root file with events."; 
	exit;
fi

# SegmentTrackFilterFirstStep
if [ ! -e "SegmentTrackFilterFirstStep.root" ]; then
	trackfindingcdc-record-segment-track-first-step -i "$1"
fi
trackfindingcdc-train SegmentTrackFilterFirstStep.root
mv weights/SegmentTrackFilterFirstStep_FastBDT.weights.xml $BELLE2_LOCAL_DIR/tracking/data/
rm -rf weights

# BackgroundSegmentFilter
if [ ! -e "BackgroundSegmentsFilter.root" ]; then
	trackfindingcdc-record-background-segments -i "$1"
fi
trackfindingcdc-train BackgroundSegmentsFilter.root
mv weights/BackgroundSegmentsFilter_FastBDT.weights.xml $BELLE2_LOCAL_DIR/tracking/data/
rm -rf weights

# NewSegmentFilter
if [ ! -e "NewSegmentsFilter.root" ]; then
	trackfindingcdc-record-new-segments -i "$1"
fi
trackfindingcdc-train NewSegmentsFilter.root
mv weights/NewSegments_FastBDT.weights.xml $BELLE2_LOCAL_DIR/tracking/data/
rm -rf weights

# SegmentTrackFilterSecondStep
if [ ! -e "SegmentTrackFilterSecondStep.root" ]; then
	trackfindingcdc-record-segment-track-second-step -i "$1"
fi
trackfindingcdc-train SegmentTrackFilterSecondStep.root
mv weights/SegmentTrackFilterSecondStep_FastBDT.weights.xml $BELLE2_LOCAL_DIR/tracking/data/
rm -rf weights