#!/bin/bash

if [ -z "$1" ]; then
	echo "usage: $0 training_root_file";
	echo "   This script creates all weight files for the SegmentTrackCombinerModule from the given root file with events."; 
	exit;
fi

# BackgroundHitFinder
if [ ! -e "BackgroundHitFinder.root" ]; then
	trackfindingcdc-record-clusters -i $1
fi
trackfindingcdc-train BackgroundHitFinder.root
mv weights/BackgroundHitFinder_FastBDT.weights.xml $BELLE2_LOCAL_DIR/tracking/data/
rm -rf weights
