#!/bin/bash

if [ -z "$1" ]; then
    echo "usage: $0 training_root_file";
    echo "   This script creates the weight file for the BackgroundClusterFilter from the given root file with events as local database objects."
    exit
fi

# BackgroundClusterFilter
if [ ! -e "ClusterFilter.root" ]; then
	trackfindingcdc-record-clusters -i $1
fi
trackfindingcdc_teacher --identifier trackfindingcdc_BackgroundClusterFilter ClusterFilter.root
