Import('env')

env['LIBS'] = [
    'framework', 'vxd', 'vxd_dataobjects', 'pxd', 'pxd_dbobjects', 'pxd_utilities',
    'mdst_dataobjects', 'mdst_dbobjects',
    'tracking_dataobjects', 'calibration', '$ROOT_LIBS'
]

Return('env')
