Import('env')
env['LIBS'] = ['$ROOT_LIBS', 'framework', 'reconstruction_dbobjects', 'rawdata_dataobjects', "mdst_dbobjects","mdst_dataobjects", 'cdc_dataobjects', 'ecl_dataobjects', 'hlt_dbobjects', 'hlt']
Return('env')

