* File inclk.f generated by GRACE Ver. 2.00(37)        1996/05/14/12:00
* 
*          Fortran source code generator
*     (c)copyright 1990-1996 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
* masses and width of particles
      common /ammass/   amw,   amz,   ama,   amg,   amh,   amx,   amy,
     &                 amne,  amnm,  amnt,  amel,  ammu,  amta,  amuq,
     &                 amcq,  amtq,  amdq,  amsq,  ambq,  amcp,  amcm,
     &                 amcz,  amca,  amcg

      common /amgmma/   agw,   agz,   agh,   agx,   agy,  agcq,  agtq,
     &                 agsq,  agbq,  agcp,  agcm,  agcz

      common /amcnst/ pi, pi2, rad, gevpb, alpha, alphas, alpha0
      common /amreg / mxreg
      common /amopts/ jtgamm, jano3v, jcolmb, jqcdcr
      common /amoptc/ colmbf
      common /amoptm/ jqmass
      common /aman3v/ andka, andkz, anlma, anlmz
      common /amoptj/ jdecay, jhadrn

* external particles name
      character*16    kmprtc
      common /kmprt1/ kmprtc(6)
      common /kmprt2/ kmprtl(6)

* QEDPS flags
      common /amoptq/ jqedps

* masses of external particles
      common /kmmass/ amass1(6), amass2(6)

* charge(*3) and KFcode of external particles
      common /kminfo/ kcharg(6), kfcode(6)

* Color string information
      common /kmcsti/ kmcbas, kmcbmx, kmcstr(4,0:1), icinfo(6), icolst
      common /grc4fc/ jcanon
