import os

Import('env')

#Make sure the include files are removed from the list of source files
env['SRC_FILES'] = [srcf for srcf in env['SRC_FILES'] if srcf.find('incl') <= -1]

#Don't create a sublib for this folder
env['SUBLIB'] = False

Return('env')
