Import('env')

env['LIBS'] = [
    #'boost_chrono',
    'framework', 
    'pxd_dataobjects',
    #'svd', 
    'svd_dataobjects',
    'vxd',
    'vxd_dataobjects',
    'testbeam_vxd_dataobjects',
    'genfit2',
    'tracking',
    'testbeam'
    #'tracking_dataobjects',
    ]
Return('env')

