Import('env')

env['TOOLS_LIBS']['rocontrold'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['eb0controld'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['eb1txcontrold'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['eb1rxcontrold'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['eb2txcontrold'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['eb2rxcontrold'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['nodemonitor'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']

Return('env')
