Import('env')
env['LIBS'] = ['$ROOT_LIBS', 'framework', 'reconstruction_dataobjects', 'reconstruction_dbobjects', 'genfit2', 'vxd', 'mdst_dataobjects', 'pxd_dataobjects', 'svd_dataobjects', 'tracking_dataobjects']
Return('env')
