#! /bin/tcsh
ssh hltwk01 "cd hlt/run; setenv NSM2_HOST cevproc01; rf_eventprocessor rfarm.conf > & evp_hltwk01/nsmlog.log" &
ssh hltwk02 "cd hlt/run; setenv NSM2_HOST cevproc02; rf_eventprocessor rfarm.conf > & evp_hltwk02/nsmlog.log" &
ssh hltwk03 "cd hlt/run; setenv NSM2_HOST cevproc03; rf_eventprocessor rfarm.conf > & evp_hltwk03/nsmlog.log" &

ssh hltos "cd hlt/run; setenv NSM2_HOST coutserv; rf_outputserver rfarm.conf > & collector/nsmlog.log " &
ssh hltes "cd hlt/run; setenv NSM2_HOST cevserv; rf_eventserver rfarm.conf > & distributor/nsmlog.log" &
ssh hltes "cd hlt/run; setenv NSM2_HOST cevserv; rf_dqmserver rfarm.conf > & dqmserver/nsmlog.log" &
ssh hltes "cd hlt/run; setenv NSM2_HOST cevserv; rf_master rfarm.conf > & master/nsmlog.log" &

ssh hltos "cd hlt/run; setenv NSM2_HOST coutserv; rf_roisender rfarm.conf > & roisender/nsmlog.log" &
