Import('env')

env['TOOLS_LIBS']['filemond'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['filemonitor'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['filecopy'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['filelist'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['filegzip'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['filedb'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']

Return('env')
