Import('env')
env['SUBLIB'] = True
env['LIBS'] = [
       	      'framework', 
	      'analysis',
	      'analysis_dataobjects', 
	      'tracking_dataobjects',
	      'arich_dataobjects',
              'bklm_dataobjects',
              'cdc_dataobjects',
              'ecl_dataobjects',
              'eklm_dataobjects',
              'mdst_dataobjects',
              'pxd_dataobjects',
              'reconstruction_dataobjects',
              'svd_dataobjects',
              'top_dataobjects',
              'vxd_dataobjects',
	      'genfit2'
	      ]
Return('env')

