Import('env')
env['SUBLIB'] = True
env['LIBS'] = ['framework', 'analysis', 'analysis_utility', 'analysis_dataobjects', 'analysis_DecayDescriptor', 
	       'hlt_L1Emulator_dataobjects']

Return('env')

