Import('env')

env['LIBS'] = [
    'tracking_dataobjects',
    'tracking',
    'mdst_dataobjects',
    'cdc_dataobjects',
    'pxd_dataobjects',
    'svd_dataobjects',
    'framework']

Return('env')

