import os

Import('env')

env['LIBS'] = [
    'framework',
    'boost_regex',
    '$ROOT_LIBS',
    'ca', 'Com'
]

print("HERERERERERERE")
# this check is not completely save if new options are added with clang
if os.environ['BELLE2_OPTION'] in ['clang', 'intel']:
    env.Append(CPPPATH=['$EPICS_BASE/include/compiler/clang'])
else:
    env.Append(CPPPATH=['$EPICS_BASE/include/compiler/gcc'])

env['EPICS_BASE'] = os.environ['EPICS_BASE']
env['EPICS_HOST_ARCH'] = os.environ['EPICS_HOST_ARCH']

env.Append(CPPDEFINES=['_BELLE2_EPICS'])
env.Append(CPPPATH=['$EPICS_BASE/include'])
env.Append(CPPPATH=['$EPICS_BASE/include/os/Linux'])
env.Append(LIBPATH=['$EPICS_BASE/lib/$EPICS_HOST_ARCH'])

Return('env')
