/**************************************************************************
 * BASF2 (Belle Analysis Framework 2)                                     *
 * Copyright(C) 2015 - Belle II Collaboration                             *
 *                                                                        *
 * Author: The Belle II Collaboration                                     *
 * Contributors: Oliver Frost                                             *
 *                                                                        *
 * This software is provided "as is" without any warranty.                *
 **************************************************************************/
#pragma once

#include <tracking/trackFindingCDC/basemodules/TrackFinderCDCBaseModule.h>

#include <tracking/trackFindingCDC/eventdata/segments/CDCRecoSegment2D.h>

namespace Belle2 {
  /// Worker for building reconstructed segments form wirehits using facets.
  class SegmentFinderCDCBaseModule : public virtual TrackFinderCDCBaseModule {
  public:
    /// Constructor of the module overwritting the default desired orientation of the Segments.
    SegmentFinderCDCBaseModule();

    ///  Initialize the Module before event processing.
    void initialize() override;

    /// Processes the event and generates track candidates.
    void event() override;

    /** Implementation specific method that generates segments and
     *  writes them to the output vector not carry about orientation.
     */
    virtual void generateSegments(std::vector<Belle2::TrackFindingCDC::CDCRecoSegment2D>&) {}

  public:
    /** Set the default output orientation of the segments.
     *  * ETrackOrientation::c_None does not modify the orientation from the concret algorithm.
     *  * ETrackOrientation::c_Symmetric makes to copies of each segment with forward and backward to the original orientation.
     *  * ETrackOrientation::c_Outwards flips the orientation of the segment such that they point away from the interaction point.
     *  * ETrackOrientation::c_Downwards flips the orientation of the segment such that they point downwards.
     *
     *  This properties can also be overridden by the user to in a module parameter.
     */
    void setSegmentOrientation(const ETrackOrientation& segmentOrientation)
    { m_segmentOrientation = segmentOrientation; }

    /// Get the currentl default output orientation of the segments.
    const ETrackOrientation& getSegmentOrientation() const
    { return m_segmentOrientation; }

  protected:
    /// Parameter: Name of the output StoreObjPtr of the segments generated by this module.
    std::string m_param_segmentsStoreObjName;

    /** Parameter: String that states the desired segment orientation.
     *  Valid orientations are "none" (as generated), "symmetric", "outwards", "downwards".
     */
    std::string m_param_segmentOrientationString;

    /// Parameter: Switch if the segments shall be fitted after the generation.
    bool m_param_fitSegments;

    /// Parameter: Switch if genfit::TrackCandidates shall be generated for each segment.
    bool  m_param_createGFTrackCands;

    /** Encoded desired segment orientation.
     *  Valid orientations are "c_None" (as generated), "c_Symmetric", "c_Outwards", "c_Downwards.
     */
    ETrackOrientation m_segmentOrientation;
  };
}
