Import('env')

env['LIBS'] = ['cdc_dataobjects',
               'framework',
               'genfit2',
               'tracking',
               'mdst_dataobjects',
               'tracking_trackFindingCDC',
               'framework_pybasf2',
               'simulation_dataobjects',
               '_trackFinderCDC_',
               'framework_pybasf2',
               'simulation_dataobjects',
               'tracking_trackFinderCDC',
]
Return('env')