Import('env')

env['LIBS'] = ['framework', 'rawdata_dataobjects', 'mdst_dataobjects',
               'pxd_dataobjects', 'pxd', 
               'svd_dataobjects', 'svd',
               'cdc_dataobjects',
               'top_dataobjects', 'top', 
               'arich_dataobjects', 'arich',
               'ecl_dataobjects',
               'bklm_dataobjects',
               'eklm_dataobjects', 'eklm_dbobjects',
               '$ROOT_LIBS']

Return('env')