Import('env')

env['LIBS'] = ['framework', 'rawdata_dataobjects', 'mdst_dataobjects',
               'pxd_dataobjects', 'pxd', 
               'svd_dataobjects', 'svd',
               'cdc_dataobjects',
               'top_dataobjects', 'top', 
               'arich_dataobjects', 'arich',
               'ecl_dataobjects', 'ecl', 'ecl_dbobjects', 'calibration', 'Geom',
               'klm_dataobjects', 'klm_dbobjects',
	       'hlt',
	       'tracking_trackFindingCDC',
               '$ROOT_LIBS']

Return('env')
