Import('env')

env['LIBS'] = [
    'framework',
    'geometry',
    'mdst_dataobjects',
    'simulation_dataobjects',
    'rawdata_dataobjects',
    'vxd', 'vxd_dataobjects',
    'pxd', 'pxd_dataobjects',
    'genfit2',
    'tracking', 'tracking_dataobjects',
    ]

Return('env')

