#!/usr/bin/env python3

from glob import glob
import ROOT
import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument('exp', type=str, help='Experiment number in #### format. For example, 0010')
parser.add_argument('run', type=str, help='Run number in ###### format, For example, 000001')
parser.add_argument('--file', default="", type=str, help='DQM file w/ input histograms')
args = parser.parse_args()
if len(args.exp) != 4:
	sys.exit("Error: Experiment number should be in #### format. For example, 0010")
if len(args.run) != 6:
	sys.exit("Error: Run number should be in ###### format. Foe example, 000001")
if args.file == "":
	args.file = "/group/belle2/phase3/dqm/dqmsrv1/e"+args.exp+"/dqmhisto/hltdqm_e"+args.exp+"r"+args.run+".root"

f = ROOT.TFile.Open(args.file,"READ")
if args.exp == "0010":
	histos = ['ECL/cid', 'ECL/cid_Thr5MeV', 'ECL/cid_Thr10MeV', 'ECL/cid_Thr50MeV',
                  'ECL/quality', 'ECL/trigtag1', 'ECL/adc_hits',
                  'ECL/edep',
                  'ECL/time_barrel_Thr50MeV', 'ECL/time_endcaps_Thr50MeV',
                  'ECL/ncev', 'ECL/ncev_Thr10MeV']
                  
elif args.exp > "0010":
	histos = ['ECL/cid_Thr0Mev', 'ECL/cid_Thr5MeV', 'ECL/cid_Thr10MeV', 'ECL/cid_Thr50MeV', 
                  'ECL/quality', 'ECL/quality_other', 'ECL/trigtag1', 'ECL/adc_hits', 
                  'ECL/edep_Thr0MeV', 'ECL/edep_Thr5MeV', 'ECL/edep_Thr7MeV', 
                  'ECL/time_barrel_Thr50MeV', 'ECL/time_endcaps_Thr50MeV',    
                  'ECL/ncev_Thr0MeV', 'ECL/ncev_Thr5MeV', 'ECL/ncev_Thr10MeV', 'ECL/ncev_Thr50MeV',
                  'ECL/wf_cid_psd', 'ECL/wf_cid_logic', 'ECL/wf_cid_rand', 'ECL/wf_cid_dphy', 'ECL/wf_cid_other']
else:
	sys.exit("Error: Sorry, DQM reference script doesn't work for experiment number < 10")
histobjs = [ f.FindObjectAny(h) for h in histos ] 
for hist in histobjs:
	hist.SetDirectory(0)
f.Close()

outputHistFile = ROOT.TFile.Open("ECLDQMREF.root","RECREATE") 
dir = outputHistFile.mkdir("ECL");
dir.cd()
for h, hist in zip(histos,histobjs):
	spl = h.split("/")
	hist.SetName(spl[1])
	hist.Write()
outputHistFile.Close()
  

