Import('env')
env['TOOLS_LIBS']['writetestWF'] = ['framework','ecl','ecl_dataobjects','$ROOT_LIBS'];
env['TOOLS_LIBS']['cut'] = ['$ROOT_LIBS'];
env['TOOLS_LIBS']['matrix_cal'] = ['$ROOT_LIBS'];
env['TOOLS_LIBS']['bit'] = ['$ROOT_LIBS'];
Return('env')
