Import('env')

env['LIBS'] = [
    'framework', 
    'pxd_dataobjects',
    'svd_dataobjects',
    'vxd_dataobjects',
    'testbeam_vxd_dataobjects',
    'genfit2',
    'tracking',
    'testbeam'
    ]
Return('env')

