#!/usr/bin/env bash

#if there is nothing to commit we do nothing.
#This might happen for git commit --amend to reword the commit message
if git diff --cached --quiet
then
    exit 0
fi

#if we can find fixstyle we check the files
if which fixstyle >/dev/null
then
    #To check the files to be commited we need a temporary dir as there might
    #be differences between the file in the index and the file on disk
    tmpdir=`mktemp -d`
    if [ $? -ne 0 ]; then
        echo "Problem creating temp dir, aborting commit."
        exit 2
    fi

    #Find out which files were modified
    files_modified=`git diff --cached --name-only`
    #Place a copy of the versions to be commited in the temp dir
    git checkout-index --prefix=$tmpdir/ -- $files_modified
    #Check all the files in the temp dir and write which ones failed the check
    fail=0
    for file in $files_modified; do
        #Suppressing output since the path would be wrong anyways
        checkstyle "$tmpdir/$file" > /dev/null
        if [ $? -ne 0 ]; then
            echo "checkstyle failed for $file"
            fail=1
        fi
    done
    #At least one fail, abort commit
    if [ $fail -ne 0 ]; then
        echo "Commit aborted, please run 'fixstyle' on the files listed above and 'git add' them to your commit again!"
    fi
    #Clean up the temp dir
    rm -r $tmpdir
    exit $fail
else
    #fixstyle not found, bail out
    echo "Belle II environment not found, please set it up via 'source tools/setup_belle2' first. Aborting commit."
    exit 255
fi
