Import('env')

env['LIBS'] = [
    'framework',
    'mdst_dataobjects',
    'pxd_dataobjects',
    'svd_dataobjects',
    'cdc_dataobjects',
    'vtx_dataobjects',
    'tracking_dataobjects',
    ]
Return('env')
