import os

Import('env')

env['SUBLIB'] = True
env['LIBS'] = ['$ROOT_LIBS', 'mdst_dataobjects', 'framework', 'libeemmgisr', 'libeemmgisrfsr', 'libeemmg5', 'libqcdloop1', 'libpjfry', 'gfortran']

Return('env')
