Import('env')

env['LIBS'] = ['$ROOT_LIBS', 'framework', 'daq_hbasf2', 'boost_program_options',
			   'hlt_softwaretrigger_dataobjects', 'rawdata_dataobjects', 'mdst_dataobjects', 'tracking_dataobjects', 'hlt_dataobjects']

Return('env')
