Import('env')

env['TOOLS_LIBS']['dqmviewd'] = ['pthread', 'dl', '$ROOT_LIBS', 'Geom',
				 '$GEANT4_LIBS', 'CLHEP','$PGSQL_LIBS', 
				 'daq', 'pxd', 'vxd', 'rawdata_dataobjects',
				 'framework', 'nsm2_b2lib', 'nsm2_corelib']

Return('env')
