Import('env')

env['TOOLS_LIBS']['dqmviewd'] = ['pthread', 'dl', '$ROOT_LIBS', 'libNew', 'Geom',
				 '$GEANT4_LIBS', 'CLHEP','$PGSQL_LIBS', 
				 'daq', 'pxd', 'vxd', 'rawdata_dataobjects',
				 'framework', 'nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['dqmmaptest'] = ['$ROOT_LIBS']
env['TOOLS_LIBS']['file2tmap'] = ['$ROOT_LIBS', 'libNew']

env['TOOLS_LIBS']['dqmmaptest'] = ['pthread', 'dl', '$ROOT_LIBS', 'libNew', 'Geom',
				 '$GEANT4_LIBS', 'CLHEP','$PGSQL_LIBS', 
				 'daq', 'pxd', 'vxd', 'rawdata_dataobjects',
				 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'ecl']

Return('env')
