Import('env')

env['LIBS'] = [
    'framework',
    'mdst_dataobjects',
    'genfit2',
    'svd',
    'pxd',
    'cdc_dataobjects',
    'geometry',
    'vxd',
    'pxd_dataobjects',
    'vxd_dataobjects',
    'svd_dataobjects'
    ]

Return('env')

