Import('env')
# This file specifies the dependencies of your Analyis code to parts of the
# Belle 2 Software. It should be fine for most analysis but if you need to link
# against additional libraries pleas put them here.
env['LIBS'] = [
    'masterclass_dataobjects',
    'mdst_dataobjects',
    'framework',
    '$ROOT_LIBS',
]
Return('env')
