# -*- coding: utf-8 -*-
# vim: syntax=python

Import('env')

env['LIBS'] = [
    'tracking_dataobjects', 
    'pxd_dataobjects',
    'svd', 'svd_dataobjects',
    'vxd', 'vxd_dataobjects', 
    'cdc', 'cdc_dataobjects',
    'simulation_dataobjects',
    'geometry',
    'mdst_dataobjects',
    'framework',
    'genfit2',
    'EG',
    '$ROOT_LIBS',
    ]

Return('env')

