Import('env')

env['LIBS'] = [
    'alignment',
    'tracking_dataobjects',
    'tracking_trackFindingCDC',
    'pxd', 'pxd_dataobjects',
    'svd', 'svd_dataobjects',
    'vxd', 'vxd_dataobjects',
    'cdc', 'cdc_dataobjects',
    'klm_dataobjects',
    'mdst_dataobjects',
    'mva_dataobjects',
    'mva',
    'framework',
    'genfit2',
    'EG',
    '$ROOT_LIBS',
    'FastBDT_shared',
    'analysis', 'analysis_dataobjects', 'analysis_VertexFitting'
    ]

Return('env')
