Import('env')

env['LIBS'] = [
    'framework',
    'mdst_dataobjects',
    'generators_dataobjects',
    'cdc', 'cdc_dataobjects',
    'genfit2',
    'tracking', #'tracking_dataobjects',
    ]

Return('env')

