Import('env')

# env['LIBS'] = ['framework','rawdata' ,'trg', 'trg_gdl_dataobjects','rawdata_dataobjects']
env['LIBS'] = ['framework', 'mdst_dataobjects', 'trg', 'trg_gdl_dataobjects', 'mdst_dbobjects']

Return('env')
