Import('env')

env['CONTINUE'] = False

env['LIBS'] = ['daq', 'dqm', '$ROOT_LIBS', 'Geom',
               'G4root', '$GEANT4_LIBS', 'CLHEP',
               'boost_python', 'boost_filesystem',
               '$PYTHON_LIBS', '$XML_LIBS']

Return('env')
