Import('env')

# Mark this folder a sub-library
env.Dictionary()['SUBLIB'] = True

env['LIBS'] = ['tracking_dataobjects',
               'ecl',
               'framework',
               'genfit2',
               'ir',
               'klm', 'klm_dataobjects', 'klm_dbobjects',
               'mdst_dataobjects',
               'simulation',
               'structure_dbobjects',
               'CLHEP',
               '$GEANT4_LIBS',
               '$ROOT_LIBS',
              ]

Return('env')