#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclasses;

#pragma link C++ class Belle2::ARICHAerogelInfo+;
#pragma link C++ class Belle2::ARICHAerogelMap+;
#pragma link C++ class Belle2::ARICHAsicChannelMask+;
#pragma link C++ class Belle2::ARICHAsicInfo+;
#pragma link C++ class Belle2::ARICHBadChannels+;
#pragma link C++ class Belle2::ARICHB2LinkInfo+;
#pragma link C++ class Belle2::ARICHCableInfo+;
#pragma link C++ class Belle2::ARICHComponentTest+;
#pragma link C++ class Belle2::ARICHFEBoardInfo+;
#pragma link C++ class Belle2::ARICHFebTest+;
#pragma link C++ class Belle2::ARICHFirmware+;
#pragma link C++ class Belle2::ARICHHapdChipInfo+;
#pragma link C++ class Belle2::ARICHHapdInfo+;
#pragma link C++ class Belle2::ARICHHapdMask+;
#pragma link C++ class Belle2::ARICHHapdQA+;
#pragma link C++ class Belle2::ARICHHapdQE+;
#pragma link C++ class Belle2::ARICHHighVoltageConfig+;
#pragma link C++ class Belle2::ARICHMergerInfo+;
#pragma link C++ class Belle2::ARICHMergerMap+;
#pragma link C++ class Belle2::ARICHMirrorInfo+;
#pragma link C++ class Belle2::ARICHMirrorMap+;
#pragma link C++ class Belle2::ARICHSensorModuleInfo+;
#pragma link C++ class Belle2::ARICHSensorModuleMap+;
#pragma link C++ class Belle2::ARICHGeoBase+;
#pragma link C++ class Belle2::ARICHGeoMasterVolume+;
#pragma link C++ class Belle2::ARICHGeoAerogelPlane+;
#pragma link C++ class Belle2::ARICHGeoDetectorPlane+;
#pragma link C++ class Belle2::ARICHGeoHAPD+;
#pragma link C++ class Belle2::ARICHGeoSupport+;
#pragma link C++ class Belle2::ARICHGeoMirrors+;
#pragma link C++ class Belle2::ARICHGeometryConfig+;
#pragma link C++ class Belle2::ARICHModulesInfo+;
#pragma link C++ class Belle2::ARICHChannelMapping+;
#pragma link C++ class Belle2::ARICHMergerMapping+;
#pragma link C++ class Belle2::ARICHCopperMapping+;
#pragma link C++ class Belle2::ARICHSimulationPar+;
#pragma link C++ class Belle2::ARICHReconstructionPar+;
#pragma link C++ class Belle2::ARICHChannelMask+;
#pragma link C++ class Belle2::ARICHModuleTest+;
#pragma link C++ class Belle2::ARICHMagnetTest+;
#pragma link C++ class Belle2::ARICHBiasCablesMapping+;
#pragma link C++ class Belle2::ARICHBiasChannelsMapping+;
#pragma link C++ class Belle2::ARICHBiasVoltages+;
#pragma link C++ class Belle2::ARICHBiasCrateCableMapping+;
#pragma link C++ class Belle2::ARICHHvChannelsMapping+;
#pragma link C++ class Belle2::ARICHHvCablesMapping+;
#pragma link C++ class Belle2::ARICHHvCrateCableMapping+;
#pragma link C++ class Belle2::ARICHAeroTilesInfo+;
#endif
