Import('env')

env['LIBS'] = ['framework', 'rawdata_dataobjects', 'eklm', 'eklm_dataobjects',
               'eklm_dbobjects', 'klm_dataobjects', 'klm_dbobjects',
               '$ROOT_LIBS']

Return('env')
