Import('env')

env['LIBS'] = ['klm',
               'klm_dataobjects',
               'framework', 
               'rawdata_dataobjects',
               '$ROOT_LIBS',
               'mdst_dataobjects']

Return('env')
