Import('env')

env['LIBS'] = [
    'framework',
    'pxd_dataobjects',
    'svd_dataobjects',
    'cdc_dataobjects',
    'klm_bklm_dataobjects',
    'klm_eklm_dataobjects',
    'mdst_dataobjects',
    'vxd_dataobjects', 'vxd',
    'genfit2',
    '$ROOT_LIBS',
    'EG',
    ]
Return('env')

