Import('env')

env['TOOLS_LIBS']['runcontrold'] = ['pthread', '$MYSQL_LIBS' , '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['runmasterd'] = ['pthread', 'ncurses','readline','$MYSQL_LIBS' , '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['runnsm'] = ['pthread', 'ncurses','readline','$MYSQL_LIBS' , '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']

Return('env')
