Import('env')

env['LIBS'] = ['framework',
               'vxd_dataobjects',
               'pxd_dataobjects',
               'svd_dataobjects',
               'cdc_dataobjects',
               'top_dataobjects',
               'arich_dataobjects',
               'ecl_dataobjects',
               'bklm_dataobjects',
               'eklm_dataobjects',
	       'simulation_dataobjects',
               '$ROOT_LIBS']

Return('env')
