* File incl1.f generated by GRACE Ver. 2.00(37)        1996/05/14/12:00
* 
*          Fortran source code generator
*     (c)copyright 1990-1996 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
      parameter (loutgo =  2, lincom =  1)
      parameter (lantip = -1, lprtcl =  1)
      parameter (lscalr =  1)
      parameter (lepexa =  2, lepexw =  3, lepexz =  3, lepexg =  2)
      parameter (lepina =  4, lepinw =  4, lepinz =  4, leping =  3)
      parameter (lextrn =  2, lintrn =  4)

* table of amplitudes
      parameter (ngraph =144)
      parameter (nextn  =6)

* number of color base
      parameter (ncbase =2)

* number of all helicity states
      parameter (lag    =64)
      parameter (ngrpsq = ngraph*ngraph)
      common /amslct/jselg(ngraph), jgraph, jhiggs,jgluon

      common /amgrph/ agcwrk(0:lag-1),agc(0:lag-1,0:ncbase-1),
     &              aprop,ancp(ngraph),ansp(0:ngraph)
     &             ,cfmtx(0:ncbase-1,0:ncbase-1)
      common /amgrpi/igraph(ngraph)
      DOUBLE COMPLEX agc, agcwrk, aprop
      common /amcplc/     cqed,     cqcd,     czww,     caww,     cggg,
     &                   cwwaa,    cwwza,    cwwzz,    cwwww,    cgggg,
     &                    cwhm,     cwhp,     cwym,     cwyp,     czpm,
     &                    capm,     czhy,     chww,     chzz,     cwzm,
     &                    cwam,     cwzp,     cwap,    cwwhh,    czzhh,
     &                   cwzhm,    cwzhp,    cwahm,    cwahp,    cwwyy,
     &                   czzyy,    cwzym,    cwzyp,    cwaym,    cwayp,
     &                   cwwpm,    czzpm,    caapm,    czapm,     chyy,
     &                    chhh,    chhhh,    cyyyy,    cpmyy,    chhpm,
     &                   chhyy,    cpmpm,     cwne,     cwnm,     cwnt,
     &                    cwel,     cwmu,     cwta,     cwuq,     cwcq,
     &                    cwtq,     cwdq,     cwsq,     cwbq,     cael,
     &                    camu,     cata,     cauq,     cacq,     catq,
     &                    cadq,     casq,     cabq,     czne,     cznm,
     &                    cznt,     czel,     czmu,     czta,     czuq,
     &                    czcq,     cztq,     czdq,     czsq,     czbq
      common /amcplc/     cguq,     cgdq,     cgcq,     cgsq,     cgbq,
     &                    cgtq,     cmmu,     cmta,     cpmu,     cpta,
     &                    cmuq,     cmcq,     cmtq,     cpdq,     cpsq,
     &                    cpbq,     chmu,     chta,     chuq,     chcq,
     &                    chtq,     chdq,     chsq,     chbq,     cymu,
     &                    cyta,     cyuq,     cycq,     cytq,     cydq,
     &                    cysq,     cybq,    cwczp,    cwcmz,    cwcap,
     &                   cwcma,    cwczm,    cwcpz,    cwcam,    cwcpa,
     &                   czcmm,    czcpp,    cacmm,    cacpp,    cgcgg,
     &                   cpczp,    cpcap,    cpcmz,    cmczm,    cmcam,
     &                   cmcpz,    cycmm,    cycpp,    chcmm,    chcpp,
     &                   chczz

      DOUBLE COMPLEX      cqed,     cqcd,     czww,     caww,     cggg,
     &                   cwwaa,    cwwza,    cwwzz,    cwwww,    cgggg,
     &                    cwhm,     cwhp,     cwym,     cwyp,     czpm,
     &                    capm,     czhy,     chww,     chzz,     cwzm,
     &                    cwam,     cwzp,     cwap,    cwwhh,    czzhh,
     &                   cwzhm,    cwzhp,    cwahm,    cwahp,    cwwyy,
     &                   czzyy,    cwzym,    cwzyp,    cwaym,    cwayp,
     &                   cwwpm,    czzpm,    caapm,    czapm,     chyy,
     &                    chhh,    chhhh,    cyyyy,    cpmyy,    chhpm,
     &                   chhyy,    cpmpm,  cwne(2),  cwnm(2),  cwnt(2),
     &                 cwel(2),  cwmu(2),  cwta(2),  cwuq(2),  cwcq(2),
     &                 cwtq(2),  cwdq(2),  cwsq(2),  cwbq(2),  cael(2),
     &                 camu(2),  cata(2),  cauq(2),  cacq(2),  catq(2),
     &                 cadq(2),  casq(2),  cabq(2),  czne(2),  cznm(2),
     &                 cznt(2),  czel(2),  czmu(2),  czta(2),  czuq(2),
     &                 czcq(2),  cztq(2),  czdq(2),  czsq(2),  czbq(2)
      DOUBLE COMPLEX   cguq(2),  cgdq(2),  cgcq(2),  cgsq(2),  cgbq(2),
     &                 cgtq(2),  cmmu(2),  cmta(2),  cpmu(2),  cpta(2),
     &                 cmuq(2),  cmcq(2),  cmtq(2),  cpdq(2),  cpsq(2),
     &                 cpbq(2),  chmu(2),  chta(2),  chuq(2),  chcq(2),
     &                 chtq(2),  chdq(2),  chsq(2),  chbq(2),  cymu(2),
     &                 cyta(2),  cyuq(2),  cycq(2),  cytq(2),  cydq(2),
     &                 cysq(2),  cybq(2),    cwczp,    cwcmz,    cwcap,
     &                   cwcma,    cwczm,    cwcpz,    cwcam,    cwcpa,
     &                   czcmm,    czcpp,    cacmm,    cacpp,    cgcgg,
     &                   cpczp,    cpcap,    cpcmz,    cmczm,    cmcam,
     &                   cmcpz,    cycmm,    cycpp,    chcmm,    chcpp,
     &                   chczz


* Momenta of external particles
      common /amextr/pe1(4),pe2(4),pe3(4),pe4(4),pe5(4),pe6(4),
     &               prod(nextn, nextn)

      common /smextp/ps1,ew1,ce1,ps2,ew2,ce2,ps3,ew3,ce3,ps4,ew4,ce4,
     &               ps5,ew5,ce5,ps6,ew6,ce6

      DOUBLE PRECISION     ps1(4,2), ew1(1)
      DOUBLE COMPLEX ce1(2,2)
      DOUBLE PRECISION     ps2(4,2), ew2(1)
      DOUBLE COMPLEX ce2(2,2)
      DOUBLE PRECISION     ps3(4,2), ew3(1)
      DOUBLE COMPLEX ce3(2,2)
      DOUBLE PRECISION     ps4(4,2), ew4(1)
      DOUBLE COMPLEX ce4(2,2)
      DOUBLE PRECISION     ps5(4,2), ew5(1)
      DOUBLE COMPLEX ce5(2,2)
      DOUBLE PRECISION     ps6(4,2), ew6(1)
      DOUBLE COMPLEX ce6(2,2)

* Switch of gauge parameters
      common /smgaus/igau00,igauab,igauwb,igauzb,igaugl
      common /smgaug/agauge(0:4)

* Normalization
      common /smdbgg/fknorm,fkcall,nkcall

* Calculated table of amplitudes
      common /smatbl/av, lt, indexg
      DOUBLE COMPLEX av(0:lag-1)
      integer    lt(0:nextn), indexg(nextn)

* Spin average
      common /amspin/aspin, jhs(nextn), jhe(nextn), jcpol(nextn)

