Import('env')
env['LIBS'] = [
    'framework',
    'mdst_dataobjects',
    'generators_dataobjects',
    'geometry',
    'pxd', 'pxd_dataobjects',
    'svd', 'svd_dataobjects',
    'vxd', 'vxd_dataobjects',
    'cdc','cdc_dataobjects',
    'genfit2',
    'tracking',
    ]
Return('env')

