Import('env')
env['LIBS'] = [ 'framework','tracking','generators_dataobjects', 'geometry', 'vxd','vxd_dataobjects', 'pxd', 'pxd_dataobjects', 'svd', 'svd_dataobjects','cdc','cdc_dataobjects', 'genfit', 'RKTrackRep']
Return('env')

