Import('env')

env['LIBS'] = ['framework', 'calibration', 
               'klm', 'klm_dataobjects', 'klm_dbobjects',
               'tracking_dataobjects', 'analysis_dataobjects',
               '$ROOT_LIBS', 'CLHEP']

Return('env')
