Import('env')

env['LIBS'] = ['framework', 'klm', 'calibration', 
               'klm_dataobjects', 'klm_bklm_dataobjects', 'klm_eklm_dataobjects', 'calibration_dataobjects', 'tracking_dataobjects',
               'klm_eklm_dbobjects', 'klm_bklm_dbobjects',
               '$ROOT_LIBS', 'CLHEP']

Return('env')
