Import('env')

env['LIBS'] = ['framework', 'klm', 
               'klm_bklm_dataobjects', 'klm_bklm_dbobjects',
               'klm_eklm_dataobjects', 'klm_eklm_dbobjects',
               '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP']

Return('env')
