

var_set = [
    "x_pos_0",
    "y_pos_0",
    "z_pos_0",
    "layer_0",
    "size_0",
    "sizeU_0",
    "sizeV_0",
    "seedCharge_0",
    "clusterCharge_0",
    "x_pos_1",
    "y_pos_1",
    "z_pos_1",
    "layer_1",
    "size_1",
    "sizeU_1",
    "sizeV_1",
    "seedCharge_1",
    "clusterCharge_1",
    "x_pos_2",
    "y_pos_2",
    "z_pos_2",
    "layer_2",
    "size_2",
    "sizeU_2",
    "sizeV_2",
    "seedCharge_2",
    "clusterCharge_2",
    "x_pos_3",
    "y_pos_3",
    "z_pos_3",
    "layer_3",
    "size_3",
    "sizeU_3",
    "sizeV_3",
    "seedCharge_3",
    "clusterCharge_3",
    "seed_pT",
    "seed_tanLambda",
    "first_vtx_layer",
    "last_vtx_layer",
    # "isSignal",
]
