Import('env')

env['LIBS'] = [
    'framework', 'vxd', 'vxd_dataobjects', 'pxd', 'pxd_dataobjects', 'pxd_dbobjects',
    'mdst_dataobjects', 'tracking_dataobjects', 'calibration', '$ROOT_LIBS'
]

Return('env')
