#ifdef CDCLOCALTRACKING_COMPILE_DEBUG
// Setup for debug during structural changes to the algorithm
#define CDCLOCALTRACKING_USE_MC_FILTERS_FIRST_STAGE
#define CDCLOCALTRACKING_USE_MC_FILTERS_SECOND_STAGE
#define CDCLOCALTRACKING_USE_MC_INFORMATION
#define CDCLOCALTRACKING_USE_ROOT
#endif


#ifdef CDCLOCALTRACKING_COMPILE_OPT
// Setup for profiling the real algorithm
#define CDCLOCALTRACKING_USE_SIMPLE_FILTERS_FIRST_STAGE
#define CDCLOCALTRACKING_USE_SIMPLE_FILTERS_SECOND_STAGE
#define CDCLOCALTRACKING_USE_CALLGRIND
#endif

#ifdef CDCLOCALTRACKING_COMPILE_CLANG
// Setup for investigating filter efficiency
//#define CDCLOCALTRACKING_USE_EVALUATE_FILTERS_FIRST_STAGE
//#define CDCLOCALTRACKING_USE_EVALUATE_FILTERS_SECOND_STAGE
#define CDCLOCALTRACKING_USE_SIMPLE_FILTERS_FIRST_STAGE
#define CDCLOCALTRACKING_USE_SIMPLE_FILTERS_SECOND_STAGE
#define CDCLOCALTRACKING_USE_MC_INFORMATION
#define CDCLOCALTRACKING_USE_ROOT
#endif



// Ensure that the Monte Carlo information is retrievable when needed
#if defined CDCLOCALTRACKING_USE_MC_FILTERS_FIRST_STAGE || \
  defined CDCLOCALTRACKING_USE_EVALUATE_FILTERS_FIRST_STAGE  || \
  defined CDCLOCALTRACKING_USE_MC_FILTERS_SECOND_STAGE || \
  defined CDCLOCALTRACKING_USE_EVALUATE_FILTERS_SECOND_STAGE

#ifndef CDCLOCALTRACKING_USE_MC_INFORMATION
#define CDCLOCALTRACKING_USE_MC_INFORMATION
#endif

#endif




