Import('env')

env['LIBS'] = [
    'genfit2',
    'framework',
    'tracking_dataobjects',
    'mdst_dataobjects',
    'vxd',	
    'svd',	
    'svd_dataobjects',
    'vxd_dataobjects',
    'pxd_dataobjects',
    'cdc_dataobjects',
    'svd_dbobjects',
    'hlt',
    ]
Return('env')
