Import('env')

import os

# Mark this folder as a sub library
env.Dictionary()['SUBLIB'] = True

# Additional libraries
env['LIBS'] = [
    'tracking',
    'tracking_dataobjects',
    'geometry',
    'cdc', 'cdc_dataobjects',
    "mva", 'mva_dataobjects',
    # the following four libs are not required by the CDC tracking 
    # but still generated as symbols for unknown reason.
    # Therefore adding them here to keep the dependency checker happy
    'bklm_dataobjects',
    'eklm_dataobjects',
    'pxd_dataobjects',
    'svd_dataobjects',
    'mdst_dataobjects',
    'framework',
    'genfit2',
    '$ROOT_LIBS',
    ]

# Does not work well with cppcheck
# option = os.environ['BELLE2_OPTION']
# if option == "clang":
#     env.Append(CCFLAGS=['-Wdocumentation'])

Return('env')
