Import('env')

import os

# Mark this folder as a sub library
env.Dictionary()['SUBLIB'] = True

# Additional libraries
env['LIBS'] = [
    # This should be removed once the CDCLegendreNiceDrawing is gone,
    # since it is the only thing the links currently links to tracking.

    'geometry',
    #'pxd', 'pxd_dataobjects',
    #'svd', 'svd_dataobjects',
    #'vxd', 'vxd_dataobjects',
    'cdc', 'cdc_dataobjects',
    'mdst_dataobjects',
    'simulation_dataobjects',
    'framework',
    'genfit2',
    '$ROOT_LIBS',
    'TMVA',
    ]

Return('env')
