Import('env')

import os

# Mark this folder as a sub library
env.Dictionary()['SUBLIB'] = True

# Additional libraries
env['LIBS'] = [
    'tracking',
    'tracking_dataobjects',
    'tracking_trackingUtilities',
    'simulation_dataobjects',
    'geometry',
    'cdc', 'cdc_dataobjects', 'cdc_dbobjects',
    "mva", 'mva_dataobjects',
    'mdst_dataobjects',
    'framework',
    'genfit2',
    '$ROOT_LIBS',
    ]

# Does not work well with cppcheck
# option = os.environ['BELLE2_OPTION']
# if option == "clang":
#     env.Append(CCFLAGS=['-Wdocumentation'])

Return('env')
