Import('env')

env['TOOLS_LIBS']['hserver'] = ['daq', 'framework', 'libNew', '$ROOT_LIBS' ]
env['TOOLS_LIBS']['hrelay'] = ['daq', 'framework', 'libNew', '$ROOT_LIBS' ]
env['TOOLS_LIBS']['maptest'] = ['daq', 'framework', 'libNew', '$ROOT_LIBS' ]

Return('env')
