Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation','ecl_dataobjects','vxd_dataobjects', 
               'simulation_dataobjects', 'generators_dataobjects',
               '$ROOT_LIBS', 'Geom']

Return('env')
