Import('env')

env['LIBS'] = ['klm', 'framework', 'klm_eklm_dataobjects',
               'calibration', 'calibration_dataobjects', 'tracking_dataobjects',
               'mdst_dataobjects', '$ROOT_LIBS']

Return('env')

