Import('env')

env['LIBS'] = [
    'framework',
    'mdst_dataobjects',
    'pxd',
    'svd',
    'cdc_dataobjects',
    'genfit2',
    'tracking_dataobjects',
    'ecl_dataobjects'
    ]

Return('env')
