Import('env')

env['SUBLIB'] = True

env['LIBS'] = ['framework', 'geometry', 'simulation', '$ROOT_LIBS',
               'simulation_dataobjects', 'beast_claws_dataobjects', 'beast_claws']

Return('env')
