Import('env')
env['LIBS'] = ['$ROOT_LIBS', 'TMVA', 'framework', 'reconstruction_dataobjects',
               'genfit2', 'tracking_dataobjects', 'mdst_dataobjects','cdc_dataobjects','pxd_dataobjects','svd_dataobjects','vxd_dataobjects']
Return('env')
