Import('env')

env['LIBS'] = ['framework', 'generators_dataobjects', 'vxd', 'pxd', 'svd', 'vxd_dataobjects', 'pxd_dataobjects', 'svd_dataobjects', 'tracking_dataobjects', 'genfit2', 'tracking', 'geometry', 'boost_chrono']
Return('env')
# ', 'tracking_sharedClasses'
