/**************************************************************************
 * basf2 (Belle II Analysis Software Framework)                           *
 * Author: The Belle II Collaboration                                     *
 *                                                                        *
 * See git log for contributors and copyright holders.                    *
 * This file is licensed under LGPL-3.0, see LICENSE.md.                  *
 **************************************************************************/
enum input {
  t3_0,
  t3_1,
  t3_2,
  t2_0,
  t2_1,
  t2_2,
  cdc_open90,
  cdc_active,
  cdc_b2b3,
  cdc_b2b5,
  cdc_b2b7, // 10
  cdc_b2b9,
  ehigh,
  elow,
  elum,
  ecl_bha,
  bha_type_0,
  bha_type_1,
  bha_type_2,
  bha_type_3,
  bha_type_4, // 20
  bha_type_5,
  bha_type_6,
  bha_type_7,
  bha_type_8,
  bha_type_9,
  bha_type_10,
  bha_type_11,
  bha_type_12,
  bha_type_13,
  clst_0,     // 30
  clst_1,
  clst_2,
  clst_3,
  ecl_bg_0,
  ecl_bg_1,
  ecl_bg_2,
  ecl_active,
  ecl_timing_fwd,
  ecl_timing_brl,
  ecl_timing_bwd, // 40
  ecl_phys,
  top_0,
  top_1,
  top_2,
  top_bb,
  top_active,
  klm_hit,
  klm_0,
  klm_1,
  klm_2,    // 50
  klm_3,
  klmb2b_0,
  klmb2b_1,
  klmb2b_2,
  revo,
  her_kick,
  ler_kick,
  bha_delay,
  pseud_rand,
  plsin,        // 60
  poissonin,
  periodin,
  veto,
  nclst1_0,
  nclst1_1,
  nclst1_2,
  nclst2_0,
  nclst2_1,
  nclst2_2,
  cdcecl_0, // 70
  cdcecl_1,
  cdcecl_2,
  cdcklm_0,
  cdcklm_1,
  cdcklm_2,
  nimin0,
  nimin1,
  nimin2,
  nimin3,
  t3_3,        // 80
  t2_3,
  nclst1_3,
  nclst2_3,
  cdcecl_3,
  cdcklm_3,
  u2_0,
  u2_1,
  u2_2,
  ecl_oflo,
  ecl_3dbha, // 90
  lml_0,
  lml_1,
  lml_2,
  lml_3,
  lml_4,
  lml_5,
  lml_6,
  lml_7,
  lml_8,
  lml_9,  // 100
  lml_10,
  samhem,
  opohem,
  d_b2b3,
  d_b2b5,
  d_b2b7,
  d_b2b9,
  p_b2b3,
  p_b2b5,
  p_b2b7, // 110
  p_b2b9
};
