Import('env')

env['LIBS'] = [
    
    'framework', 
    'boost_regex'

    #'boost_chrono',
    #'geometry',
    #'pxd', 'pxd_dataobjects',
    #'svd', 'svd_dataobjects',
    #'vxd', 'vxd_dataobjects',
    #'genfit2',
    #'tracking',
    #'tracking_dataobjects',
    ]
Return('env')
