Import('env')

#These are the libraries the awesome package has to be linked against
env['LIBS'] = ['framework','$ROOT_LIBS', 'mdst_dataobjects','beast_pindiode_dataobjects', 'generators_SAD_dataobjects', 'simulation_dataobjects']

Return('env')
