Import('env')

env['LIBS'] = ['framework', 'analysis_dataobjects', 'analysis',
               'mdst_dataobjects', 'analysis_DecayDescriptor', 'analysis_ParticleCombiner',
               '$ROOT_LIBS']

Return('env')
