Import('env')

# This file specifies the dependencies of your Analysis code to parts of the
# Belle 2 Software. It should be fine for most analysis but if you need to link
# against additional libraries please put them here.
env['LIBS'] = [
    'analysis_dataobjects',
    'analysis',
    'framework',
    '$ROOT_LIBS',
]

Return('env')