Import('env')

env['TOOLS_LIBS']['rodummy_in'] = ['daq', 'framework', '$ROOT_LIBS' ]
env['TOOLS_LIBS']['rodummy_out'] = ['daq', 'framework', '$ROOT_LIBS' ]
env['TOOLS_LIBS']['rodummy_io'] = ['daq', 'framework', '$ROOT_LIBS' ]
env['TOOLS_LIBS']['dummy_gen'] = ['daq', 'framework', '$ROOT_LIBS' ]
env['TOOLS_LIBS']['flow_monitor'] = ['daq', 'framework', '$ROOT_LIBS' ]

Return('env')
