Import('env')

env['TOOLS_LIBS']['rodummy_in'] = ['daq', 'framework']
env['TOOLS_LIBS']['rodummy_out'] = ['daq', 'framework']
env['TOOLS_LIBS']['rodummy_io'] = ['daq', 'framework']
env['TOOLS_LIBS']['dummy_gen'] = ['daq', 'framework']
env['TOOLS_LIBS']['flow_monitor'] = ['daq', 'framework']
env['TOOLS_LIBS']['read_roinfo'] = ['daq']
env['TOOLS_LIBS']['create_roinfo'] = ['daq']
env['TOOLS_LIBS']['socketcheck'] = ['daq']

Return('env')
