Import('env')

env['TOOLS_LIBS']['shmclean'] = ['rt']
env['TOOLS_LIBS']['nsmcui']  = ['nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['confget']  = ['daq']
env['TOOLS_LIBS']['rfconfcreate']  = ['daq', '$PGSQL_LIBS']
env['TOOLS_LIBS']['rfconfget']  = ['daq', '$PGSQL_LIBS']
env['TOOLS_LIBS']['bootnsmd2']  = ['daq']
env['TOOLS_LIBS']['checknsm2']  = ['daq']
env['TOOLS_LIBS']['semtest']  = ['framework', 'daq']
env['TOOLS_LIBS']['bootecl']  = ['daq']
env['TOOLS_LIBS']['bootcdc']  = ['daq']
env['TOOLS_LIBS']['boottop']  = ['daq']
env['TOOLS_LIBS']['boottrg']  = ['daq']
env['TOOLS_LIBS']['bootklm']  = ['daq']
env['TOOLS_LIBS']['bootcopper']  = ['daq']
env['TOOLS_LIBS']['bootarich']  = ['daq']

Return('env')
