Import('env')

env['TOOLS_LIBS']['shmclean'] = ['rt']
env['TOOLS_LIBS']['nsmcui']  = ['nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['getconfig']  = ['daq']
env['TOOLS_LIBS']['rfconfcreate']  = ['daq', 'framework', '$PGSQL_LIBS']
env['TOOLS_LIBS']['rfconfget']  = ['daq', 'framework', '$PGSQL_LIBS']
env['TOOLS_LIBS']['rcconfigget']  = ['daq', 'framework', '$PGSQL_LIBS']

Return('env')
