Import('env')

env['TOOLS_LIBS']['createParamTable'] = ['daq', 'framework', '$PGSQL_LIBS']
env['TOOLS_LIBS']['addParamConfig'] = ['daq', 'framework', '$PGSQL_LIBS']
env['TOOLS_LIBS']['addRunConfig'] = ['daq', 'framework', '$PGSQL_LIBS']
env['TOOLS_LIBS']['testRunSetting'] = ['daq', 'framework', '$PGSQL_LIBS']

Return('env')
