Import('env')

env['LIBS'] = [
    'tracking',
    'tracking_trackFindingCDC',
    'cdc_dataobjects',
    'framework',
    'framework_pybasf2',
    '$ROOT_LIBS',
    '$PYTHON_LIBS',
    ]

Return('env')
