#!/usr/bin/env python3
# -*- coding: utf-8 -*-

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

import basf2
from tracking.run.event_generation import ReadOrGenerateEventsRun
from tracking.run.mixins import RootOutputRunMixin

import logging

class StandardEventGenerationRun(RootOutputRunMixin, ReadOrGenerateEventsRun):
    allow_input = False
    generator_module = 'EvtGenInput'

def main():
    readOrGenerateEventsRun = StandardEventGenerationRun()
    readOrGenerateEventsRun.configure_and_execute_from_commandline()

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
