#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import basf2
from tracking.run.event_generation import ReadOrGenerateEventsRun
from tracking.run.mixins import RootOutputRunMixin

import logging

class StandardEventGenerationRun(RootOutputRunMixin, ReadOrGenerateEventsRun):
    allow_input = False
    generator_module = 'EvtGenInput'

def main():
    readOrGenerateEventsRun = StandardEventGenerationRun()
    readOrGenerateEventsRun.configure_and_execute_from_commandline()

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
