#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import basf2
from tracking.run.tracked_event_generation import ReadOrGenerateTrackedEventsRun
from tracking.run.mixins import RootOutputRunMixin

import logging

class TrackingRun(RootOutputRunMixin, ReadOrGenerateTrackedEventsRun):
    allow_input = True
    generator_module = 'EvtGenInput'
    finder_module = "TrackFinder"

def main():
    tracking_run = TrackingRun()
    tracking_run.configure_and_execute_from_commandline()

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
