#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import basf2
from tracking.cli.run import run_generator


def main():
    arguments = dict()
    run_generator(arguments)


if __name__ == "__main__":
    main()
