Import('env')

env['TOOLS_LIBS']['rf_master'] = ['pthread', 'daq', 'nsm2_b2lib', 'nsm2_corelib', '$PGSQL_LIBS']
env['TOOLS_LIBS']['rfarmmonitor'] = ['pthread', 'daq', 'nsm2_b2lib', 'nsm2_corelib', '$PGSQL_LIBS']
env['TOOLS_LIBS']['testrfclient'] = ['pthread', 'daq', 'nsm2_b2lib', 'nsm2_corelib', '$PGSQL_LIBS']

Return('env')
