Import('env')

env['LIBS'] = ['framework', '$ROOT_LIBS', 'genfit2', 'simulation_dataobjects', 'cdc_dataobjects', 'vxd_dataobjects', 'pxd_dataobjects', 'svd_dataobjects', 'pxd', 'svd', 'alignment_database']
Return('env')
