Import('env')

env['LIBS'] = ['framework', '$ROOT_LIBS', 'Geom',
               '$GEANT4_LIBS', 'CLHEP',
               'boost_python', 'boost_iostreams',
               'BaseVGM','ClhepVGM','Geant4GM','RootGM',
               '$PYTHON_LIBS']

Return('env')
