Import('env')

env['LIBS'] = ['$ROOT_LIBS', 'Geom',
               'G4root', '$GEANT4_LIBS', 'CLHEP',
               'boost_python',
               '$PYTHON_LIBS', '$XML_LIBS',
               'ir', 'pxd', 'svd', 'cdc', 'top', 'arich', 'eklm']

Return('env')
