Import('env')

env['LIBS'] = [
	'cdc_dataobjects',
	'framework',
	'genfit2',
	'tracking_dataobjects',
	'mdst_dataobjects',
	'pxd_dataobjects',
	'svd_dataobjects',
	'tracking',
	'klm_dataobjects'
    ]

Return('env')
