Import('env')

env['LIBS'] = [
	'cdc_dataobjects',
	'cdc',
	'framework',
	'genfit2',
	'tracking_dataobjects',
	'mdst_dataobjects',
	'pxd_dataobjects',
	'svd_dataobjects',
	'vxd_dataobjects'
    ]

Return('env')
