Import('env')

env['LIBS'] = [
    'tracking_trackFindingCDC',
    'mdst_dataobjects',
    'simulation_dataobjects',
    'framework',
    'framework_pybasf2',
    '$ROOT_LIBS',
    '$PYTHON_LIBS',
    'genfit2',
    'cdc_dataobjects',
    'cdc',
    ]

Return('env')
