Import('env')

env['SUBLIB'] = True
env['LIBS'] = ['framework', 
               'analysis_dataobjects',
               'mdst_dataobjects', 
               '$ROOT_LIBS', 
               'CLHEP', 
               'EG',
	             'analysis_ClusterUtility', 
]

Return('env')
