# -*- coding: utf-8 -*-
#vim: syntax=python

Import('env')

env['LIBS'] = [
    'tracking', 'tracking_dataobjects',
    'vxd',
    'vxd_dataobjects',
    #'pxd',
    'pxd_dataobjects',
    'cdc',
    'cdc_dataobjects',
    'simulation_dataobjects',
    'framework',
    'Geom',
    'geometry',
#   'genfit2',
    '$ROOT_LIBS',
    'boost_chrono',
    '$PYTHON_LIBS',
    #'generators',
    ]

Return('env')
