Import('env')

env.ParseConfig("python3 -c 'import numpy; print(f\"-I{numpy.get_include():s}\")'")

env['LIBS'] = [
	    'framework',
	    'framework_io',
	    'mva_dataobjects',
	    'boost_program_options',
	    'FastBDT_shared',
	    'MLP',
	    'onnxruntime',
	    'TMVA',
	    'XMLIO',
	    '$ROOT_LIBS',
]

Return('env')
