Import('env')

env.ParseConfig("python3 -c 'import numpy; print(\"-I%s\" % numpy.get_include())'") 

env['LIBS'] = ['framework', 'mva_dataobjects', 'analysis', '$ROOT_LIBS', 'fann', 'libFastBDT_shared']

env.Append(LIBS = ['NeuroBayesExpertCPP'])
env.Append(LIBS = ['NeuroBayesTeacherCPP'])
env.Append(LIBS = ['TMVA','MLP','XMLIO'])

Return('env')
