#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import subprocess

argvs = sys.argv
argc = len(argvs)

#with open('/dev/null', 'w') as f:
with open('dummyout.dat', 'w') as f:
    p = subprocess.call ( ['nc', '-l', argvs[3]], stdout=f, stderr=f )
