#!/bin/sh


/bin/mkdir /dev/mqueue
/bin/mount -t mqueue none /dev/mqueue
/bin/chmod o-t /dev/mqueue

/bin/echo    20 > /proc/sys/fs/mqueue/msg_max
/bin/echo 16384 > /proc/sys/fs/mqueue/msgsize_max
/bin/echo    32 > /proc/sys/fs/mqueue/queues_max

