Import('env')

env['LIBS'] = ['framework', 'analysis','mdst_dataobjects', 'analysis_dataobjects',
               'arich_dataobjects','tracking_dataobjects', 'analysis_DecayDescriptor', '$ROOT_LIBS']

Return('env')
