export BELLE2_LOCAL_DIR=$HOME/belle2/release2
export BELLE2_EXTERNAL_LOCAL_DIR=$HOME/belle2/external/v00-05-02
export BELLE2_DAQ_SLC=$BELLE2_LOCAL_DIR/daq/slc
export PATH=$BELLE2_DAQ_SLC/bin:$PATH
export LD_LIBRARY_PATH=$BELLE2_DAQ_SLC/lib:$LD_LIBRARY_PATH
