#ifndef SVDSTATEDEFS_H_
#define SVDSTATEDEFS_H_
typedef enum {
  MASTER_STATE_UNKNOWN = 0,
  MASTER_STATE_ERROR = 1,
  MASTER_STATE_NOTREADY = 2,
  MASTER_STATE_LOADING = 3,
  MASTER_STATE_READY = 4,
  MASTER_STATE_STARTING = 5,
  MASTER_STATE_RUNNING = 6,
  MASTER_STATE_STOPPING = 7,
  MASTER_STATE_UNLOADING = 8,
  MASTER_STATE_ABORTING = 9,
} SVDMasterStates_t;

typedef enum {
  MAIN_STATE_IDLE = 0,
  MAIN_STATE_CONFIGURING = 1,
  MAIN_STATE_READY = 2,
  MAIN_STATE_STARTING = 3,
  MAIN_STATE_RUNNING = 4,
  MAIN_STATE_STOPPING = 5,
  MAIN_STATE_FINISHED = 6,
  MAIN_STATE_FINISHING = 7,
  MAIN_STATE_EXITED = 8,
  MAIN_STATE_EXITING = 9,
  MAIN_STATE_ERROR = 10,
  MAIN_STATE_ABORTING = 11,
  MAIN_STATE_DOWN = 12
} SVDMainStates_t;

typedef enum {
  SUB_STATE_DOWN = 1,
  SUB_STATE_IDLE = 2,
  SUB_STATE_INITIALIZING = 3,
  SUB_STATE_INITIALIZED = 4,
  SUB_STATE_CONFIGURING = 5,
  SUB_STATE_READY = 6,
  SUB_STATE_STARTING = 7,
  SUB_STATE_RUNNING = 8,
  SUB_STATE_STOPPING = 9,
  SUB_STATE_ABORTING = 11,
  SUB_STATE_FINISHING = 13,
  SUB_STATE_ERROR = 0,
} SVDSubState_t;

typedef enum {
  MAIN_REQ_PROCESSED = 0,
  MAIN_REQ_CONFIGURE = 1,
  MAIN_REQ_START = 2,
  MAIN_REQ_STOP = 3,
  MAIN_REQ_ABORT = 4,
  MAIN_REQ_EXIT = 5,
} SVDMainRequest_t;

typedef enum {
  SUB_REQ_PROCESSED = 0,
  SUB_REQ_INITIALIZE = 1,
  SUB_REQ_CONFIGURE = 2,
  SUB_REQ_START = 3,
  SUB_REQ_STOP = 4,
  SUB_REQ_ABORT = 5,
  SUB_REQ_RESET = 6,
  SUB_REQ_FINISH = 7,
} SVDSubRequest_t;



#endif
