# -*- coding: utf-8 -*-
# vim: syntax=python

Import('env')

env['LIBS'] = [
    'framework',
    'hlt_softwaretrigger_dataobjects',
    'hlt',
    '$ROOT_LIBS',
    "framework",
    "tracking_dataobjects",
    "mdst_dataobjects",
    "analysis_dataobjects",
    "analysis_utility"
    
    ]

Return('env')

