Import('env')

env['LIBS'] = ['framework',
               'trg_trg',
               'mdst_dataobjects',
               'cdc_dataobjects',
               'cdc',
               'trg_cdc',
               'trg_cdc_dataobjects']
#print env.Dump()

Return('env')
