/**************************************************************************
 * BASF2 (Belle Analysis Framework 2)                                     *
 * Copyright(C) 2012 - Belle II Collaboration                             *
 *                                                                        *
 * Author: The Belle II Collaboration                                     *
 * Contributors: Oliver Frost                                             *
 *                                                                        *
 * This software is provided "as is" without any warranty.                *
 **************************************************************************/
#ifndef CDCLOCALTRACKINGMODULE_H_
#define CDCLOCALTRACKINGMODULE_H_

//#define LOG_NO_B2DEBUG
#include <framework/core/Module.h>

#include <tracking/cdcLocalTracking/config/CDCLocalTrackingConfig.h>

#include <tracking/cdcLocalTracking/eventdata/CDCEventData.h>
#include <tracking/cdcLocalTracking/filters/CDCFilters.h>

#include <tracking/cdcLocalTracking/workers/FacetSegmentWorker.h>
#include <tracking/cdcLocalTracking/workers/SegmentTripleTrackingWorker.h>

namespace Belle2 {

  /// Module for the cellular automaton tracking for the CDC
  class CDCLocalTrackingModule : public Module {

  public:

    /// Constructor of the module. Setting up parameters and description.
    CDCLocalTrackingModule();

    /// Destructor of the module.
    virtual ~CDCLocalTrackingModule();

    ///  Initialize the Module before event processing
    virtual void initialize();

    /// Called when entering a new run.
    virtual void beginRun();

    /// Processes the event and generates track candidates
    virtual void event();

    /// Called at the end of a run.
    virtual void endRun();

    /// Terminate and free resources after last event has been processed
    virtual void terminate();

  private:
    /// Parameter: Name of the output StoreArray for the Genfit track candidates generated by this module.
    std::string m_param_gfTrackCandColName; /**< Name of the output collection of genfit::TrackCands */

    /// Worker to carry out the first stage for segment generation
    CDCLocalTracking::FacetSegmentWorker <
    CDCLocalTracking::FacetFilter,
                     CDCLocalTracking::FacetNeighborChooser
                     > m_segmentWorker;

    /// Pool to store the segments between the stages
    std::vector< Belle2::CDCLocalTracking::CDCRecoSegment2D > m_recoSegments;

    /// Worker to carry out the second stage generating tracks from segments.
    CDCLocalTracking::SegmentTripleTrackingWorker <
    CDCLocalTracking::AxialAxialSegmentPairFilter,
                     CDCLocalTracking::SegmentTripleFilter,
                     CDCLocalTracking::SegmentTripleNeighborChooser
                     > m_trackingWorker;

  }; // end class
} // end namespace Belle2

#endif /* CDCLOCALTRACKINGMODULE_H_ */

