Import('env')

env['LIBS'] = ['framework', 'analysis', 'analysis_dataobjects', 
               'generators_dataobjects', 'tracking_dataobjects',
               'ecl_dataobjects', 'reconstruction_dataobjects',
               '$ROOT_LIBS']

Return('env')
