Import('env')

env['LIBS'] = ['$ROOT_LIBS',
               'EG', # for TDatabasePDG
               'XMLIO', # for TBufferXML
               'boost_python', 'boost_filesystem', 'boost_regex', 'boost_iostreams', 'boost_system',
               '$PYTHON_LIBS', '$XML_LIBS', '$SQLITE_LIBS', '$MYSQL_LIBS' , '$PGSQL_LIBS',
               'rt', # for clock_gettime() on some systems
               'curl' # for REST API access to the database
               ]

# Macros to limit the variations of the utilities/sha3hash implementation
env.Append(CPPDEFINES={"KeccakP200_excluded" : None,
                       "KeccakP400_excluded" : None,
                       "KeccakP800_excluded" : None})

Return('env')
