Import('env')

env['LIBS'] = ['$ROOT_LIBS', 'Geom', 'EG',
               'g4root', '$GEANT4_LIBS', 'CLHEP',
               'boost_python', 'boost_filesystem', 'boost_regex',
               '$PYTHON_LIBS', '$XML_LIBS']

Return('env')
