Import('env')

env['LIBS'] = ['framework', 'analysis', 'analysis_dataobjects', 'analysis_raveInterface',
               'analysis_utility', 'mdst_dataobjects', 'RaveBase', 
	       '$ROOT_LIBS', 'CLHEP']

Return('env')
