Import('env')
env['LIBS'] = ['framework',
               'mdst_dataobjects',
               'trg',
               'trg_ecl_dataobjects',
               'trg_gdl_dataobjects',
               'trg_grl_dataobjects',
               'trg_top_dataobjects']
Return('env')

