Import('env')

env['LIBS'] = [
  'framework',
  'vxd', 'vxd_dataobjects',
  'tracking', 'tracking_dataobjects',
  'testbeam_vxd_dataobjects',
  '$ROOT_LIBS', 
  'boost_regex',
  'genfit2'] # 'tracking', 

Return('env')
