Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'calibration',
               '$ROOT_LIBS', 'Geom', 'EG', 'cdc_dataobjects',
               '$GEANT4_LIBS', 'CLHEP', 'mdst_dataobjects']

#env.Append(CPPDEFINES = {'CDC_DEBUG':None})

#env.Append(CPPDEFINES = {'CDC_T0_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_BADWIRE_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_PROPSPEED_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_TIMEWALK_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_XTREL_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_SRESOL_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_CHMAP_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_DISPLACEMENT_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_ALIGN_FROM_DB':None})
#env.Append(CPPDEFINES = {'CDC_MISALIGN_FROM_DB':None})

Return('env')
