Import('env')

if "daq" not in env["AVAILABLE_PACKAGES"]:
    env["CONTINUE"] = False

env['LIBS'] = ['framework', 'daq', 'boost_regex', 'dqm_analysis_modules']

env['SUBLIB'] = True
env.Append(LIBPATH=['$MODDIR'])

Return('env')
