Import('env')

env['TOOLS_LIBS']['numberOfEventsInBelleMdst'] = ['stdc++', 'framework', 'boost_program_options', 'belle_legacy', 'pq', 'readline', 'termcap', 'z', 'b2bii']
env['TOOLS_LIBS']['numberOfEventsInBelle2Mdst'] = ['stdc++', 'framework', 'boost_program_options']

Return('env')
