Import('env')

env['LIBS'] = [
    'framework',
    'tracking_dataobjects',
    'mdst_dataobjects',
    'vxd',
    'svd_dataobjects',
    'vxd_dataobjects',
    '$ROOT_LIBS',
    'calibration'
    ]
Return('env')
