Import('env')

env['LIBS'] = [
    '$ROOT_LIBS',
    'framework',
    'mdst_dataobjects',
    'vxd', 'vxd_dataobjects',
    'pxd_dataobjects',
    'genfit2',
    'tracking_dataobjects',
    'NeuroBayesExpertCPP'
    ]

Return('env')
