#!/usr/bin/env python3

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

import sys
import subprocess
import basf2 as b2

OLD = "basf2_mva_upload"
NEW = "basf2_mva_add_to_local_database"

output_string = f"\n\033[0;31mAttention:\033[0m {OLD} has been deprecated in favor of {NEW} as the name {OLD} was confusing.\n"
output_string += " The old name has been kept for compatibility but will be removed in release-09.\n"
output_string += f"From now on please use \033[0;32m{NEW}\033[0m.\n"

b2.B2WARNING(output_string)

command = f"{NEW} {subprocess.list2cmdline(sys.argv[1:]).replace('--identifier', '--weight_file_name')}"

subprocess.run(command.split())
