Import('env')

env['TOOLS_LIBS']['basf2_mva_available'] = ['stdc++', 'framework', 'mva', 'mva_dataobjects', 'boost_program_options', '$ROOT_LIBS']
env['TOOLS_LIBS']['basf2_mva_teacher'] = ['stdc++', 'framework', 'mva', 'mva_dataobjects', 'boost_program_options', '$ROOT_LIBS']
env['TOOLS_LIBS']['basf2_mva_expert'] = ['stdc++', 'framework', 'mva', 'mva_dataobjects', 'boost_program_options', '$ROOT_LIBS']
env['TOOLS_LIBS']['basf2_mva_extract'] = ['stdc++', 'framework', 'mva', 'mva_dataobjects', 'boost_program_options', '$ROOT_LIBS']
env['TOOLS_LIBS']['basf2_mva_upload'] = ['stdc++', 'framework', 'mva', 'mva_dataobjects', 'boost_program_options', '$ROOT_LIBS']
env['TOOLS_LIBS']['basf2_mva_download'] = ['stdc++', 'framework', 'mva', 'mva_dataobjects', 'boost_program_options', '$ROOT_LIBS']
env['TOOLS_LIBS']['basf2_mva_info'] = ['stdc++', 'framework', 'mva', 'mva_dataobjects', 'boost_program_options', '$ROOT_LIBS']


Return('env')
