Import('env')

#print(" now in sptcNetwork!")

#import os

## Mark this folder as a sub library
env['SUBLIB'] = True
##env.Dictionary()['SUBLIB'] = True


env['LIBS'] = [
    'genfit2', 
    'pxd_dataobjects', 
    'svd_dataobjects', 
    'vxd',
    'vxd_dataobjects', 
    'framework', 
    'tracking'
    ]
Return('env')
