Import('env')

#print(" now in sptcNetwork!")

#import os

## Mark this folder as a sub library
env['SUBLIB'] = True
##env.Dictionary()['SUBLIB'] = True


env['LIBS'] = [
    'framework', 
    ]
Return('env')
