/**************************************************************************
 * BASF2 (Belle Analysis Framework 2)                                     *
 * Copyright(C) 2010 - Belle II Collaboration                             *
 *                                                                        *
 * Author: The Belle II Collaboration                                     *
 * Contributors: Peter Kvasnicka, Zbynek Drasal                           *
 *                                                                        *
 * This software is provided "as is" without any warranty.                *
 **************************************************************************/

#ifndef PXDCHEATER_H
#define PXDCHEATER_H

#include <framework/datastore/Units.h>

namespace Belle2 {

  /*
   ** PXD cheater class
   *
   * The class provides detector pitch values which are currently nowhere to read
   * from, and provides simulation resolutions for the Gaussian-smearing
   * digitizer. It is a temporary class.'
   */

  class PXDcheater {

  public:
    /**
     * The constructor just sets defaults.
     */
    PXDcheater() {
      m_pitchRPhi1 = 50;
      m_pitchRPhi2 = 50;
      m_pitchZ1 = 50;
      m_pitchZ2 = 75;
    }

    ~PXDcheater() {
      // Does nothing.
    }
    /**
     * Return resolution estimate for a specific sensor.
     *
     * These functions are based on MC estimates of sensor resolutions.
     * Sensor resolution is parametrized by a single parameter, the
     * theta angle of impact. Interpolants are spline fits to the data.
     * The interpolants' codes are automatically generated by ROOT TSpline class.
     */
    double getResolutionZ(int iLayer, int iLadder, int iSensor, double theta) const;
    double getResolutionRPhi(int iLayer, int iLadder, int iSensor, double theta) const;
    /*
     * Return pitch for a specific sensor.
     */
    double getPitchZ(int iLayer, int iLadder, int iSensor) const;
    double getPitchRPhi(int iLayer, int iLadder, int iSensor) const;

  protected:
    /**
     * These are spline fits of simulation data.
     *
     * These functions are automatically generated by the ROOT TSpline class.
     */
    double PXD_ResFunc_rphi1(double x) const;
    double PXD_ResFunc_rphi2(double x) const;
    double PXD_ResFunc_z1(double x) const;
    double PXD_ResFunc_z2(double x) const;

  private:
    /** Pitch values. */
    double m_pitchRPhi1;
    double m_pitchRPhi2;
    double m_pitchZ1;
    double m_pitchZ2;

  }; // class PXDcheater

} // end namespace Belle2

#endif
