Import('env')

import commands
import os.path
if os.path.exists("/etc/redhat-release"):
   osver = float(commands.getoutput("cat /etc/redhat-release | awk '{print $4}'"))
#   print osver
   if osver < 6.0:
#      print "SL5"
      env['TOOLS_LIBS']['hvcui'] = ['pthread', 'ncurses', 'readline', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
   elif osver >= 6.0:
#      print "SL6"
      env['TOOLS_LIBS']['hvcui'] = ['pthread', 'ncurses', 'tinfo', 'readline', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
else:
      env['TOOLS_LIBS']['hvcui'] = ['pthread', 'ncurses', 'readline', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']

env['TOOLS_LIBS']['hv2db'] = ['pthread', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['db2hv'] = ['pthread', 'ncurses', '$ROOT_LIBS', 'libNew', 'Geom',
			      '$GEANT4_LIBS', 'CLHEP', 'readline', '$PGSQL_LIBS', 
			      'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']

Return('env')
