Import('env')

env['TOOLS_LIBS']['hvcui'] = ['pthread', 'ncurses', 'readline', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['hv2db'] = ['pthread', 'ncurses', 'readline', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['db2hv'] = ['pthread', 'ncurses', '$ROOT_LIBS', 'libNew', 'Geom',
			      '$GEANT4_LIBS', 'CLHEP', 'readline', '$PGSQL_LIBS', 
			      'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']

Return('env')
