Import('env')

env['LIBS'] = [
    'CLHEP',
    '$ROOT_LIBS',
    '$GEANT4_LIBS',
    'framework',
    'simulation',
    'geometry',
    'generators_dataobjects',
    'genfit2',
    'tracking_dataobjects',
    'bklm', 'bklm_dataobjects',
    'eklm_dataobjects', 
    ]

Return('env')
