Import('env')

env['LIBS'] = [
    'CLHEP',
    '$ROOT_LIBS',
    '$GEANT4_LIBS',
    'framework',
    'simulation',
    'genfit2',
    'tracking_dataobjects',
    'bklm', 'bklm_dataobjects', 'bklm_dbobjects',
    'eklm', 'eklm_dataobjects', 'eklm_dbobjects',
    'simulation_dataobjects',
    'mdst_dataobjects',
    ]

Return('env')
