Import('env')

env['LIBS'] = ['framework', 'simulation', 'geometry',
               'generators_dataobjects', 'tracking_dataobjects', 'bklm_dataobjects', 'eklm_dataobjects', 'bklm',
               '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP']

Return('env')
