import os

Import('env')

env['SUBLIB'] = True
env['LIBS'] = ['$ROOT_LIBS', 'analysis_dataobjects', 'mdst_dataobjects', 'framework', 'gfortran']

env.Append(FORTRANFLAGS=['-O3', '-fno-automatic', '-ffixed-line-length-none'])
#env.Append(FORTRANFLAGS = '')

Return('env')
