#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys

from rfarmutil import *

argvs = sys.argv
argc = len(argvs)


conffile = argvs[1]

# Install Event Processor scripts
nodebase = get_rfgetconf(conffile, 'processor', 'nodebase')
basedir = get_rfgetconf(conffile, 'system', 'execdir_base')
nnodes = int(get_rfgetconf(conffile, 'processor', 'nnodes'))
procid = int(get_rfgetconf(conffile, 'processor', 'idbase'))
badlist = get_rfgetconf(conffile, 'processor', 'badlist')
id = int(get_rfgetconf(conffile, 'processor', 'idbase'))

for i in range(procid, procid + nnodes):
    nodeid = '%2.2d' % i
    if badlist.find(nodeid) == -1:
        nodename = nodebase + nodeid
        if not os.path.exists(basedir + '/evp_' + nodename):
            os.mkdir(basedir + '/evp_' + nodename)
        os.chdir(basedir + '/evp_' + nodename)
        for f in os.listdir(basedir + '/evp_scripts'):
            if f.endswith(".py"):
                if (os.path.exists(f)):
                    os.remove(f)
                os.symlink("../evp_scripts/" + f, f)
