#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys

from rfarmutil import *

argvs = sys.argv
argc = len(argvs)

if argc<=1:
    print "Usage : stop_rfarm_local config_name"
    sys.exit()
    
stop_rfarm_local ( argvs[1] )


