#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import validationserver

"""
Start the server which hosts the validation result plots
"""

# Only execute if the file is not imported
if __name__ == '__main__':
    # run validation server with default settings and 
    # parse command line input in any case
    validationserver.run_server(parseCommandLine=True)
