#!/usr/bin/env python3

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

from ROOT import PyConfig
PyConfig.IgnoreCommandLineOptions = True
import validationserver

"""
Start the server which hosts the validation result plots and 
serves them.
"""

# Only execute if the file is not imported
if __name__ == '__main__':
    # run validation server with default settings and 
    # parse command line input in any case
    validationserver.run_server(parse_command_line=True)
