#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import validationserver

# Only execute if the file is not imported
if __name__ == '__main__':
    # run validation server with default settings and 
    # parse command line input
    validationserver.run_server(parseCommandLine=True)
