# -*- coding: utf-8 -*-
# vim: syntax=python

Import('env')

env['LIBS'] = [
    'framework',
    '$ROOT_LIBS',
    'mdst_dataobjects',
    'hlt_softwaretrigger_dataobjects',
    'hlt',
    'klm_eklm_dataobjects',
    'klm_bklm_dataobjects',
    'ecl_dataobjects'
    ]

Return('env')

