Import('env')

env['LIBS'] = ['framework', 'geometry', 'generators_dataobjects',
               '$ROOT_LIBS', 'Geom', 'EG', 'g4root',
               '$GEANT4_LIBS', 'G4GMocren', 'CLHEP']

Return('env')
