Import('env')

env['LIBS'] = ['framework', 'geometry', 'generators_dataobjects', 'mdst_dataobjects', 'simulation_dataobjects',
               '$ROOT_LIBS', 'Geom', 'EG',
               '$GEANT4_LIBS', 'G4GMocren', 'CLHEP']

Return('env')
