Import('env')

env['LIBS'] = ['framework', 'geometry']

# check if we have GDML support
conf = Configure(env)
if conf.CheckHeader('G4GDMLParser.hh', language="C++"):
    env.Append(CPPDEFINES="HAS_GDML")

Return('env')
