Import('env')


env['LIBS'] = ['framework', '$ROOT_LIBS',
               'analysis_utility',
               'trg', 'trg_ecl_dataobjects', 'trg_grl_dataobjects',
               'trg_grl_dbobjects',
               'fann',
               'mdst_dataobjects']
               

Return('env')
