Import('env')
env['LIBS'] = ['$ROOT_LIBS', 
                'calibration', 
                'framework', 
                'cdc_dataobjects', 
                'cdc_dbobjects', 
                'mdst_dataobjects', 
                'analysis_dataobjects'
            ]
Return('env')

