Import('env')

env['SUBLIB'] = True
env['LIBS'] = ['framework',
	       'cdc',
	       'rawdata_dataobjects',
	       'cdc_dataobjects',
	       'trg_cdc_dataobjects',
         'trg_trg']
#env.Append(CPPDEFINES = {'TRGCDC_DISPLAY':None})
#env.Append(CPPDEFINES = {'TRGCDC_DISPLAY_HOUGH':None})
#env.ParseConfig('pkg-config --cflags --libs gtkmm-2.4')
#print env.Dump()

Return('env')
