#
#    Makefile of basf modules (for simple directory hierarchy)
#   ------------------------------------------------------------
#
#     INPUTS:
#       MODULES    list of basf modules to make
#       MAINS      list of executables to make
#       OBJS       list of other objects to link(if any)
#       LIBS       list of libraries to link 
#       CERNLIBS   list of cern libraries to link
#
#     *NOTES* remove suffixes or "-l" for above lists
#             e.g. module.cc -> module, -llibrary -> library
#
#

# 1. User Specifications

MODULES =

MAINS =

OBJS =

LIBS =

CERNLIBS =

# 2. System Specifications

include ../config/Makefile.common
