Import('env')
env['TOOLS_LIBS']['analyzeWave'] = ['framework', 'topcaf_dataobjects', '$ROOT_LIBS', 'TreePlayer'];
env['TOOLS_LIBS']['analyzeHits'] = ['framework', 'topcaf_dataobjects', '$ROOT_LIBS', 'TreePlayer', 'Spectrum'];
env['TOOLS_LIBS']['analyzeHits_extended'] = ['framework', 'topcaf_dataobjects', '$ROOT_LIBS', 'TreePlayer', 'Spectrum'];
env['TOOLS_LIBS']['pedestalStability'] = ['framework', 'topcaf_dataobjects', '$ROOT_LIBS', 'TreePlayer'];
env['TOOLS_LIBS']['analyzeHits'] = ['$ROOT_LIBS', 'TreePlayer', 'topcaf_dataobjects', 'Spectrum'];
env['TOOLS_LIBS']['analyzeTopDigits'] = ['$ROOT_LIBS', 'TreePlayer', 'topcaf_dataobjects'];
env['TOOLS_LIBS']['plotCalibrationChannel'] = ['$ROOT_LIBS', 'TreePlayer', 'topcaf_dataobjects'];
env['TOOLS_LIBS']['plotChannels'] = ['$ROOT_LIBS', 'TreePlayer', 'topcaf_dataobjects'];
Return('env')
