Import('env')
env['TOOLS_LIBS']['analyzeWave'] = ['framework', 'topcaf_dataobjects', '$ROOT_LIBS', 'TreePlayer'];
env['TOOLS_LIBS']['pedestalStability'] = ['framework', 'topcaf_dataobjects', '$ROOT_LIBS', 'TreePlayer'];
env['TOOLS_LIBS']['compareWave'] = ['$ROOT_LIBS', 'TreePlayer'];
Return('env')
