/**************************************************************************
 * BASF2 (Belle Analysis Framework 2)                                     *
 * Copyright(C) 2017 - Belle II Collaboration                             *
 *                                                                        *
 * Author: The Belle II Collaboration                                     *
 * Contributors: Kirill Chilikin                                          *
 *                                                                        *
 * This software is provided "as is" without any warranty.                *
 **************************************************************************/

/* Belle 2 headers. */
#include <framework/datastore/StoreArray.h>
#include <framework/datastore/StoreObjPtr.h>
#include <framework/gearbox/Unit.h>
#include <framework/gearbox/Const.h>
#include <framework/utilities/FileSystem.h>
#include <generators/modules/evtgendecay/EvtGenDecayModule.h>

using namespace Belle2;

REG_MODULE(EvtGenDecay)

EvtGenDecayModule::EvtGenDecayModule() : Module()
{
  setDescription("This module decays unstable particles using EvtGen. The "
                 "event should be already generated by another generator. "
                 "If you need to generate full event with EvtGen, then use "
                 "the module 'EvtGenInput'.");
  addParam("DecFile", m_DecFile, "EvtGen decay file (DECAY.DEC)",
           FileSystem::findFile(
             "generators/evtgen/decayfiles/DECAY_BELLE2.DEC", true));
  addParam("UserDecFile", m_UserDecFile, "User EvtGen decay file",
           std::string(""));
  addParam("MCParticleColName", m_MCParticleColName,
           "MCParticle collection name.", std::string(""));
  m_Initialized = false;
}

EvtGenDecayModule::~EvtGenDecayModule()
{
}

void EvtGenDecayModule::initialize()
{
  StoreArray<MCParticle> mcParticles(m_MCParticleColName);
  mcParticles.isRequired();
  const std::string defaultDecFile =
    FileSystem::findFile("generators/evtgen/decayfiles/DECAY_BELLE2.DEC", true);
  if (m_DecFile.empty()) {
    B2ERROR("No global decay file defined, please make sure "
            "the parameter 'DecFile' is set correctly.");
    return;
  }
  if (defaultDecFile.empty()) {
    B2WARNING("Cannot find default decay file");
  } else if (defaultDecFile != m_DecFile) {
    B2INFO("Using non-standard DECAY file \"" << m_DecFile << "\"");
  }
}

void EvtGenDecayModule::beginRun()
{
}

void EvtGenDecayModule::event()
{
  if (m_BeamParameters.hasChanged()) {
    if (!m_Initialized) {
      initializeGenerator();
    } else {
      B2FATAL("EvtGenDecayModule::event(): BeamParameters have changed within "
              "a job, this is not supported for EvtGen!");
    }
  }
  m_Graph.clear();
  m_Graph.loadList(m_MCParticleColName);
  m_Graph.generateList(
    m_MCParticleColName,
    MCParticleGraph::c_clearParticles | MCParticleGraph::c_setDecayInfo |
    MCParticleGraph::c_checkCyclic);
}

void EvtGenDecayModule::endRun()
{
}

void EvtGenDecayModule::terminate()
{
}

void EvtGenDecayModule::initializeGenerator()
{
  m_EvtGenInterface.setup(m_DecFile, "", m_UserDecFile);
}

