#!/usr/bin/env python3

##########################################################################
# basf2 (Belle II Analysis Software Framework)                           #
# Author: The Belle II Collaboration                                     #
#                                                                        #
# See git log for contributors and copyright holders.                    #
# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
##########################################################################

import basf2 as b2
from optparse import OptionParser
import os
# --------------------------------------------------------------------
# Example of using ARICH reconstruction
# needs reconstructed tracks (Tracks), extrapolated to ARICH (ExtHits)
# (generated by evtgen_sim.py)
# Produces root file with flat ntuple from ARICHNtuple module
# --------------------------------------------------------------------

parser = OptionParser()
parser.add_option('-f', '--file', dest='filename',
                  default='ARICHRec.root')
(options, args) = parser.parse_args()

home = os.environ['BELLE2_LOCAL_DIR']

# Suppress messages and warnings during processing:
b2.set_log_level(b2.LogLevel.ERROR)

# Create path
main = b2.create_path()

# input root file
input_module = b2.register_module('RootInput')
input_module.param('inputFileName', home + "/ARICHEvents.root")
main.add_module(input_module)

# Histogram manager immediately after master module
histo = b2.register_module('HistoManager')
histo.param('histoFileName', 'DQMhistograms.root')  # File to save histograms
main.add_module(histo)

# Gearbox: access to database (xml files)
main.add_module('Gearbox')

# Geometry
geometry = b2.register_module('Geometry')
geometry.param('components', ['ARICH'])
main.add_module(geometry)

# ARICH digitizer
main.add_module('ARICHDigitizer')

# convert ARICHDigits to ARICHHits
main.add_module('ARICHFillHits')

# ARICH reconstruction
# calculate PID likelihoods for all tracks
main.add_module('ARICHReconstructor')

# ARICH Ntuple
# create flat ntuple for performance analysis
arichNtuple = b2.register_module('ARICHNtuple')
arichNtuple.param('outputFile', options.filename)
main.add_module(arichNtuple)

# ARICH DQM
# create DQM occupancy plots
main.add_module('ARICHDQM')

# Uncomment to store DataStore content to root file
# output = register_module('RootOutput')
# output.param('outputFileName', 'DataStore.root')
# main.add_module(output)

# Show progress of processing
main.add_module('Progress')

# Process events
b2.process(main)

# Print call statistics
print(b2.statistics)
