Import('env')

env['LIBS'] = ['framework',
               'trg_trg',
               'mdst_dataobjects',
               'cdc_dataobjects',
               'cdc',
               'trg_cdc',
               'trg_cdc_dataobjects']
#print env.Dump()

# loader = env.SharedObject(source='../houghtracking/src/xsi_loader.cpp', CPPPATH=['../houghtracking/include'])
# env.Append(LIBS=['xsi_loader', 'dl', 'rt'])

Return('env')
