Import('env')

if env.has_key('HAS_TEVE'):
  if not env['HAS_TEVE']:
    print "Event display disabled, please recompile root with opengl support (on Debian/Ubuntu you'll probably only need to install libglu1-mesa-dev and rebuild)"

  env['CONTINUE'] = env['HAS_TEVE']
  env['LIBS'] = ['$ROOT_LIBS', 'GuiHtml', 'framework', 'geometry',
                 'vxd', 'pxd_dataobjects', 'svd_dataobjects', 'svd', 'cdc_dataobjects',
                 'cdc', 'bklm_dataobjects', 'mdst_dataobjects', 'eklm_dataobjects',
                 'simulation_dataobjects', 'tracking_dataobjects','arich',
                 'genfit2'] + env['TEVE_LIBS']


Return('env')
