Import('env')

env['LIBS'] = ['framework', 
			   'cdc_dataobjects', 
			   'pxd_dataobjects', 
			   'svd_dataobjects',
               'geometry',			   
			   'tracking_trackFindingCDC',
               'tracking_dataobjects', 
               'tracking_ckf',
               'tracking']
Return('env')
