#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
<header>
  <contact>tracking@belle2.kek.jp</contact>
  <input>EvtGenSimNoBkg.root</input>
  <output>VXDTF2TrackingValidation.root</output>
  <description>This module validates that the VXDTF2 SVD-ONLY is capable of reconstructing tracks in Y(4S) runs.</description>
</header>
"""

VALIDATION_OUTPUT_FILE = 'SVDTF2TrackingValidation.root'
N_EVENTS = 1000
ACTIVE = True

import basf2
basf2.set_random_seed(1337)

import logging

from tracking.validation.run import TrackingValidationRun
import tracking


class VXDTF2_SVD_ONLY(TrackingValidationRun):
    """
    Class for the validation of the VXDTF2 SVD-ONLY track finder
    """

    #: number of events to process
    n_events = N_EVENTS
    #: Generator to be used in the simulation (-so)
    generator_module = 'generic'
    #: root input file to use, in generated by central validation script
    root_input_file = '../EvtGenSimNoBkg.root'
    #: Use all Belle 2 detector components -> None
    components = None

    #: lambda method which is used by the validation to add the vxd finder modules
    finder_module = staticmethod(lambda path: tracking.add_vxd_track_finding_vxdtf2(path, components=["SVD"]))

    #: fit the tracks after the track finder
    fit_tracks = True

    #: use only hits from the SVD detector
    tracking_coverage = {
        'WhichParticles': ['SVD'],  # Include all particles seen in the SVD detector, also secondaries
        'UsePXDHits': False,
        'UseSVDHits': True,
        'UseCDCHits': False,
    }

    #: also create pull distributions
    pulls = True

    #: write to output file
    output_file_name = VALIDATION_OUTPUT_FILE


def main():
    """
    create and execute the VXDTF2 SVD-ONLY validation
    """
    validation_run = VXDTF2_SVD_ONLY()
    validation_run.configure_and_execute_from_commandline()


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    if ACTIVE:
        main()
