Import('env')

env['LIBS'] = ['klm_dataobjects', 'klm_dbobjects',
               'analysis', 'analysis_dataobjects', 
               'calibration', 'calibration_dataobjects',
               'framework',
               'geometry',
               'mdst_dataobjects',
               'simulation',
               '$ROOT_LIBS']

Return('env')
