Import('env')

env['LIBS'] = ['eklm_dataobjects', 'eklm_dbobjects', 'eklm',
               'bklm_dbobjects', 'bklm',
               'klm_dataobjects', 'klm_dbobjects', 'framework', '$ROOT_LIBS']

Return('env')
