Import('env')

env['LIBS'] = ['CLHEP','framework', 'analysis_dataobjects', 'analysis_OrcaKinFit', 
	      'analysis_DecayDescriptor', 'mdst_dataobjects',
	      'analysis_utility', '$ROOT_LIBS']

Return('env')
