Import('env')

env['LIBS'] = [
    #'boost_chrono',
    'framework',
    #'geometry',
    #'pxd', 
    'pxd_dataobjects',
    #'svd',
    'svd_dataobjects',
    'vxd', 'vxd_dataobjects',
    'genfit2',
    'tracking',
    #'tracking_dataobjects',
    ]
Return('env')
