Import('env')

env['LIBS'] = ['framework', 
               'simulation_dataobjects', 
	       'vxd_dataobjects',
           'vtx_dataobjects',
	       'pxd_dataobjects',
	       'svd_dataobjects',
	       'cdc_dataobjects',
	       'top_dataobjects',
	       'arich_dataobjects',
	       'ecl_dataobjects',
	       'klm_dataobjects',
               '$ROOT_LIBS']

Return('env')
