Import('env')

env['LIBS'] = [
    '$ROOT_LIBS',
    "framework",
    "analysis_utility",
    "tracking_dataobjects",
    "hlt_softwaretrigger_dbobjects",
    "hlt_softwaretrigger_dataobjects",
    "analysis_dataobjects",
    "analysis_ClusterUtility",
    "mdst_dataobjects"
]

Return('env')

