Import('env')

env['CONTINUE'] = True

env['LIBS'] = ['$ROOT_LIBS', 'Geom',
               '$GEANT4_LIBS', 'CLHEP',
               'boost_serialization',
               'boost_python', 'boost_filesystem',
               '$PYTHON_LIBS', '$XML_LIBS',
               'framework', 'nsm2_basf2', 'pthread', 'ncurses', 'pq',
		]

Return('env')
