Import('env')

#env['CONTINUE'] = False

env['LIBS'] = ['$ROOT_LIBS', 'Geom',
               '$GEANT4_LIBS', 'CLHEP',
               'boost_serialization',
               'boost_python', 'boost_filesystem',
               '$PYTHON_LIBS', '$XML_LIBS',
               'framework', 'rawdata',
	       'nsm2_b2lib', 'nsm2_corelib']

Return('env')
