Import('env')

#These are the libraries the module has to be linked against
env['LIBS'] = ['online_book_awesome_dataobjects', 
               'mdst_dataobjects',
               '$ROOT_LIBS',
              ]

Return('env')
