Import('env')

env['LIBS'] = ['cdc_dataobjects',
               'framework',
               'tracking_trackFindingCDC',
               'mdst_dataobjects',
               'simulation_dataobjects']
Return('env')
