drop table "configinfo.field";
drop table "configinfo.field.type";
drop table "configinfo.field.type.enum";
drop table "configinfo:copper:1";
drop table "configinfo:copper.hslb:1";
drop table "configinfo:ropc:1";
drop table "configinfo:ropc.from_hosts:1";
drop table "configinfo:runcontrol:1";
drop table "configinfo:runcontrol.node:1";
drop table "configinfo:hvchannel:1";
drop table runnumberinfo;
drop table "logger:1";
drop table "runsetting:1";
drop table "runsummary:1";
drop table "runsummary.nsmdata:1";
drop table "runsummary.nodestate:1";

drop function if exists groupname(int);
drop function if exists groupname_by_node(int);
drop function if exists nodename(int);
drop function if exists tablename(int);
drop function if exists tablename_by_field(int);
drop function if exists tablename_by_configinfo(text);
drop function if exists fieldname(int);
drop function if exists fieldtype(int);
drop function if exists fieldalias(int);
drop function if exists fieldnames();
drop function if exists fieldnames(text, int);
drop function if exists configid(text, text, text, int);
drop function if exists configid(text, text);
drop function if exists confignames();
drop function if exists confignames(text);
drop function if exists loggernames(text);
drop function if exists nodenames(text);
drop function if exists nodenames();
drop function if exists addnode(text, text);
drop function if exists addgroup(text);
drop function if exists addtable(text, int, boolean, boolean);
drop function if exists addtable(text, boolean, boolean);
drop function if exists addconfig(text, text, text, int);
drop function if exists addlogger(text, text);
drop function if exists addfield(text, int, text, int, text, int);
drop function if exists addfield(text, int, text, int, int);
drop function if exists fieldid(text, text, text);

drop table if exists fieldinfo_names;
drop table if exists loggerinfo_names;
drop table if exists loggerinfo;
drop table if exists configinfo_names;
drop table if exists configinfo;
drop table if exists "fieldinfo.type.enum";
drop table if exists "fieldinfo.type";
drop table if exists "fieldinfo";
drop table if exists tableinfo;
drop table if exists nodeinfo_names;
drop table if exists nodeinfo;
drop table if exists groupinfo;

