Import('env')

# env['CONTINUE'] = False

env['LIBS'] = ['framework', 'mdst_dataobjects', 'pxd_dataobjects', 'svd_dataobjects', 'tracking_dataobjects', 'cdc_dataobjects', 'bklm_dataobjects', 'eklm_dataobjects']

Return('env')
