Import('env')

# env['CONTINUE'] = False

env['LIBS'] = ['framework', 'mdst_dataobjects', 'vxd_dataobjects', 'pxd_dataobjects', 'svd_dataobjects', 'tracking_dataobjects', 'cdc_dataobjects', 'genfit2']

Return('env')
