# -*- coding: utf-8 -*-
# vim: syntax=python

Import('env')

env['LIBS'] = [
    'framework',
    'skim_softwaretrigger_dataobjects',
    'skim_softwaretrigger_dbobjects',
    'skim',
    '$ROOT_LIBS',
    "framework",
    "tracking_dataobjects",
    "mdst_dataobjects"
    ]

Return('env')

