Import('env')

env['TOOLS_LIBS']['dqm-check-size'] = ['framework',
                                       'zmq',
                                       'stdc++',
                                       '$ROOT_LIBS']

Return('env')