Import('env')

env['LIBS'] = ['framework', 'bklm_dataobjects', 'bklm_dbobjects',
               'eklm_dataobjects', 'eklm_dbobjects', 'simulation_dataobjects',
               'mdst_dataobjects', 'eklm', '$ROOT_LIBS', 'CLHEP']

Return('env')
