Import('env')

env['LIBS'] = ['CLHEP', 'framework', 'belle_legacy', 'mdst_dataobjects', 'b2bii', 'analysis_dataobjects', 'analysis_VertexFitting', 'ecl_dataobjects', 'tracking_dataobjects']

Return('env')
