Import('env')

env['TOOLS_LIBS']['mwreaderd'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']
env['TOOLS_LIBS']['mwnsmread'] = ['daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib', 'pthread']

Return('env')
