Import('env')

env['LIBS'] = ['framework', 'genfit2', 'calibration', '$ROOT_LIBS',
               'alignment_dataobjects', 'calibration_dataobjects',
               'analysis_dataobjects', 'mdst_dataobjects', 'alignment',
               'bklm_dataobjects', 'cdc_dataobjects', 'vxd_dataobjects',
               'tracking_dataobjects', 'tracking', 'pxd_dataobjects', 'svd_dataobjects', 'vxd']

Return('env')
