Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'top_dataobjects',
               'simulation_dataobjects', 'mdst_dataobjects',
               '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP']

Return('env')
