Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'top_dataobjects',
               'geometry_dbobjects', 'mdst_dataobjects', 
               '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP']

Return('env')
