Import('env')

env['LIBS'] = ['klm_eklm_dataobjects','klm_eklm_dbobjects',
               'klm_dataobjects', 'klm_dbobjects', 'klm',
               'framework',
               'rawdata_dataobjects',
               '$ROOT_LIBS']

Return('env')
