Import('env')

env['LIBS'] = [
    'tracking',
    "framework",
    'genfit2',
    'mdst_dataobjects',
    'simulation_dataobjects',
    '$ROOT_LIBS',
    '$PYTHON_LIBS',
    'cdc_dataobjects'
    ]

Return('env')
