Import('env')

#import os

# Mark this folder as a sub library
env.Dictionary()['SUBLIB'] = True

# Additional libraries
env['LIBS'] = [
    'mdst_dataobjects',
    'mdst_dbobjects',
    'tracking',
    'tracking_trackFindingCDC',
    'tracking_dataobjects',
    'framework',
    'svd_dataobjects',
    'vxd',
    '$ROOT_LIBS',
    ]

Return('env')
