CFLAGS = -I../drv -g

TARGETS += copper-sysreset readcpr readadc jig-start reset-fifo reset-fifo-and-finesse single-read-fifo freqcheck data2tcp read-finesse-register read-copper-register monitor-copper-register

all: ${TARGETS}

clean:
	rm ${TARGETS}
