Import('env')
# This file specifies the dependencies of your Analyis code to parts of the
# Belle 2 Software. It should be fine for most analysis but if you need to link
# against additional libraries pleas put them here.
env['LIBS'] = [
    'mdst_dataobjects',
    'analysis_dataobjects',
    'analysis',
    'framework',
    '$ROOT_LIBS',
    'klm',
    'framework',
    'rawdata_dataobjects',
    'klm_dataobjects', 
    'tracking_dataobjects'
]
Return('env')
