Import('env')

env['LIBS'] = [
    'klm',
    'klm_dataobjects',
    'klm_dbobjects',
    'analysis_dataobjects',
    'framework',
    'mdst_dataobjects',
    'tracking_dataobjects',
    '$ROOT_LIBS',
]

Return('env')
