Import('env')

env['LIBS'] = [
    'tracking_trackFindingCDC',
    'tracking_trackingUtilities',
    'cdc',
    'cdc_dataobjects',
    'framework',
    '$ROOT_LIBS',
    '$PYTHON_LIBS',
    ]

Return('env')
