Import('env')

env['LIBS'] = ['framework', 'reconstruction_dataobjects', 'generators_dataobjects',
               'tracking_dataobjects', 'top_dataobjects', 
      	       'arich_dataobjects', 'analysis_dataobjects', '$ROOT_LIBS']

Return('env')
