TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += xxx.db
#DB += rcnode.db
#DB += hvnode.db
#DB += hv.db
#DB += konno_hv.db
DB += arich_feb_temp.db
DB += arich_hv.db
DB += nsmvget_int.db
DB += nsmvget_float.db
DB += nsmvget_text.db
DB += nsmvset_int.db
DB += nsmvset_float.db
DB += nsmvset_text.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

