Import('env')

env['LIBS'] = [
    'boost_chrono',
    'framework',
#    'geometry',
    'mdst_dataobjects',
#    'pxd',
    'pxd_dataobjects',
#    'svd',
    'svd_dataobjects',
    'vxd', 
    'vxd_dataobjects',
    'genfit2',
    'tracking', 'tracking_dataobjects',
#    'testbeam_vxd_dataobjects'
    ]

Return('env')
