Import('env')

env['LIBS'] = ['framework', 'top_dataobjects', 'mdst_dataobjects',
               'tracking_dataobjects', 'top_reconstruction', '$ROOT_LIBS', 
	       'reconstruction_dataobjects', 'gfortran']

Return('env')
