Import('env')

env['LIBS'] = ['framework', 'top', 'top_dataobjects', 'mdst_dataobjects',
               'tracking_dataobjects', 'cdc_dataobjects', 'reconstruction_dataobjects', '$ROOT_LIBS']

Return('env')
