Import('env')

env['LIBS'] = ['background_mixbkg', 'background_dataobjects', 'simulation_dataobjects',
  'mdst_dataobjects', 'framework', 'pxd_dataobjects', 'svd_dataobjects',
  'vxd_dataobjects', 'cdc_dataobjects', 'top_dataobjects', 'arich_dataobjects',
  'ecl_dataobjects', 'eklm_dataobjects', 'bklm_dataobjects']

Return('env')
