Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation',
               'simulation_dataobjects', 'generators_dataobjects',
               '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP']

Return('env')
