Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'bklm_dataobjects', 'bklm_dbobjects', 'alignment_dbobjects',
               'mdst_dataobjects',
               '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP']

Return('env')
