#ifdef TRACKFINDINGCDC_COMPILE_DEBUG
// Setup for debug during structural changes to the algorithm
#define TRACKFINDINGCDC_USE_ROOT
#define TRACKFINDINGCDC_USE_MC_FILTERS_FIRST_STAGE
#define TRACKFINDINGCDC_USE_MC_FILTERS_SECOND_STAGE
#define TRACKFINDINGCDC_USE_MC_INFORMATION
#endif


#ifdef TRACKFINDINGCDC_COMPILE_OPT
// Setup for profiling the real algorithm
#define TRACKFINDINGCDC_USE_SIMPLE_FILTERS_FIRST_STAGE
#define TRACKFINDINGCDC_USE_SIMPLE_FILTERS_SECOND_STAGE
#define TRACKFINDINGCDC_USE_CALLGRIND
#endif

#ifdef TRACKFINDINGCDC_COMPILE_CLANG
// Setup for investigating filter efficiency
//#define TRACKFINDINGCDC_USE_EVALUATE_FILTERS_FIRST_STAGE
//#define TRACKFINDINGCDC_USE_EVALUATE_FILTERS_SECOND_STAGE
#define TRACKFINDINGCDC_USE_SIMPLE_FILTERS_FIRST_STAGE
#define TRACKFINDINGCDC_USE_SIMPLE_FILTERS_SECOND_STAGE
#define TRACKFINDINGCDC_USE_MC_INFORMATION
#define TRACKFINDINGCDC_USE_ROOT
#endif



// Ensure that the Monte Carlo information is retrievable when needed
#if defined TRACKFINDINGCDC_USE_MC_FILTERS_FIRST_STAGE || \
  defined TRACKFINDINGCDC_USE_EVALUATE_FILTERS_FIRST_STAGE  || \
  defined TRACKFINDINGCDC_USE_MC_FILTERS_SECOND_STAGE || \
  defined TRACKFINDINGCDC_USE_EVALUATE_FILTERS_SECOND_STAGE

#ifndef TRACKFINDINGCDC_USE_MC_INFORMATION
#define TRACKFINDINGCDC_USE_MC_INFORMATION
#endif

#endif




