Import('env')

env['TOOLS_LIBS']['cdchvd'] = ['pthread', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
env['TOOLS_LIBS']['cdchv_dummy'] = ['pthread', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']

Return('env')
