Import('env')

env['LIBS'] = [
    'framework',
    'mdst_dataobjects',
    'vxd',
    'genfit2',
    'svd_dataobjects',
    'tracking', 
    'tracking_dataobjects',
    'vxd_dataobjects']

Return('env')

