MAKE = gmake

srcdir := $(subst config/../,,.)
top_srcdir := $(subst config/../,,../..)
VPATH := $(subst config/../,,.)

BELLE_CONFIG_DIR = /belle/belle/b20090127_0910/src/config

SUBDIRS =

PACKAGE = kkmc
VERSION = 1.0
BELLE_TOP_DIR = /belle/belle/b20090127_0910
RELATIVE_TOP_DIR = $(srcdir)/../../../..
BUILD_TOP_DIR = ../../../..
BUILD_INCLUDE_DIR := $(shell cd $(BUILD_TOP_DIR);pwd)/include

LIBRARIES = kkmc

packagedir = ..

include $(BELLE_CONFIG_DIR)/Makefile.common

