Import('env')

env['LIBS'] = ['klm', 'klm_dataobjects',
               'analysis_dataobjects',
               'calibration', 'calibration_dataobjects',
               'framework',
               'mdst_dataobjects',
               'tracking_dataobjects',
               '$ROOT_LIBS']

Return('env')
