Import('env')

# env['CONTINUE'] = False

env['LIBS'] = ['framework','analysis','mdst_dataobjects','analysis_dataobjects','top','arich_dataobjects','klm_dataobjects', 'analysis_utility']

Return('env')
