Import('env')
	
env['LIBS'] = ['tracking_trackingUtilities','$ROOT_LIBS','Minuit', 'cdc', 'cdc_dataobjects', 'framework',
	    'calibration', 'calibration_dataobjects', 'cdc_dbobjects']
env['SUBLIB'] = True

Return('env')
