Import('env')
	
env['LIBS'] = ['tracking_trackFindingCDC','$ROOT_LIBS','Minuit', 'cdc', 'cdc_dataobjects', 'framework',
	    'calibration', 'calibration_dataobjects']
env['SUBLIB'] = True

Return('env')
