#ifndef _ECL_SHAPER_DSPB_H
#define _ECL_SHAPER_DSPB_H


#define _ECL_SHAPER_DSPB_REG_Y0_START_ADDR 0x0300
#define _ECL_SHAPER_DSPB_REG_K_X           0x0301
#define _ECL_SHAPER_DSPB_REG_K_CHI         0x0302
#define _ECL_SHAPER_DSPB_REG_CHI_THRESHOLD 0x0303

#define _ECL_SHAPER_DSPB_REG_STAT_POINTER 0x0400
#define _ECL_SHAPER_DSPB_REG_STAT_CMD     0x0401
#define _ECL_SHAPER_DSPB_REG_STAT_CMD_MAKE_SNAPSHOT_BIT 0
#define _ECL_SHAPER_DSPB_REG_STAT_INFO    0x0402

#define _ECL_SHAPER_DSPB_STAT_POINTER_THREAD_STATE_BASE  0x00

#define _ECL_SHAPER_DSPB_STAT_POINTER_THREAD_TO_INIT     0x40
#define _ECL_SHAPER_DSPB_STAT_POINTER_THREAD_TO_HIT      0x41
#define _ECL_SHAPER_DSPB_STAT_POINTER_THREAD_TO_ADC_RDY  0x42
#define _ECL_SHAPER_DSPB_STAT_POINTER_THREAD_TO_FETCH    0x43
#define _ECL_SHAPER_DSPB_STAT_POINTER_THREAD_TO_RFL      0x44
#define _ECL_SHAPER_DSPB_STAT_POINTER_THREAD_TO_RFL_DONE 0x45
#define _ECL_SHAPER_DSPB_STAT_POINTER_THREAD_TO_STORE    0x46

#define _ECL_SHAPER_DSPB_REG_ID 0xFFF0
#define _ECL_SHAPER_DSPB_ID 0x0006

#define _ECL_SHAPER_DSPB_REG_HW_VER 0xFFF1
#define _ECL_SHAPER_DSPB_REG_FW_VER 0xFFF2

#endif
