/**************************************************************************
 * BASF2 (Belle Analysis Framework 2)                                     *
 * Copyright(C) 2015 - Belle II Collaboration                             *
 *                                                                        *
 * Author: The Belle II Collaboration                                     *
 * Contributors: Nils Braun                                               *
 *                                                                        *
 * This software is provided "as is" without any warranty.                *
 **************************************************************************/

#pragma once
#include <framework/core/Module.h>

#include <string>
#include <vector>

namespace Belle2 {
  class CopyTakenFlagInformationModule : public Module {

  public:

    /**
     * Constructor.
     */
    CopyTakenFlagInformationModule() : Module()
    {
      setDescription("Set all taken flags of the cdc wire hits to true, if there is no segment in the list including this hit and to false if there is one.");

      addParam("SegmentsStoreObjName",
               m_param_segmentsStoreObjName,
               "Name of the output StoreObjPtr of the segments generated by this module.",
               std::string("CDCRecoSegment2DVector"));
    }

    /**
     * Set all taken flags of the cdc wire hits to true, if there is no segment in the list including this hit
     * and to false if there is one.
     */
    void event();

    /// Parameter: Name of the output StoreObjPtr of the segments generated by this module.
    std::string m_param_segmentsStoreObjName;
  };
}
