Import('env')
env['TOOLS_LIBS']['make_bg_plots'] = ['svd','vxd','$ROOT_LIBS'];
env['TOOLS_LIBS']['compare_bars'] = ['svd', 'vxd', '$ROOT_LIBS'];
env['TOOLS_LIBS']['showbginfo'] = ['framework', 'background_dataobjects', 'boost_program_options', '$ROOT_LIBS']
env['TOOLS_LIBS']['setbgtime'] = ['framework', 'background_dataobjects', 'boost_program_options', '$ROOT_LIBS']

Return('env')
