/**************************************************************************
 * BASF2 (Belle Analysis Framework 2)                                     *
 * Copyright(C) 2015 - Belle II Collaboration                             *
 *                                                                        *
 * Author: The Belle II Collaboration                                     *
 * Contributors: Oliver Frost                                             *
 *                                                                        *
 * This software is provided "as is" without any warranty.                *
 **************************************************************************/
#pragma once

#include <tracking/trackFindingCDC/findlets/base/Findlet.h>

#include <vector>
#include <string>

namespace Belle2 {
  class ModuleParamList;

  namespace TrackFindingCDC {
    class CDCRecoSegment2D;

    /// Exports segments has genfit tracks
    class SegmentExporter : public Findlet<const CDCRecoSegment2D> {

    private:
      /// Type of the base class
      using Super = Findlet<const CDCRecoSegment2D>;

    public:
      /// Short description of the findlet
      std::string getDescription() override final;

      /// Add the parameters of the filter to the module.
      void exposeParameters(ModuleParamList* moduleParamList, const std::string& prefix) override final;

      /// Signal initialisation phase to register store array for export
      void initialize() override final;

      /// Write give segments into track store array
      void apply(const std::vector<CDCRecoSegment2D>& segments) override final;

    private:
      /// Parameter: Switch if genfit::TrackCandidates shall be generated for each segment.
      bool m_param_exportSegments = false;

      /// Parameter: Name of the output StoreArray of the Genfit track candidates generated by this module.
      std::string m_param_exportSegmentsInto = "SegmentRecoTracks";
    };
  }
}
