Import('env')

env['LIBS'] = [
    # 'tracking_dataobjects',
    'tracking_trackFindingCDC',
    # 'cdc',
    'cdc_dataobjects',
    # 'genfit2',
    # 'mdst_dataobjects',
    'framework'
    ]

env.Append(CXXFLAGS=['-Wshadow'])

Return('env')
