* File am_3.f generated by GRACE Ver. 2.00(37)        1996/05/14/12:00
* 
*          Fortran source code generator
*     (c)copyright 1990-1996 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
*             Graph No. 1 - 1
*         Generated No. 1
************************************************************************
      subroutine a3g1
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepina),
     &           ep7(4,lepina),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepina)
      DOUBLE COMPLEX av7(lintrn*lextrn*lepina)
      DOUBLE COMPLEX av8(lextrn*lintrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lintrn*lextrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = - pe4(i) - pe5(i) - pe6(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,ama**2,0.0d0)
      vm8 =  + 2.0d0*prod(4,5) + 2.0d0*prod(4,6) + 2.0d0*prod(5,6)
     &       + amne**2 + amta**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amel**2,0.0d0)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      if(jtgamm .eq. 0 .or. vm7 .gt. 0.0d0 ) then
          call smintv(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      else
          call smintp(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      endif
      call smintf(amel,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 photon
      call smffv(lextrn,lextrn,lepina,ew1,ew2,amel,amel,cael,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe3 electron
*     7(1): + pe8 electron
*     7(2): - pe7 photon
      call smffv(lintrn,lextrn,lepina,ew8,ew3,amel,amel,cael,
     &           ce8,ce3,ps8,ps3,ep7,lt7,av7)

*     8(0): - pe8 electron
*     8(1): - pe4 nu-e
*     8(2): - pe9 w-plus
      call smffv(lextrn,lintrn,lepinw,ew4,ew8,amne,amel,cwne,
     &           ce4,ce8,ps4,ps8,ep9,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 1
      indexg(5) = 2
      indexg(6) = 3

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 2 - 1
*         Generated No. 2
************************************************************************
      subroutine a3g2
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lintrn*lextrn*lepinz)
      DOUBLE COMPLEX av8(lextrn*lintrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lintrn*lextrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = - pe4(i) - pe5(i) - pe6(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  + 2.0d0*prod(4,5) + 2.0d0*prod(4,6) + 2.0d0*prod(5,6)
     &       + amne**2 + amta**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amel**2,0.0d0)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintf(amel,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew2,amel,amel,czel,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe3 electron
*     7(1): + pe8 electron
*     7(2): - pe7 z
      call smffv(lintrn,lextrn,lepinz,ew8,ew3,amel,amel,czel,
     &           ce8,ce3,ps8,ps3,ep7,lt7,av7)

*     8(0): - pe8 electron
*     8(1): - pe4 nu-e
*     8(2): - pe9 w-plus
      call smffv(lextrn,lintrn,lepinw,ew4,ew8,amne,amel,cwne,
     &           ce4,ce8,ps4,ps8,ep9,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 1
      indexg(5) = 2
      indexg(6) = 3

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 3 - 1
*         Generated No. 3
************************************************************************
      subroutine a3g3
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lextrn*lintrn*lepinz)
      DOUBLE COMPLEX av8(lintrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lextrn*lintrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = + pe3(i) + pe5(i) + pe6(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  + 2.0d0*prod(3,5) + 2.0d0*prod(3,6) + 2.0d0*prod(5,6)
     &       + amel**2 + amta**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amne**2,0.0d0)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintf(amne,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew2,amel,amel,czel,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe8 nu-e
*     7(1): - pe4 nu-e
*     7(2): - pe7 z
      call smffv(lextrn,lintrn,lepinz,ew4,ew8,amne,amne,czne,
     &           ce4,ce8,ps4,ps8,ep7,lt7,av7)

*     8(0): - pe3 electron
*     8(1): + pe8 nu-e
*     8(2): - pe9 w-plus
      call smffv(lintrn,lextrn,lepinw,ew8,ew3,amne,amel,cwne,
     &           ce8,ce3,ps8,ps3,ep9,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 3
      indexg(4) = 1
      indexg(5) = 2
      indexg(6) = 4

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 4 - 1
*         Generated No. 4
************************************************************************
      subroutine a3g4
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepina),
     &           ep7(4,lepina),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepina)
      DOUBLE COMPLEX av7(lextrn*lintrn*lepina)
      DOUBLE COMPLEX av8(lintrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lextrn*lintrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = + pe3(i) + pe4(i) + pe6(i)
        pe9(i) = - pe3(i) - pe4(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,ama**2,0.0d0)
      vm8 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,6) + 2.0d0*prod(4,6)
     &       + amel**2 + amne**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amta**2,0.0d0)
      vm9 =  + 2.0d0*prod(3,4) + amel**2 + amne**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      if(jtgamm .eq. 0 .or. vm7 .gt. 0.0d0 ) then
          call smintv(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      else
          call smintp(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      endif
      call smintf(amta,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 photon
      call smffv(lextrn,lextrn,lepina,ew1,ew2,amel,amel,cael,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe8 tau
*     7(1): - pe5 tau
*     7(2): - pe7 photon
      call smffv(lextrn,lintrn,lepina,ew5,ew8,amta,amta,cata,
     &           ce5,ce8,ps5,ps8,ep7,lt7,av7)

*     8(0): - pe6 nu-tau
*     8(1): + pe8 tau
*     8(2): + pe9 w-plus
      call smffv(lintrn,lextrn,lepinw,ew8,ew6,amta,amnt,cwta,
     &           ce8,ce6,ps8,ps6,ep9,lt8,av8)

*     9(0): - pe3 electron
*     9(1): - pe4 nu-e
*     9(2): - pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew3,amne,amel,cwne,
     &           ce4,ce3,ps4,ps3,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 4
      indexg(2) = 3
      indexg(3) = 6
      indexg(4) = 1
      indexg(5) = 2
      indexg(6) = 5

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 5 - 1
*         Generated No. 5
************************************************************************
      subroutine a3g5
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lextrn*lintrn*lepinz)
      DOUBLE COMPLEX av8(lintrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lextrn*lintrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = + pe3(i) + pe4(i) + pe6(i)
        pe9(i) = - pe3(i) - pe4(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,6) + 2.0d0*prod(4,6)
     &       + amel**2 + amne**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amta**2,0.0d0)
      vm9 =  + 2.0d0*prod(3,4) + amel**2 + amne**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintf(amta,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew2,amel,amel,czel,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe8 tau
*     7(1): - pe5 tau
*     7(2): - pe7 z
      call smffv(lextrn,lintrn,lepinz,ew5,ew8,amta,amta,czta,
     &           ce5,ce8,ps5,ps8,ep7,lt7,av7)

*     8(0): - pe6 nu-tau
*     8(1): + pe8 tau
*     8(2): + pe9 w-plus
      call smffv(lintrn,lextrn,lepinw,ew8,ew6,amta,amnt,cwta,
     &           ce8,ce6,ps8,ps6,ep9,lt8,av8)

*     9(0): - pe3 electron
*     9(1): - pe4 nu-e
*     9(2): - pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew3,amne,amel,cwne,
     &           ce4,ce3,ps4,ps3,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 4
      indexg(2) = 3
      indexg(3) = 6
      indexg(4) = 1
      indexg(5) = 2
      indexg(6) = 5

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 6 - 1
*         Generated No. 6
************************************************************************
      subroutine a3g6
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lintrn*lextrn*lepinz)
      DOUBLE COMPLEX av8(lextrn*lintrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lintrn*lextrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = - pe3(i) - pe4(i) - pe5(i)
        pe9(i) = - pe3(i) - pe4(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  + 2.0d0*prod(3,4) + 2.0d0*prod(3,5) + 2.0d0*prod(4,5)
     &       + amel**2 + amne**2 + amta**2
  208 continue
      call smprpd(aprop,vm8,amnt**2,0.0d0)
      vm9 =  + 2.0d0*prod(3,4) + amel**2 + amne**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintf(amnt,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew2,amel,amel,czel,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe6 nu-tau
*     7(1): + pe8 nu-tau
*     7(2): - pe7 z
      call smffv(lintrn,lextrn,lepinz,ew8,ew6,amnt,amnt,cznt,
     &           ce8,ce6,ps8,ps6,ep7,lt7,av7)

*     8(0): - pe8 nu-tau
*     8(1): - pe5 tau
*     8(2): + pe9 w-plus
      call smffv(lextrn,lintrn,lepinw,ew5,ew8,amta,amnt,cwta,
     &           ce5,ce8,ps5,ps8,ep9,lt8,av8)

*     9(0): - pe3 electron
*     9(1): - pe4 nu-e
*     9(2): - pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew3,amne,amel,cwne,
     &           ce4,ce3,ps4,ps3,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 4
      indexg(2) = 3
      indexg(3) = 5
      indexg(4) = 1
      indexg(5) = 2
      indexg(6) = 6

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 7 - 1
*         Generated No. 7
************************************************************************
      subroutine a3g7
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,vm7,
     &               vm8,vm9,ew7,ep7,ew8,ep8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     4440 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepina),
     &           ep7(4,lepina),ew8(lepinw),ep8(4,lepinw),
     &           ew9(lepinw),ep9(4,lepinw)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepina)
      DOUBLE COMPLEX av7(lepina*lepinw*lepinw)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lepinw*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lepinw)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = - pe3(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,ama**2,0.0d0)
      vm8 =  + 2.0d0*prod(3,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      if(jtgamm .eq. 0 .or. vm7 .gt. 0.0d0 ) then
          call smintv(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      else
          call smintp(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      endif
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 photon
      call smffv(lextrn,lextrn,lepina,ew1,ew2,amel,amel,cael,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe7 photon
*     7(1): - pe9 w-plus
*     7(2): + pe8 w-plus
      if( jano3v .eq. 0 ) then
         call smvvv(lepina,lepinw,lepinw,-1,-1,+1,caww,
     &              pe7,pe9,pe8,ep7,ep9,ep8,lt7,av7)
      else
         call smvww(lepina,lepinw,lepinw,-1,-1,+1,caww,
     &              pe7,pe9,pe8,1.0d0,andka,anlma,amw**2,
     &              ep7,ep9,ep8,lt7,av7)
      endif
*     8(0): - pe3 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew3,amne,amel,cwne,
     &           ce4,ce3,ps4,ps3,ep8,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,1,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,5,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 3
      indexg(5) = 1
      indexg(6) = 2

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 8 - 1
*         Generated No. 8
************************************************************************
      subroutine a3g8
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,vm7,
     &               vm8,vm9,ew7,ep7,ew8,ep8
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     1784 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepina),
     &           ep7(4,lepina),ew8(lepinw),ep8(4,lepinw)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepina)
      DOUBLE COMPLEX av7(lscalr*lepinw*lepina)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lscalr)
      DOUBLE COMPLEX av10(lextrn*lextrn*lscalr*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lscalr)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = - pe3(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,ama**2,0.0d0)
      vm8 =  + 2.0d0*prod(3,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,agauge(igauwb)*amx**2,amx*agx)

* Internal momenta
      if(jtgamm .eq. 0 .or. vm7 .gt. 0.0d0 ) then
          call smintv(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      else
          call smintp(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      endif
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
*     Scalar internal line i0009 ()

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 photon
      call smffv(lextrn,lextrn,lepina,ew1,ew2,amel,amel,cael,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe9 chi-plus
*     7(1): + pe8 w-plus
*     7(2): - pe7 photon
      call smsvv(lepinw,lepina,cwam,ep8,ep7,lt7,av7)

*     8(0): - pe3 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew3,amne,amel,cwne,
     &           ce4,ce3,ps4,ps3,ep8,lt8,av8)

*     9(0): + pe9 chi-plus
*     9(1): - pe6 nu-tau
*     9(2): - pe5 tau
      call smffs(lextrn,lextrn,ew5,ew6,amta,amnt,cpta,
     &           ce5,ce6,ps5,ps6,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,4,ew8,av8,av10,lt11,av11)
      call smcons(lt9,lt11,3,5,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 3
      indexg(5) = 1
      indexg(6) = 2

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 9 - 1
*         Generated No. 9
************************************************************************
      subroutine a3g9
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,vm7,
     &               vm8,vm9,ew7,ep7,ew8,ep8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     4440 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(lepinw),ep8(4,lepinw),
     &           ew9(lepinw),ep9(4,lepinw)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lepinz*lepinw*lepinw)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lepinw*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lepinw)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = - pe3(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  + 2.0d0*prod(3,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew2,amel,amel,czel,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe7 z
*     7(1): - pe9 w-plus
*     7(2): + pe8 w-plus
      if( jano3v .eq. 0 ) then
         call smvvv(lepinz,lepinw,lepinw,-1,-1,+1,czww,
     &              pe7,pe9,pe8,ep7,ep9,ep8,lt7,av7)
      else
         call smvww(lepinz,lepinw,lepinw,-1,-1,+1,czww,
     &              pe7,pe9,pe8,1.0d0,andkz,anlmz,amw**2,
     &              ep7,ep9,ep8,lt7,av7)
      endif
*     8(0): - pe3 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew3,amne,amel,cwne,
     &           ce4,ce3,ps4,ps3,ep8,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,1,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,5,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 3
      indexg(5) = 1
      indexg(6) = 2

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 10 - 1
*         Generated No. 10
************************************************************************
      subroutine a3g10
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,vm7,
     &               vm8,vm9,ew7,ep7,ew8,ep8
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     1784 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(lepinw),ep8(4,lepinw)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lscalr*lepinw*lepinz)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lscalr)
      DOUBLE COMPLEX av10(lextrn*lextrn*lscalr*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lscalr)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) - pe2(i)
        pe8(i) = - pe3(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  + 2.0d0*prod(1,2) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  + 2.0d0*prod(3,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,agauge(igauwb)*amx**2,amx*agx)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
*     Scalar internal line i0009 ()

* Vertices (10)

*     6(0): + pe2 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew2,amel,amel,czel,
     &           ce1,ce2,ps1,ps2,ep7,lt6,av6)

*     7(0): - pe9 chi-plus
*     7(1): + pe8 w-plus
*     7(2): - pe7 z
      call smsvv(lepinw,lepinz,cwzm,ep8,ep7,lt7,av7)

*     8(0): - pe3 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew3,amne,amel,cwne,
     &           ce4,ce3,ps4,ps3,ep8,lt8,av8)

*     9(0): + pe9 chi-plus
*     9(1): - pe6 nu-tau
*     9(2): - pe5 tau
      call smffs(lextrn,lextrn,ew5,ew6,amta,amnt,cpta,
     &           ce5,ce6,ps5,ps6,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,4,ew8,av8,av10,lt11,av11)
      call smcons(lt9,lt11,3,5,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 3
      indexg(5) = 1
      indexg(6) = 2

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 11 - 1
*         Generated No. 11
************************************************************************
      subroutine a3g11
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepina),
     &           ep7(4,lepina),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepina)
      DOUBLE COMPLEX av7(lintrn*lextrn*lepina)
      DOUBLE COMPLEX av8(lextrn*lintrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lintrn*lextrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = - pe4(i) - pe5(i) - pe6(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,ama**2,0.0d0)
      vm8 =  + 2.0d0*prod(4,5) + 2.0d0*prod(4,6) + 2.0d0*prod(5,6)
     &       + amne**2 + amta**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amel**2,0.0d0)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      if(jtgamm .eq. 0 .or. vm7 .gt. 0.0d0 ) then
          call smintv(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      else
          call smintp(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      endif
      call smintf(amel,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 photon
      call smffv(lextrn,lextrn,lepina,ew1,ew3,amel,amel,cael,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): + pe2 electron
*     7(1): + pe8 electron
*     7(2): - pe7 photon
      call smffv(lintrn,lextrn,lepina,ew8,ew2,amel,amel,cael,
     &           ce8,ce2,ps8,ps2,ep7,lt7,av7)

*     8(0): - pe8 electron
*     8(1): - pe4 nu-e
*     8(2): - pe9 w-plus
      call smffv(lextrn,lintrn,lepinw,ew4,ew8,amne,amel,cwne,
     &           ce4,ce8,ps4,ps8,ep9,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 2

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 12 - 1
*         Generated No. 12
************************************************************************
      subroutine a3g12
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lintrn*lextrn*lepinz)
      DOUBLE COMPLEX av8(lextrn*lintrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lintrn*lextrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = - pe4(i) - pe5(i) - pe6(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  + 2.0d0*prod(4,5) + 2.0d0*prod(4,6) + 2.0d0*prod(5,6)
     &       + amne**2 + amta**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amel**2,0.0d0)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintf(amel,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew3,amel,amel,czel,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): + pe2 electron
*     7(1): + pe8 electron
*     7(2): - pe7 z
      call smffv(lintrn,lextrn,lepinz,ew8,ew2,amel,amel,czel,
     &           ce8,ce2,ps8,ps2,ep7,lt7,av7)

*     8(0): - pe8 electron
*     8(1): - pe4 nu-e
*     8(2): - pe9 w-plus
      call smffv(lextrn,lintrn,lepinw,ew4,ew8,amne,amel,cwne,
     &           ce4,ce8,ps4,ps8,ep9,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 2

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 13 - 1
*         Generated No. 13
************************************************************************
      subroutine a3g13
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lextrn*lintrn*lepinz)
      DOUBLE COMPLEX av8(lintrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lextrn*lintrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = - pe2(i) + pe5(i) + pe6(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  - 2.0d0*prod(2,5) - 2.0d0*prod(2,6) + 2.0d0*prod(5,6)
     &       + amel**2 + amta**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amne**2,0.0d0)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintf(amne,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew3,amel,amel,czel,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): - pe8 nu-e
*     7(1): - pe4 nu-e
*     7(2): - pe7 z
      call smffv(lextrn,lintrn,lepinz,ew4,ew8,amne,amne,czne,
     &           ce4,ce8,ps4,ps8,ep7,lt7,av7)

*     8(0): + pe2 electron
*     8(1): + pe8 nu-e
*     8(2): - pe9 w-plus
      call smffv(lintrn,lextrn,lepinw,ew8,ew2,amne,amel,cwne,
     &           ce8,ce2,ps8,ps2,ep9,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 2
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 4

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 14 - 1
*         Generated No. 14
************************************************************************
      subroutine a3g14
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepina),
     &           ep7(4,lepina),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepina)
      DOUBLE COMPLEX av7(lextrn*lintrn*lepina)
      DOUBLE COMPLEX av8(lintrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lextrn*lintrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = - pe2(i) + pe4(i) + pe6(i)
        pe9(i) = + pe2(i) - pe4(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,ama**2,0.0d0)
      vm8 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,6) + 2.0d0*prod(4,6)
     &       + amel**2 + amne**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amta**2,0.0d0)
      vm9 =  - 2.0d0*prod(2,4) + amel**2 + amne**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      if(jtgamm .eq. 0 .or. vm7 .gt. 0.0d0 ) then
          call smintv(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      else
          call smintp(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      endif
      call smintf(amta,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 photon
      call smffv(lextrn,lextrn,lepina,ew1,ew3,amel,amel,cael,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): - pe8 tau
*     7(1): - pe5 tau
*     7(2): - pe7 photon
      call smffv(lextrn,lintrn,lepina,ew5,ew8,amta,amta,cata,
     &           ce5,ce8,ps5,ps8,ep7,lt7,av7)

*     8(0): - pe6 nu-tau
*     8(1): + pe8 tau
*     8(2): + pe9 w-plus
      call smffv(lintrn,lextrn,lepinw,ew8,ew6,amta,amnt,cwta,
     &           ce8,ce6,ps8,ps6,ep9,lt8,av8)

*     9(0): + pe2 electron
*     9(1): - pe4 nu-e
*     9(2): - pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew2,amne,amel,cwne,
     &           ce4,ce2,ps4,ps2,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 4
      indexg(2) = 2
      indexg(3) = 6
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 5

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 15 - 1
*         Generated No. 15
************************************************************************
      subroutine a3g15
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lextrn*lintrn*lepinz)
      DOUBLE COMPLEX av8(lintrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lextrn*lintrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = - pe2(i) + pe4(i) + pe6(i)
        pe9(i) = + pe2(i) - pe4(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,6) + 2.0d0*prod(4,6)
     &       + amel**2 + amne**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amta**2,0.0d0)
      vm9 =  - 2.0d0*prod(2,4) + amel**2 + amne**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintf(amta,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew3,amel,amel,czel,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): - pe8 tau
*     7(1): - pe5 tau
*     7(2): - pe7 z
      call smffv(lextrn,lintrn,lepinz,ew5,ew8,amta,amta,czta,
     &           ce5,ce8,ps5,ps8,ep7,lt7,av7)

*     8(0): - pe6 nu-tau
*     8(1): + pe8 tau
*     8(2): + pe9 w-plus
      call smffv(lintrn,lextrn,lepinw,ew8,ew6,amta,amnt,cwta,
     &           ce8,ce6,ps8,ps6,ep9,lt8,av8)

*     9(0): + pe2 electron
*     9(1): - pe4 nu-e
*     9(2): - pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew2,amne,amel,cwne,
     &           ce4,ce2,ps4,ps2,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,1,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 4
      indexg(2) = 2
      indexg(3) = 6
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 5

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 16 - 1
*         Generated No. 16
************************************************************************
      subroutine a3g16
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     3752 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lintrn*lextrn*lepinz)
      DOUBLE COMPLEX av8(lextrn*lintrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lintrn*lextrn)
      DOUBLE COMPLEX av11(lextrn*lepinw*lextrn*lextrn*lextrn)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = + pe2(i) - pe4(i) - pe5(i)
        pe9(i) = + pe2(i) - pe4(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  - 2.0d0*prod(2,4) - 2.0d0*prod(2,5) + 2.0d0*prod(4,5)
     &       + amel**2 + amne**2 + amta**2
  208 continue
      call smprpd(aprop,vm8,amnt**2,0.0d0)
      vm9 =  - 2.0d0*prod(2,4) + amel**2 + amne**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintf(amnt,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew3,amel,amel,czel,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): - pe6 nu-tau
*     7(1): + pe8 nu-tau
*     7(2): - pe7 z
      call smffv(lintrn,lextrn,lepinz,ew8,ew6,amnt,amnt,cznt,
     &           ce8,ce6,ps8,ps6,ep7,lt7,av7)

*     8(0): - pe8 nu-tau
*     8(1): - pe5 tau
*     8(2): + pe9 w-plus
      call smffv(lextrn,lintrn,lepinw,ew5,ew8,amta,amnt,cwta,
     &           ce5,ce8,ps5,ps8,ep9,lt8,av8)

*     9(0): + pe2 electron
*     9(1): - pe4 nu-e
*     9(2): - pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew2,amne,amel,cwne,
     &           ce4,ce2,ps4,ps2,ep9,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconf(lt8,lt10,2,3,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,2,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 4
      indexg(2) = 2
      indexg(3) = 5
      indexg(4) = 1
      indexg(5) = 3
      indexg(6) = 6

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 17 - 1
*         Generated No. 17
************************************************************************
      subroutine a3g17
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,vm7,
     &               vm8,vm9,ew7,ep7,ew8,ep8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     4440 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepina),
     &           ep7(4,lepina),ew8(lepinw),ep8(4,lepinw),
     &           ew9(lepinw),ep9(4,lepinw)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepina)
      DOUBLE COMPLEX av7(lepina*lepinw*lepinw)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lepinw*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lepinw)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = + pe2(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,ama**2,0.0d0)
      vm8 =  - 2.0d0*prod(2,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      if(jtgamm .eq. 0 .or. vm7 .gt. 0.0d0 ) then
          call smintv(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      else
          call smintp(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      endif
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 photon
      call smffv(lextrn,lextrn,lepina,ew1,ew3,amel,amel,cael,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): - pe7 photon
*     7(1): - pe9 w-plus
*     7(2): + pe8 w-plus
      if( jano3v .eq. 0 ) then
         call smvvv(lepina,lepinw,lepinw,-1,-1,+1,caww,
     &              pe7,pe9,pe8,ep7,ep9,ep8,lt7,av7)
      else
         call smvww(lepina,lepinw,lepinw,-1,-1,+1,caww,
     &              pe7,pe9,pe8,1.0d0,andka,anlma,amw**2,
     &              ep7,ep9,ep8,lt7,av7)
      endif
*     8(0): + pe2 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew2,amne,amel,cwne,
     &           ce4,ce2,ps4,ps2,ep8,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,1,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,5,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 2
      indexg(5) = 1
      indexg(6) = 3

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 18 - 1
*         Generated No. 18
************************************************************************
      subroutine a3g18
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,vm7,
     &               vm8,vm9,ew7,ep7,ew8,ep8
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     1784 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepina),
     &           ep7(4,lepina),ew8(lepinw),ep8(4,lepinw)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepina)
      DOUBLE COMPLEX av7(lscalr*lepinw*lepina)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lscalr)
      DOUBLE COMPLEX av10(lextrn*lextrn*lscalr*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lscalr)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = + pe2(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,ama**2,0.0d0)
      vm8 =  - 2.0d0*prod(2,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,agauge(igauwb)*amx**2,amx*agx)

* Internal momenta
      if(jtgamm .eq. 0 .or. vm7 .gt. 0.0d0 ) then
          call smintv(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      else
          call smintp(lepina,ama,pe7,ep7,ew7,vm7,igauab)
      endif
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
*     Scalar internal line i0009 ()

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 photon
      call smffv(lextrn,lextrn,lepina,ew1,ew3,amel,amel,cael,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): - pe9 chi-plus
*     7(1): + pe8 w-plus
*     7(2): - pe7 photon
      call smsvv(lepinw,lepina,cwam,ep8,ep7,lt7,av7)

*     8(0): + pe2 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew2,amne,amel,cwne,
     &           ce4,ce2,ps4,ps2,ep8,lt8,av8)

*     9(0): + pe9 chi-plus
*     9(1): - pe6 nu-tau
*     9(2): - pe5 tau
      call smffs(lextrn,lextrn,ew5,ew6,amta,amnt,cpta,
     &           ce5,ce6,ps5,ps6,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,4,ew8,av8,av10,lt11,av11)
      call smcons(lt9,lt11,3,5,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 2
      indexg(5) = 1
      indexg(6) = 3

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 19 - 1
*         Generated No. 19
************************************************************************
      subroutine a3g19
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,vm7,
     &               vm8,vm9,ew7,ep7,ew8,ep8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     4440 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(lepinw),ep8(4,lepinw),
     &           ew9(lepinw),ep9(4,lepinw)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lepinz*lepinw*lepinw)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lextrn*lepinw*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lepinw)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = + pe2(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  - 2.0d0*prod(2,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew3,amel,amel,czel,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): - pe7 z
*     7(1): - pe9 w-plus
*     7(2): + pe8 w-plus
      if( jano3v .eq. 0 ) then
         call smvvv(lepinz,lepinw,lepinw,-1,-1,+1,czww,
     &              pe7,pe9,pe8,ep7,ep9,ep8,lt7,av7)
      else
         call smvww(lepinz,lepinw,lepinw,-1,-1,+1,czww,
     &              pe7,pe9,pe8,1.0d0,andkz,anlmz,amw**2,
     &              ep7,ep9,ep8,lt7,av7)
      endif
*     8(0): + pe2 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew2,amne,amel,cwne,
     &           ce4,ce2,ps4,ps2,ep8,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconv(lt6,lt7,3,1,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,4,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,5,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 2
      indexg(5) = 1
      indexg(6) = 3

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 20 - 1
*         Generated No. 20
************************************************************************
      subroutine a3g20
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,vm7,
     &               vm8,vm9,ew7,ep7,ew8,ep8
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     1784 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinz),
     &           ep7(4,lepinz),ew8(lepinw),ep8(4,lepinw)
      DOUBLE COMPLEX av6(lextrn*lextrn*lepinz)
      DOUBLE COMPLEX av7(lscalr*lepinw*lepinz)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lscalr)
      DOUBLE COMPLEX av10(lextrn*lextrn*lscalr*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lscalr)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe1(i) + pe3(i)
        pe8(i) = + pe2(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(1,3) + amel**2 + amel**2
  207 continue
      call smprpd(aprop,vm7,amz**2,amz*agz)
      vm8 =  - 2.0d0*prod(2,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,agauge(igauwb)*amx**2,amx*agx)

* Internal momenta
      call smintv(lepinz,amz,pe7,ep7,ew7,vm7,igauzb)
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
*     Scalar internal line i0009 ()

* Vertices (10)

*     6(0): - pe3 electron
*     6(1): + pe1 electron
*     6(2): + pe7 z
      call smffv(lextrn,lextrn,lepinz,ew1,ew3,amel,amel,czel,
     &           ce1,ce3,ps1,ps3,ep7,lt6,av6)

*     7(0): - pe9 chi-plus
*     7(1): + pe8 w-plus
*     7(2): - pe7 z
      call smsvv(lepinw,lepinz,cwzm,ep8,ep7,lt7,av7)

*     8(0): + pe2 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew2,amne,amel,cwne,
     &           ce4,ce2,ps4,ps2,ep8,lt8,av8)

*     9(0): + pe9 chi-plus
*     9(1): - pe6 nu-tau
*     9(2): - pe5 tau
      call smffs(lextrn,lextrn,ew5,ew6,amta,amnt,cpta,
     &           ce5,ce6,ps5,ps6,lt9,av9)

      call smconv(lt6,lt7,3,3,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,4,ew8,av8,av10,lt11,av11)
      call smcons(lt9,lt11,3,5,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 2
      indexg(5) = 1
      indexg(6) = 3

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 21 - 1
*         Generated No. 21
************************************************************************
      subroutine a3g21
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce8,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ep7,ew8,ps8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     4264 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(lepinw),
     &           ep7(4,lepinw),ew8(2),ps8(4,3),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce8(2,4)
      DOUBLE COMPLEX av6(lextrn*lintrn*lepinw)
      DOUBLE COMPLEX av7(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av8(lintrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lepinw*lextrn*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lepinw)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = + pe2(i) - pe4(i)
        pe8(i) = + pe3(i) + pe5(i) + pe6(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(2,4) + amel**2 + amne**2
  207 continue
      call smprpd(aprop,vm7,amw**2,amw*agw)
      vm8 =  + 2.0d0*prod(3,5) + 2.0d0*prod(3,6) + 2.0d0*prod(5,6)
     &       + amel**2 + amta**2 + amnt**2
  208 continue
      call smprpd(aprop,vm8,amne**2,0.0d0)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintv(lepinw,amw,pe7,ep7,ew7,vm7,igauwb)
      call smintf(amne,pe8, vm8, ew8, ps8, ce8)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe8 nu-e
*     6(1): + pe1 electron
*     6(2): + pe7 w-plus
      call smffv(lextrn,lintrn,lepinw,ew1,ew8,amel,amne,cwel,
     &           ce1,ce8,ps1,ps8,ep7,lt6,av6)

*     7(0): + pe2 electron
*     7(1): - pe4 nu-e
*     7(2): - pe7 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew2,amne,amel,cwne,
     &           ce4,ce2,ps4,ps2,ep7,lt7,av7)

*     8(0): - pe3 electron
*     8(1): + pe8 nu-e
*     8(2): - pe9 w-plus
      call smffv(lintrn,lextrn,lepinw,ew8,ew3,amne,amel,cwne,
     &           ce8,ce3,ps8,ps3,ep9,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconf(lt6,lt8,2,1,ew8,av6,av8,lt10,av10)
      call smconv(lt7,lt10,3,2,ew7,av7,av10,lt11,av11)
      call smconv(lt9,lt11,3,5,ew9,av9,av11,lt,av)

      sym = + 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 2
      indexg(5) = 1
      indexg(6) = 3

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
*             Graph No. 22 - 1
*         Generated No. 22
************************************************************************
      subroutine a3g22
      implicit DOUBLE PRECISION(a-h,o-z)

      include 'incl1.f'
      include 'inclk.f'
*-----------------------------------------------------------------------
      common /amwork/ce7,av6,av7,av8,av9,av10,av11,pe7,pe8,pe9,
     &               vm7,vm8,vm9,ew7,ps7,ew8,ep8,ew9,ep9
      common /amwori/lt6,lt7,lt8,lt9,lt10,lt11
*     4264 + 108 bytes used

      integer    lt6(0:3),lt7(0:3),lt8(0:3),lt9(0:3),lt10(0:4),
     &           lt11(0:5)
      DOUBLE PRECISION     pe7(4),pe8(4),pe9(4),vm7,vm8,vm9,ew7(2),
     &           ps7(4,3),ew8(lepinw),ep8(4,lepinw),ew9(lepinw),
     &           ep9(4,lepinw)
      DOUBLE COMPLEX ce7(2,4)
      DOUBLE COMPLEX av6(lextrn*lintrn*lepinw)
      DOUBLE COMPLEX av7(lintrn*lextrn*lepinw)
      DOUBLE COMPLEX av8(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av9(lextrn*lextrn*lepinw)
      DOUBLE COMPLEX av10(lextrn*lepinw*lextrn*lepinw)
      DOUBLE COMPLEX av11(lextrn*lextrn*lextrn*lextrn*lepinw)
      DOUBLE COMPLEX atmp
*-----------------------------------------------------------------------
* Internal momenta
      do 100 i = 1, 4
        pe7(i) = - pe2(i) + pe5(i) + pe6(i)
        pe8(i) = - pe3(i) - pe4(i)
        pe9(i) = + pe5(i) + pe6(i)
  100 continue

* Denominators of propagators
      aprop         = 1.0d0
      vm7 =  - 2.0d0*prod(2,5) - 2.0d0*prod(2,6) + 2.0d0*prod(5,6)
     &       + amel**2 + amta**2 + amnt**2
  207 continue
      call smprpd(aprop,vm7,amne**2,0.0d0)
      vm8 =  + 2.0d0*prod(3,4) + amel**2 + amne**2
  208 continue
      call smprpd(aprop,vm8,amw**2,amw*agw)
      vm9 =  + 2.0d0*prod(5,6) + amta**2 + amnt**2
  209 continue
      call smprpd(aprop,vm9,amw**2,amw*agw)

* Internal momenta
      call smintf(amne,pe7, vm7, ew7, ps7, ce7)
      call smintv(lepinw,amw,pe8,ep8,ew8,vm8,igauwb)
      call smintv(lepinw,amw,pe9,ep9,ew9,vm9,igauwb)

* Vertices (10)

*     6(0): - pe7 nu-e
*     6(1): + pe1 electron
*     6(2): + pe8 w-plus
      call smffv(lextrn,lintrn,lepinw,ew1,ew7,amel,amne,cwel,
     &           ce1,ce7,ps1,ps7,ep8,lt6,av6)

*     7(0): + pe2 electron
*     7(1): + pe7 nu-e
*     7(2): - pe9 w-plus
      call smffv(lintrn,lextrn,lepinw,ew7,ew2,amne,amel,cwne,
     &           ce7,ce2,ps7,ps2,ep9,lt7,av7)

*     8(0): - pe3 electron
*     8(1): - pe4 nu-e
*     8(2): - pe8 w-plus
      call smffv(lextrn,lextrn,lepinw,ew4,ew3,amne,amel,cwne,
     &           ce4,ce3,ps4,ps3,ep8,lt8,av8)

*     9(0): - pe6 nu-tau
*     9(1): - pe5 tau
*     9(2): + pe9 w-plus
      call smffv(lextrn,lextrn,lepinw,ew5,ew6,amta,amnt,cwta,
     &           ce5,ce6,ps5,ps6,ep9,lt9,av9)

      call smconf(lt6,lt7,2,1,ew7,av6,av7,lt10,av10)
      call smconv(lt8,lt10,3,2,ew8,av8,av10,lt11,av11)
      call smconv(lt9,lt11,3,5,ew9,av9,av11,lt,av)

      sym = - 1.0d0
      cf  = + 1.0d0
      aprop         = cf*sym/aprop

      indexg(1) = 5
      indexg(2) = 6
      indexg(3) = 4
      indexg(4) = 3
      indexg(5) = 1
      indexg(6) = 2

      call ampord(lt, av, indexg, agcwrk)

      ancp(jgraph) = 0.0d0
*     nbase = 1
      do 500 ih = 0 , lag-1
         atmp    = agcwrk(ih)*aprop
         agc(ih,0) = agc(ih,0) + colmbf*atmp
         ancp(jgraph) = ancp(jgraph) + atmp*conjg(atmp)
  500 continue

      return
      end
