/**************************************************************************
 * basf2 (Belle II Analysis Software Framework)                           *
 * Author: The Belle II Collaboration                                     *
 *                                                                        *
 * See git log for contributors and copyright holders.                    *
 * This file is licensed under LGPL-3.0, see LICENSE.md.                  *
 **************************************************************************/
#pragma once

#include <tracking/trackFindingCDC/legendre/quadtree/QuadTreeProcessor.h>
#include <tracking/trackFindingCDC/legendre/precisionFunctions/PrecisionUtil.h>

#include <tracking/trackingUtilities/numerics/LookupTable.h>
#include <tracking/trackingUtilities/geometry/Vector2D.h>

#include <vector>

namespace Belle2 {

  namespace TrackingUtilities {
    class CDCWireHit;
  }

  namespace TrackFindingCDC {

    /** A QuadTreeProcessor for TrackHits */
    class AxialHitQuadTreeProcessor : public QuadTreeProcessor<long, float, const TrackingUtilities::CDCWireHit> {

    public:
      /**
       *  Get the standard lookup table containing equally spaces unit vectors (cos, sin)
       *
       *  It contains 2**16 + 1 sampling points between -pi and pi.
       */
      static const TrackingUtilities::LookupTable<TrackingUtilities::Vector2D>& getCosSinLookupTable();
      /**
       *  Constructs an array with the curvature bounds as generated by the default bin divisions
       */
      static std::vector<float> createCurvBound(YSpan curvSpan, int lastLevel);

    public:
      /// Constructor
      AxialHitQuadTreeProcessor(int lastLevel,
                                int seedLevel,
                                const XYSpans& ranges,
                                PrecisionUtil::PrecisionFunction precisionFunction);

      /**
       *  Constructor for the quad tree processor used in the off-origin extension.
       *  Currently only used in zero level mode to collect hits that are in a phase space part
       *  with respect to the given point.
       */
      AxialHitQuadTreeProcessor(const TrackingUtilities::Vector2D& localOrigin,
                                const YSpan& curvSpan,
                                const TrackingUtilities::LookupTable<TrackingUtilities::Vector2D>* cosSinLookupTable);

    protected: // Section of specialized functions
      /**
       * lastLevel depends on curvature of the track candidate
       */
      bool isLeaf(QuadTree* node) const final;

      /**
       * Return the new ranges. We do not use the standard ranges for the lower levels.
       * @param node quadtree node
       * @param i theta index of the child
       * @param j rho index of the child
       * @return returns ranges of the (i;j) child
       */
      XYSpans createChild(QuadTree* node, int i, int j) const final;

      /**
       * Check whether hit belongs to the quadtree node:
       * @param node quadtree node
       * @param wireHit hit being checked
       * @return returns true if Legendre curve of the hit crosses (geometrically) borders of the node
       */
      bool isInNode(QuadTree* node, const TrackingUtilities::CDCWireHit* wireHit) const final;

      /**
       * Insert the hits into the given nodes sharing the parts of the containment check
       * that do not depend on the individual node.
       *
       * The nodes handed to this function - the children of a common parent or the nodes of
       * the seed level - always form a grid in the phase space, in the sense that their theta
       * spans only take a few distinct values. All quantities that only depend on the hit and
       * on the theta span of a node are therefore computed once per hit and distinct theta
       * span instead of once for every hit and node pair.
       */
      void insertItemsInNodes(const std::vector<QuadTree*>& nodes,
                              const std::vector<Item*>& items) final;

    protected: // Implementation details
      /**
       * Check derivative of the Legendre curve.
       * @param node QuadTree node
       * @param wireHit pointer to the hit to check
       * @return returns true in cases:
       * @return    - positive derivative and no extremum in the node's ranges or
       * @return    - extremum located in the node's ranges
       * @return returns false in other cases (namely negative derivative
       *
       */
      bool checkDerivative(QuadTree* node, const TrackingUtilities::CDCWireHit* wireHit) const;

      /**
       * Checks whether extreme point is located within QuadTree node's ranges
       * @param node QuadTree node
       * @param wireHit hit to check
       * @return true or false
       */
      bool checkExtremum(QuadTree* node, const TrackingUtilities::CDCWireHit* wireHit) const;

    public: // debug stuff
      /// Draw QuadTree node
      void drawHits(std::vector<const TrackingUtilities::CDCWireHit*> hits, unsigned int color = 46) const;
      /// Draw QuadTree node
      void drawNode(QuadTree* node) const;

    private:
      /**
       *  Quantities entering the node containment check that only depend on the hit and on the
       *  theta span of a node - shared by all nodes that have the same theta span.
       */
      struct ThetaSpanCache {
        /// Lower theta bound of the nodes in this group as an index into the lookup table
        long xMin = 0;

        /// Upper theta bound of the nodes in this group as an index into the lookup table
        long xMax = 0;

        /// Unit vector (cos, sin) at the lower theta bound
        const TrackingUtilities::Vector2D* thetaVecMin = nullptr;

        /// Unit vector (cos, sin) at the upper theta bound
        const TrackingUtilities::Vector2D* thetaVecMax = nullptr;

        /// Legendre curve of the right passage hypothesis at the lower theta bound
        float rHitMinRight = 0;

        /// Legendre curve of the right passage hypothesis at the upper theta bound
        float rHitMaxRight = 0;

        /// Legendre curve of the left passage hypothesis at the lower theta bound
        float rHitMinLeft = 0;

        /// Legendre curve of the left passage hypothesis at the upper theta bound
        float rHitMaxLeft = 0;

        /// Derivative of the Legendre curve at the lower theta bound
        float rHitMinExtr = 0;

        /// Derivative of the Legendre curve at the upper theta bound
        float rHitMaxExtr = 0;

        /// Result of the derivative check for this theta span
        bool derivativeOk = false;

        /// Indicator that the extremum of the Legendre curve lies within this theta span
        bool hasExtremum = false;

        /// Indicator that the extremum is a candidate for the containment check
        bool extremumIsBetween = false;
      };

      /// Geometry of a node that is needed in the containment check
      struct NodeCache {
        /// Lower curvature bound of the node
        float yMin = 0;

        /// Upper curvature bound of the node
        float yMax = 0;

        /// Index of the theta span of the node in the theta span cache
        int iThetaSpan = 0;

        /// Indicator that the forward direction of the hit has to be checked for this node
        bool needsDerivativeCheck = false;
      };

      /// Reusable buffer with the per theta span quantities - one entry per distinct theta span
      std::vector<ThetaSpanCache> m_thetaSpanCaches;

      /// Reusable buffer with the per node quantities - one entry per node
      std::vector<NodeCache> m_nodeCaches;

    private:
      /// Lambda which holds resolution function for the quadtree
      PrecisionUtil::PrecisionFunction m_precisionFunction;

      /// Local origin on which the phase space coordinates are centered
      TrackingUtilities::Vector2D m_localOrigin;

      /// Pinned lookup table for precomputed cosine and sine values
      const TrackingUtilities::LookupTable<TrackingUtilities::Vector2D>* m_cosSinLookupTable;

      /// The curvature above which the trajectory is considered a curler.
      const double c_curlCurv = 0.02;

      /**
       *  Indicator whether the two sided phases space insertion check should be used
       *  This option should automatically split back to back tracks in the low curvature regions
       */
      bool m_twoSidedPhaseSpace;
    };
  }
}
