Import('env')

env['LIBS'] = ['framework', 'simulation_dataobjects', 'arich_dataobjects', 'arich']
 	
# env['LIBS'] = ['framework','arich_dataobjects','arich',
#               '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP']
 	
Return('env')
