Import('env')
 	
env['LIBS'] = ['framework', 'tracking_dataobjects', 'mdst_dataobjects', 'arich_dataobjects', 'arich',
               'genfit2', '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP']
 	
Return('env')
