---
programs:
  - ["b2hlt_distributor",
     "--expressRecoMode",
     "--input", "tcp://localhost:5000",
     "--output", "tcp://*:4000",
     "--monitor", "tcp://*:8000"]

  - ["python3", "steering/steering.py",
     "--input", "tcp://localhost:4000",
     "--output", "tcp://localhost:4001",
     "--dqm", "tcp://localhost:6000",
     "--expressreco"]
  - ["python3", "steering/steering.py",
     "--input", "tcp://localhost:4000",
     "--output", "tcp://localhost:4001",
     "--dqm", "tcp://localhost:6001",
     "--expressreco"]
  
  - ["b2hlt_proxycollector",
     "--input", "tcp://*:4001",
     "--output", "tcp://localhost:4002",
     "--monitor", "tcp://*:8001"]

  - ["b2hlt_collector",
     "--lax",
     "--input", "tcp://*:4002",
     "--output", "tcp://*:4003",
     "--monitor", "tcp://*:8002"]

  - ["python3", "steering/display.py",
     "--input", "tcp://localhost:4003"]

  - ["b2hlt_proxyhistoserver",
     "--input", "tcp://*:6000",
     "--output", "tcp://localhost:7000",
     "--monitor", "tcp://*:8004",
     "--timeout", "30"]
  - ["b2hlt_proxyhistoserver",
     "--input", "tcp://*:6001",
     "--output", "tcp://localhost:7000",
     "--monitor", "tcp://*:8005",
     "--timeout", "30"]

  - ["b2hlt_finalhistoserver",
     "--input", "tcp://*:7000",
     "--rootFileName", "root_dqm_{run_number}_{experiment_number}.root",
     "--monitor", "tcp://*:8006"]

input: 5000
monitor:
  distributor: "tcp://localhost:8000"
  proxycollector: "tcp://localhost:8001"
  collector: "tcp://localhost:8002"
  proxyhistoserver1: "tcp://localhost:8004"
  proxyhistoserver2: "tcp://localhost:8005"
  dqmserver: "tcp://localhost:8006"
