import os

Import('env')

env['SUBLIB'] = True
env['LIBS'] = ['$ROOT_LIBS', 'generators_dataobjects', 'framework', 'pxd_dataobjects', 'svd_dataobjects', 'vxd_dataobjects','cdc_dataobjects']

Return('env')
