#!/bin/bash
# Thomas Kuhr, Tom Fifield
# 2010-01
# As DIRAC uses its own versions of some libraries, let's try to avoid trashing
# the system by sourcing before calling
DIRACROOT=${DIRACROOT:-~/dirac/pro}
. $DIRACROOT/../bashrc
# check if gbasf2 is unreachable by PATH
which gbasf2.py >/dev/null 2>&1
if [ $? -eq 1 ]
then
 BELLE2_LOCAL_DIR=${BELLE2_LOCAL_DIR:-..}
 ${BELLE2_LOCAL_DIR}/gbasf2/gbasf2.py "$@"  
else
 gbasf2.py "$@"
fi

exit $?
