Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'simulation_dataobjects', 'genfit2', 'pxd_dbobjects',
               '$ROOT_LIBS', 'vxd','vxd_dataobjects', 'pxd_dataobjects', 'mdst_dataobjects', 'alignment_dataobjects', 'calibration', 'calibration_dataobjects']

Return('env')
