Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'simulation_dataobjects', 'genfit',
               'generators_dataobjects', '$ROOT_LIBS', 'vxd', 'pxd_dataobjects']

Return('env')
