Import('env')

env['LIBS'] = ['framework', 'analysis', 'analysis_utility',
               'analysis_dataobjects', 'analysis_DecayDescriptor',
               'analysis_ParticleCombiner', 'mdst_dataobjects',
               '$ROOT_LIBS']

Return('env')
