Import('env')

env['LIBS'] = [
    'framework', 
    'tracking',
    'tracking_dataobjects',
    'cdc_dataobjects',
    'mdst_dataobjects',
    'pxd_dataobjects',
    'svd_dataobjects',
    'vtx_dataobjects',
    'genfit2']
Return('env')
