Import('env')

env['LIBS'] = [
    'framework', 'geometry', 'simulation', 'svd_dbobjects',
    'genfit2', '$ROOT_LIBS', 'Geom', 'vxd', 'vxd_dbobjects',
    'vxd_dataobjects',
    'svd_dataobjects', 'mdst_dataobjects',
    'simulation_dataobjects',
    'calibration','calibration_dataobjects', 
    'RooFit', 'RooFitCore', 'RooStats'
]

# env.Append(CPPDEFINES=["DISABLE_CONST_DBOBJECTS"])

Return('env')
