/**************************************************************************
 * BASF2 (Belle Analysis Framework 2)                                     *
 * Copyright(C) 2015 - Belle II Collaboration                             *
 *                                                                        *
 * Author: The Belle II Collaboration                                     *
 * Contributors: Oliver Frost                                             *
 *                                                                        *
 * This software is provided "as is" without any warranty.                *
 **************************************************************************/
#include <tracking/trackFindingCDC/basemodules/TrackFinderCDCFromSegmentsModule.h>

#include <tracking/trackFindingCDC/rootification/StoreWrappedObjPtr.h>

using namespace Belle2;
using namespace TrackFindingCDC;

TrackFinderCDCFromSegmentsModule::TrackFinderCDCFromSegmentsModule()
  : TrackFinderCDCBaseModule()
  , m_param_segmentsStoreObjName("CDCSegment2DVector")
{
  this->addParam("SegmentsStoreObjName",
                 m_param_segmentsStoreObjName,
                 "Name of the output StoreObjPtr of the segments generated by this module.",
                 m_param_segmentsStoreObjName);
}

void TrackFinderCDCFromSegmentsModule::initialize()
{
  TrackFinderCDCBaseModule::initialize();
  StoreWrappedObjPtr<std::vector<CDCSegment2D>> storedSegments(m_param_segmentsStoreObjName);
  storedSegments.isRequired();
}

void TrackFinderCDCFromSegmentsModule::generate(std::vector<CDCTrack>& tracks)
{
// Aquire the store vector
  StoreWrappedObjPtr<std::vector<CDCSegment2D>> storedSegments(m_param_segmentsStoreObjName);
  if (not storedSegments) {
    B2WARNING("The segments have not been created.");
    return;
  }
  std::vector<CDCSegment2D>& segments = *storedSegments;
  this->generate(segments, tracks);
}
