Import('env')

env['LIBS'] = ['framework', 'cdc', 'cdc_dataobjects', 'genfit2','tracking_dataobjects', 'mdst_dataobjects', 'vxd', 'vxd_dataobjects', 'pxd_dataobjects', 'svd_dataobjects']

Return('env')
