Import('env')

env['LIBS'] = ['framework', 'geometry', 'top_dataobjects','generators_dataobjects',
               'tracking_dataobjects','top',
               '$ROOT_LIBS', '$GEANT4_LIBS', 'CLHEP','gfortran']

Return('env')
