Import('env')

env['LIBS'] = ['framework', 'geometry', 'top_dataobjects', 'generators_dataobjects',
               'tracking_dataobjects', 'top', 'top_reconstruction', '$ROOT_LIBS', 'gfortran']

Return('env')
