Import('env')
env['LIBS'] = ['framework',
               '$ROOT_LIBS',
               'calibration',
               'cdc', 'cdc_dataobjects',
               'calibration_dataobjects', 'calibration_dbobjects',
               'alignment_dataobjects'
              ]
env['SUBLIB'] = True
Return('env')
