#! /bin/tcsh
foreach x (02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17)
  ssh hlttb$x "cd belle2/daq/rfarm/run;rf_eventprocessor rfarm1.conf > & evp_hlttb$x/nsmlog.log" &
end
ssh hltsr01 "cd belle2/daq/rfarm/run;rf_eventserver rfarm1.conf > & collector/nsmlog.log " &
ssh hltsr01 "cd belle2/daq/rfarm/run;rf_outputserver rfarm1.conf > & distributor/nsmlog.log" &
ssh hlttbsrv "cd belle2/daq/rfarm/run;setenv NSM2_HOST hlttbsrv; rf_master rfarm1.conf > & master/nsmlog.log" &

