#! /bin/tcsh
foreach x (02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17)
  ssh hlttb$x killall rf_eventprocessor basf2 sock2rbr rb2sockr
  ssh hlttb$x clshm
end
ssh hltsr01 "killall rf_eventserver sock2rbr rb2sockr; clshm"
ssh hltsr01 "killall rf_outputserver sock2rbr rb2sockr basf2; clshm"
ssh hlttb01 "killall rf_master; clshm"
