Import('env')

env['LIBS'] = [
	    'framework', 
	    'analysis_dataobjects', 
	    'ecl_dataobjects',
	    'mdst_dataobjects',
	    '$ROOT_LIBS',
            'TMVA',
	    'EG', 
	    'EvtGen'
            ]
Return('env')

