Import('env')

env['LIBS'] = ['framework', 'generators_dataobjects', 'arich_dataobjects', 'top_dataobjects',
                'tracking_dataobjects', 'ecl_dataobjects', '$ROOT_LIBS', 'EG']
Return('env')

