Import('env')

env['LIBS'] = [
    'framework',
    'analysis_dataobjects',
    'mdst_dataobjects',
    '$ROOT_LIBS',
    'TMVA',
    'EG',
    'RooFit',
    'RooFitCore',
    'RooStats',
    'skim_L1Emulator_dataobjects'
]
Return('env')
