Import('env')

#2013/06/17 env['CONTINUE'] = False

env['LIBS'] = ['framework']
#env.Append(CPPDEFINES = {'TRASAN_WINDOW_GTK':None,
#	                 'TRASAN_WINDOW_GTK_HOUGH':None,
#	                 'TRASAN_WINDOW_GTK_SZ':None,
#			 'TRASAN_DEBUG':None,
#			 'TRASAN_DEBUG_DETAIL':None})
#env.ParseConfig('pkg-config --cflags --libs gtkmm-2.4')
#print env.Dump()

Return('env')
