Import('env')

env['CONTINUE'] = False
import commands
import os.path
if os.path.exists("/etc/redhat-release"):
   ss = (commands.getoutput("cat /etc/redhat-release")).split(" ")
   osver = 0.0
   for s in ss:
      try:
         osver = float(s)
	 break
      except ValueError:
         continue
   if osver < 6.0:
      env['TOOLS_LIBS']['rcview'] = ['pthread', 'ncurses', 'readline', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
   elif osver > 6.0:
      env['TOOLS_LIBS']['rcview'] = ['pthread', 'ncurses', 'tinfo', 'readline', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']
else:
      env['TOOLS_LIBS']['rcview'] = ['pthread', 'ncurses', 'readline', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']

env['TOOLS_LIBS']['rcrequest'] = ['pthread', '$PGSQL_LIBS', 'daq', 'framework', 'nsm2_b2lib', 'nsm2_corelib']

Return('env')


