Import('env')

env['LIBS'] = ['framework', 'mdst_dataobjects', 'reconstruction_dataobjects',
               'tracking_dataobjects', 'top_dataobjects', 'arich_dataobjects',
               'ecl_dataobjects', '$ROOT_LIBS']

Return('env')
