Import('env')

env['LIBS'] = ['framework', 'simulation', 'generators_dataobjects', 'geometry',
               '$ROOT_LIBS', 'Geom', 'EG', 'g4root',
               '$GEANT4_LIBS', 'CLHEP']

Return('env')
