Import('env')

env['LIBS'] = [
    'framework', 'geometry', 'pxd_dbobjects', '$ROOT_LIBS', 
    'vxd', 'vxd_dataobjects', 'pxd', 'pxd_dataobjects', 'calibration',
    'calibration_dataobjects'
]

env['SUBLIB'] = True


Return('env')
