Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'simulation_dataobjects', 'genfit',
               'generators_dataobjects', '$ROOT_LIBS', 'vxd','vxd_dataobjects', 'pxd_dataobjects', 'testbeam']

Return('env')
