Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'vxd_dbobjects',
               'vxd_dataobjects', 'genfit2', '$ROOT_LIBS', '$GEANT4_LIBS', 'alignment_dbobjects',
	       'analysis', 'analysis_utility', 'mdst_dataobjects']

Return('env')
