Import('env')

env['LIBS'] = ['framework', 'geometry', 'simulation', 'simulation_dataobjects', 'vxd_dbobjects',
               'vxd_dataobjects', 'mdst_dataobjects', 'genfit2', '$ROOT_LIBS', '$GEANT4_LIBS']

Return('env')
