Import('env')

env['LIBS'] = ['framework', 'analysis', 'analysis_DecayDescriptor',
               'analysis_ParticleCombiner',
               'analysis_dataobjects', 'mdst_dataobjects',
               '$ROOT_LIBS']

Return('env')
