Import('env')

env['SUBLIB'] = True
env['LIBS'] = ['framework',
               '$ROOT_LIBS', 'EvtGen', 'pythia8', 'PhotosCxxInterface.a', 'HepMC',
               'TauolaCxxInterface', 'TauolaFortran',
               'PhotosFortran', 'EvtGenExternal', 'Geom', 'CLHEP',
               'mdst_dataobjects']

Return('env')
