Import('env')

env['LIBS'] = [
    'framework', 'framework_io', 'framework_utilities_testhelpers',
    '$ROOT_LIBS',
    'boost_filesystem', 'boost_system',
    '$XML_LIBS',
    '$SQLITE_LIBS',
]

Return('env')
