#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""General steering file for running skims."""

import argparse
from importlib import import_module

import basf2 as b2
import modularAnalysis as ma
import skimExpertFunctions as expert


def get_argument_parser():
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("skim", choices=["LeptonicUntagged"])
    parser.add_argument("-n", "--max-input-events", default=0)
    parser.add_argument(
        "-i",
        "--input-file-list",
        dest="InputFileList",
        nargs="+",
        default=[expert.get_test_file("MC12_mixedBGx1")],
    )
    parser.add_argument("-o", "--output-udst-name", dest="OutputFileName")

    return parser


def import_skim_module(SkimName):
    # TODO: Write generalised method of finding modules
    if SkimName == "LeptonicUntagged":
        import_module("skim.leptonic")
    else:
        raise NotImplementedError


def main():
    parser = get_argument_parser()
    args = parser.parse_args()

    path = b2.Path()
    ma.inputMdstList("default", args.InputFileList, path=path)

    SkimModule = import_skim_module(args.skim)
    Skim = getattr(SkimModule, args.skim)()

    Skim.set_skim_logging(path)
    Skim.setup(path)
    Skim.build_lists(path)
    Skim.output_udst(path)

    b2.process(path, max_event=args.max_input_events)


if __name__ == "__main__":
    main()
