#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""General steering file for running combined skims."""

import argparse
from importlib import import_module

import basf2 as b2
import modularAnalysis as ma
from skimExpertFunctions import CombinedSkim
from skim.registry import Registry


class CustomHelpFormatter(argparse.HelpFormatter):
    """Custom formatter for argparse which prints the valid choices for an
    argument in the help string.
    """

    def _get_help_string(self, action):
        if action.choices:
            return (
                action.help + " Valid options are: " + ", ".join(action.choices) + "."
            )
        else:
            return action.help


def get_argument_parser():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=CustomHelpFormatter,
    )

    SkimGroup = parser.add_mutually_exclusive_group(required=True)
    SkimGroup.add_argument(
        "-s",
        "--skims",
        choices=Registry.names,
        nargs="+",
        default=[],
        metavar="Skim",
        help="Skims to be run.",
    )
    SkimGroup.add_argument(
        "-m",
        "--module",
        choices=Registry.modules,
        metavar="Module",
        help="Module to run all skims for.",
    )

    parser.add_argument(
        "-n",
        "--max-input-events",
        dest="MaxInputEvents",
        metavar="MaxInputEvents",
        type=int,
        help="Maximum number of input events to process.",
    )
    parser.add_argument(
        "-i",
        "--input-file-list",
        dest="InputFileList",
        metavar="InputFileList",
        nargs="+",
        help="Input file list",
    )

    return parser


def get_skim_function(SkimName):
    """Get the skim class constructor for the given skim.

    This is achieved by importing the module listed alongside the skim name in the
    `skim.registry.Registry`.

    Parameters:
        SkimName (str): Name of the skim to be found.

    Returns:
        SkimFunction: The class constructor for the given skim.
    """
    ModuleName = Registry.get_skim_module(SkimName)
    SkimModule = import_module(f"skim.{ModuleName}")
    return getattr(SkimModule, SkimName)


def main():
    parser = get_argument_parser()
    args = parser.parse_args()

    path = b2.Path()

    if args.skims:
        skims = list(set(args.skims))
        SkimObjects = [get_skim_function(skim)() for skim in skims]
    elif args.module:
        SkimObjects = [
            get_skim_function(skim)()
            for skim in Registry.get_skims_in_module(args.module)
        ]

    SkimObject = CombinedSkim(*SkimObjects)

    InputFileList = args.InputFileList or list({Skim.TestFile for Skim in SkimObjects})
    ma.inputMdstList("default", InputFileList, path=path)
    SkimObject(path)

    args.MaxInputEvents = args.MaxInputEvents or 0
    b2.process(path, max_event=args.MaxInputEvents)
    print(b2.statistics())


if __name__ == "__main__":
    main()
