Import('env')

env['LIBS'] = [
    'boost_chrono',
    'framework', 
    'pxd_dataobjects',
    # 'svd',
    'svd_dataobjects',
    'vxd_dataobjects',
    'tracking', 'tracking_dataobjects',
    'mdst_dataobjects',
#    'testbeam_vxd_dataobjects',
    ]
Return('env')
# ', 'tracking_sharedClasses'
